<wsdl:definitions
     name="StagingDB"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/EnterpriseService.Transactions/BillPaymentES/StagingDB"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/EnterpriseService.Transactions/BillPaymentES/StagingDB"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/StagingDB"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="StagingDB_plt" >
    <plt:role name="StagingDB_role" >
      <plt:portType name="tns:StagingDB_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/StagingDB" schemaLocation="../Schemas/StagingDB_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CustMasterTranTableCollection_msg">
        <wsdl:part name="CustMasterTranTableCollection" element="top:CustMasterTranTableCollection"/>
    </wsdl:message>
    <wsdl:portType name="StagingDB_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:CustMasterTranTableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
