<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:app="http://ougwebcomponent.components.oug.osgi.scorex.com/"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://jaxb.dev.java.net/array"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Experian/AppMetadata/wsdls/OUGWS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ougWS" namespace="http://ougwebcomponent.components.oug.osgi.scorex.com/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 19 17:20:47 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <xsl:variable name="date" select="xp20:day-from-dateTime(xp20:current-dateTime())"/>
    <xsl:variable name="month" select="xp20:month-from-dateTime(xp20:current-dateTime())"/>
    <xsl:variable name="year" select="xp20:year-from-dateTime(xp20:current-dateTime())"/>
    <xsl:variable name="period" select="/eo:ESBMsg/eo:RqData/eo:Account/eo:LoanPeriod"/>
    <xsl:variable name="repayment"
                  select="translate(substring-before(xp20:add-dayTimeDuration-to-dateTime(xp20:current-dateTime(),concat('P',$period,'M')),'T' ),'-','')"/>
    <app:ougWS>
      <workflow_name>Instore</workflow_name>
      <data_flux>
        <item>CustID</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
        </item>
      </data_flux>
      <data_flux>
        <item>Product</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:LoanProducts"/>
        </item>
      </data_flux>
      <data_flux>
        <item>MaritalStatus</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:MaritalStatus"/>
        </item>
      </data_flux>
      <data_flux>
        <item>ResidentialStatus</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:ResidentialStatus"/>
        </item>
      </data_flux>
      <data_flux>
        <item>TimeAtAdressYY</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:TimeAtAdressYY"/>
        </item>
      </data_flux>
      <data_flux>
        <item>TimeAtAdressMM</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:TimeAtAdressMM"/>
        </item>
      </data_flux>
      <data_flux>
        <item>EmploymentStatus</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:Employment/com:EmploymentStatus"/>
        </item>
      </data_flux>
      <data_flux>
        <item>EmployerName</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:Employment/com:CompanyName"/>
        </item>
      </data_flux>
      <data_flux>
        <item>EmployerPhone</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:CompleteNumber"/>
        </item>
      </data_flux>
      <data_flux>
        <item>TimeInEmploymentYY</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:Employment/com:TimeInEmploymentYY"/>
        </item>
      </data_flux>
      <data_flux>
        <item>TimeInEmploymentMM</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:Employment/com:TimeInEmploymentMM"/>
        </item>
      </data_flux>
      <data_flux>
        <item>RequestedLoanAmount</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:LoanAmount"/>
        </item>
      </data_flux>
      <data_flux>
        <item>Term</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:LoanPeriod"/>
        </item>
      </data_flux>
      <data_flux>
        <item>RepaymentStartDate</item>
        <item>
          <xsl:choose>
            <xsl:when test="$date &lt;= 15">
              <xsl:choose>
                <xsl:when test="$month &lt; 10">
                  <xsl:value-of select="concat('200',$month,$year)"/>
                </xsl:when>
                <xsl:when test="$month >= 10">
                  <xsl:value-of select="concat('20',$month,$year)"/>
                </xsl:when>
              </xsl:choose>
            </xsl:when>
            <xsl:when test="$date > 15">
              <xsl:choose>
                <xsl:when test="$month &lt; 10">
                  <xsl:value-of select="concat('200',$month+1,$year)"/>
                </xsl:when>
                <xsl:when test="$month >= 10">
                  <xsl:value-of select="concat('20',$month+1,$year)"/>
                </xsl:when>
              </xsl:choose>
            </xsl:when>
          </xsl:choose>
        </item>
      </data_flux>
      <data_flux>
        <item>RepaymentEndDate</item>
        <item>
          <xsl:value-of select="concat(substring($repayment,7,2),substring($repayment,5,2),substring($repayment,1,4))"/>
        </item>
      </data_flux>
      <data_flux>
        <item>MerchantRef</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:MerchantReferenceNumber"/>
        </item>
      </data_flux>
      <data_flux>
        <item>MerchantID</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:MerchantID"/>
        </item>
      </data_flux>
      <data_flux>
        <item>Contribution</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:ClientContribution"/>
        </item>
      </data_flux>
      <data_flux>
        <item>BranchID</item>
        <item>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:CustomerIdentifier/com:BranchID"/>
        </item>
      </data_flux>
      <xsl:for-each select="/eo:ESBMsg/eo:RqData/eo:Account/com:GoodsCategory">
        <data_flux>
          <item>Good_Category<xsl:value-of select="position()"/></item>
          <item>
            <xsl:value-of select="com:Good_Category"/>
          </item>
        </data_flux>
        <data_flux>
          <item>Good<xsl:value-of select="position()"/></item>
          <item>
            <xsl:value-of select="com:Good"/>
          </item>
        </data_flux>
        <data_flux>
          <item>Good_Amount<xsl:value-of select="position()"/></item>
          <item>
            <xsl:value-of select="com:Good_Amount"/>
          </item>
        </data_flux>
      </xsl:for-each>
    </app:ougWS>
  </xsl:template>
</xsl:stylesheet>