<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:app="http://ougwebcomponent.components.oug.osgi.scorex.com/"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://jaxb.dev.java.net/array" xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Experian/AppMetadata/wsdls/OUGWS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ougWSResponse"
                                       namespace="http://ougwebcomponent.components.oug.osgi.scorex.com/"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 19 17:21:53 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <com:MsgID>1234</com:MsgID>
      <com:Source>WY4</com:Source>
      <com:MsgType>Enterprise</com:MsgType>
      <com:Service>AccountES</com:Service>
      <eo:RsData>
        <eo:Account>
          <custeo:Customer>
            <com:CustomerIdentifier>
              <com:CustomerID>
                <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='CustID']/item[2]"/>
              </com:CustomerID>
            </com:CustomerIdentifier>
          </custeo:Customer>
          <eo:LoanProducts>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Product']/item[2]"/>
          </eo:LoanProducts>
          <eo:ResponseCode>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='RespCode']/item[2]"/>
          </eo:ResponseCode>
          <eo:EffectiveInterestRate>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='EffectiveInterestRate']/item[2]"/>
          </eo:EffectiveInterestRate>
          <eo:Fees>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Fees']/item[2]"/>
          </eo:Fees>
          <eo:MinimumLoanTerm>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='MinimumLoanTerm']/item[2]"/>
          </eo:MinimumLoanTerm>
          <eo:MaximumLoanTerm>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='MaximumLoanTerm']/item[2]"/>
          </eo:MaximumLoanTerm>
          <eo:MaxCreditLimitAmnt>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Maximum_Credit_Limit']/item[2]"/>
          </eo:MaxCreditLimitAmnt>
          <eo:MinCreditLimitAmnt>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Minimum_Credit_Limit']/item[2]"/>
          </eo:MinCreditLimitAmnt>
          <eo:MaximumAffordableLoanAmount>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='MaximumAffordableLoanAmount']/item[2]"/>
          </eo:MaximumAffordableLoanAmount>
          <eo:MinimumLoanAmount>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='MinimumLoanAmount']/item[2]"/>
          </eo:MinimumLoanAmount>
          <eo:EazzyLoanLimit>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Shadow_Limit']/item[2]"/>
          </eo:EazzyLoanLimit>
          <eo:MaxPLLimitAmnt>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='MaximumLoanAmount']/item[2]"/>
          </eo:MaxPLLimitAmnt>
          <eo:MaxCCLimitAmnt>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='RecommendedLoanAmount']/item[2]"/>
          </eo:MaxCCLimitAmnt>
          <eo:MaxPLInstallment>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Affordable_Monthly_Repayment']/item[2]"/>
          </eo:MaxPLInstallment>
        </eo:Account>
        <com:Status>
          <xsl:choose>
            <xsl:when test="/app:ougWSResponse/data_flux[item[1]='Error_code']">
              <com:Code>
                <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Error_code']/item[2]"/>
              </com:Code>
               <com:Type>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Error_message']/item[2]"/>
          </com:Type>
          <com:Text>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='wf_rc_desc']/item[2]"/>
          </com:Text>
            </xsl:when>
            <xsl:when test="/app:ougWSResponse/data_flux[item[1]='Error_message']">
              <com:Code>ESB-100</com:Code>
               <com:Type>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='Error_message']/item[2]"/>
          </com:Type>
          <com:Text>
            <xsl:value-of select="/app:ougWSResponse/data_flux[item[1]='wf_rc_desc']/item[2]"/>
          </com:Text>
            </xsl:when>
            <xsl:otherwise>
              <com:Code>ESB-00</com:Code>
              <com:Type>Success</com:Type>
              <com:Text>Loan Limit Successful</com:Text>
            </xsl:otherwise>
          </xsl:choose>         
        </com:Status>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
