<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:app="http://ws.equitybank/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo app oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns1="http://schemas.xmlsoap.org/soap/http" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Payment/V1/PaymentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Safaricom/AppMetadata/wsdls/SafDealerService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="finRequest" namespace="http://ws.equitybank/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 08 17:53:23 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <app:finRequest>
      <dealer>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:Amount">
        <amount>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:Amount"/>
        </amount>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:BranchName">
        <branchName>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:BranchName"/>
        </branchName>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountID">
        <dealerAccountNumber>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountID"/>
        </dealerAccountNumber>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:DealerCode">
        <dealerCode>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:DealerCode"/>
        </dealerCode>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:DealerName">
        <dealerName>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:DealerName"/>
        </dealerName>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:UserID">
        <finacleUserId>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:UserID"/>
        </finacleUserId>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:PayMethod">
        <payMethod>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:PayMethod"/>
        </payMethod>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Payment/com:BillIdentifier/com:BillID">
        <payRef>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:BillIdentifier/com:BillID"/>
        </payRef>
        </xsl:if>
        <respCode/>
      </dealer>
    </app:finRequest>
  </xsl:template>
</xsl:stylesheet>
