<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo app oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/ftp/PRS_FTP_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="DepositAccountMasterFileInput"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 14 13:12:54 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="filename"/>
  <xsl:template match="/">
    <app:DepositAccountMasterFileInput>
      <app:HeaderLine>
        <app:LineIdentifier>H</app:LineIdentifier>
        <app:FileName>
          <xsl:value-of select="$filename"/>
        </app:FileName>
        <app:Date>2015-05-12</app:Date>
        <!--app:FileName>
          <xsl:value-of select="concat(/eo:ESBMsg/eo:RqData/@actionCode,'_Feed_',xp20:format-dateTime(xp20:current-date(),'[Y0001][M01][D01][H01][M01][s01]'))"/>
        </app:FileName>
        <app:Date>
          <xsl:value-of select="xp20:format-dateTime(xp20:current-date(),'[Y0001][M01][D01]')"/>
        </app:Date-->
      </app:HeaderLine>
      <xsl:for-each select="/eo:ESBMsg/eo:RqData/eo:Account">
        <app:DataLine>
          <app:LineIdentifier>D</app:LineIdentifier>
          <app:UnitID>
            <xsl:value-of select="com:AccountIdentifier/com:BankID"/>
          </app:UnitID>
          <app:CIF>
            <xsl:value-of select="custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
          </app:CIF>
          <app:DepositAccountNumber>
            <xsl:value-of select="com:AccountIdentifier/com:AccountID"/>
          </app:DepositAccountNumber>
		  <app:BilyetNumber>
            <xsl:value-of select="com:AccountIdentifier/com:AccountID"/>
          </app:BilyetNumber>
          <!--<app:BilyetNumber>
            <xsl:value-of select="com:TransactionReferenceNumber"/>
          </app:BilyetNumber>-->
          <app:Currency>
            <xsl:value-of select="com:AccountIdentifier/com:AccountCurrency"/>
          </app:Currency>
          <app:Status>
            <xsl:value-of select="eo:AccountStatus"/>
          </app:Status>
          <app:CurrentPrincipalAmount>
            <xsl:value-of select="com:Balance/com:BalanceAmount"/>
          </app:CurrentPrincipalAmount>
          <app:DepositAmount>
            <xsl:value-of select="com:Amount"/>
          </app:DepositAmount>
          <app:MaturityDate>
            <xsl:value-of select="eo:MaturityDate"/>
          </app:MaturityDate>
          <app:CurrentInterestRate>
            <xsl:value-of select="eo:CurrentInterestRate"/>
          </app:CurrentInterestRate>
          <app:BonusInterestRate/>
          <app:InterestToDate>
            <xsl:value-of select="eo:InterestToDate"/>
          </app:InterestToDate>
          <app:InterestRate>
            <xsl:value-of select="eo:InterestRate"/>
          </app:InterestRate>
          <app:TenorUnit/>
          <app:TenorValue>
            <xsl:value-of select="eo:TenorValue"/>
          </app:TenorValue>
          <app:DepositType/>
          <app:PostingDate>
            <xsl:value-of select="com:StartDate"/>
          </app:PostingDate>
          <app:MaturityInstructions>
            <xsl:value-of select="com:Remarks"/>
          </app:MaturityInstructions>
        </app:DataLine>
      </xsl:for-each>
      <app:TrailerLine>
        <app:LineIdentifier>T</app:LineIdentifier>
        <app:NumberOfRows>
          <xsl:value-of select="count (/eo:ESBMsg/eo:RqData/eo:Account )"/>
        </app:NumberOfRows>
      </app:TrailerLine>
    </app:DepositAccountMasterFileInput>
  </xsl:template>
</xsl:stylesheet>
