<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo app oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/ftp/PRS_FTP_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="LoanAccountMasterFileInput"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 14 13:29:22 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="filename"/>
  <xsl:template match="/">
    <app:LoanAccountMasterFileInput>
      <app:HeaderLine>
        <app:LineIdentifier>H</app:LineIdentifier>
        <app:FileName>
          <xsl:value-of select="$filename"/>
        </app:FileName>
        <app:Date>2015-05-12</app:Date>
        <!--app:FileName>
          <xsl:value-of select="concat(/eo:ESBMsg/eo:RqData/@actionCode,'_Feed_',xp20:format-dateTime(xp20:current-date(),'[Y0001][M01][D01][H01][M01][s01]'))"/>
        </app:FileName>
        <app:Date>
          <xsl:value-of select="xp20:format-dateTime(xp20:current-date(),'[Y0001][M01][D01]')"/>
        </app:Date-->
      </app:HeaderLine>
      <xsl:for-each select="/eo:ESBMsg/eo:RqData/eo:Account">
        <app:DataLine>
          <app:LineIdentifier>D</app:LineIdentifier>
          <app:UnitID>
            <xsl:value-of select="com:AccountIdentifier/com:BankID"/>
          </app:UnitID>
          <app:AccType>
            <xsl:value-of select="eo:AccountType"/>
          </app:AccType>
          <app:AccSubType>
            <xsl:value-of select="eo:AccountSubType"/>
          </app:AccSubType>
          <app:TotalLoanAmount>
            <xsl:value-of select="com:Amount"/>
          </app:TotalLoanAmount>
          <app:InterestAccrued>
            <xsl:value-of select="eo:InterestAccrued"/>
          </app:InterestAccrued>
          <app:SettlementCurrency>
            <xsl:value-of select="eo:SettlementCurrency"/>
          </app:SettlementCurrency>
          <app:LoanAccountNumber>
            <xsl:value-of select="com:AccountIdentifier/com:AccountID"/>
          </app:LoanAccountNumber>
          <app:LoanCurrency>
            <xsl:value-of select="com:AccountIdentifier/com:AccountCurrency"/>
          </app:LoanCurrency>
          <app:AccountName>
            <xsl:value-of select="custeo:Customer/com:Person/com:PersonName/com:FullName"/>
          </app:AccountName>
          <app:LoanType>
            <xsl:value-of select="eo:LoanType"/>
          </app:LoanType>
          <app:FundingAccount>
            <xsl:value-of select="eo:FundingAccount"/>
          </app:FundingAccount>
          <app:PaymentFrequency>
            <xsl:value-of select="eo:PaymentFrequency"/>
          </app:PaymentFrequency>
          <app:OriginalAmount>
            <xsl:value-of select="eo:Original_Amount"/>
          </app:OriginalAmount>
          <app:OutstandingAmount>
            <xsl:value-of select="eo:OutStanding_Amount"/>
          </app:OutstandingAmount>
          <app:PastDueAmount>
            <xsl:value-of select="eo:PastDueAmount"/>
          </app:PastDueAmount>
          <app:LastPaymentAmount>
            <xsl:value-of select="eo:LastPaymentAmount"/>
          </app:LastPaymentAmount>
          <app:LastPaymentReceivedDate>
            <xsl:value-of select="eo:LastPaymentReceivedDate"/>
          </app:LastPaymentReceivedDate>
          <app:TotalNumberofInstallments>
            <xsl:value-of select="eo:TotalNumberofInstallments"/>
          </app:TotalNumberofInstallments>
          <app:InstallmentsPaid>
            <xsl:value-of select="eo:InstallmentsPaid"/>
          </app:InstallmentsPaid>
          <app:LoanStartDate>
            <xsl:value-of select="com:StartDate"/>
          </app:LoanStartDate>
          <app:LoanMaturityDate>
            <xsl:value-of select="eo:MaturityDate"/>
          </app:LoanMaturityDate>
          <app:InterestRate>
            <xsl:value-of select="eo:InterestRate"/>
          </app:InterestRate>
          <app:NextPaymentDate>
            <xsl:value-of select="eo:NextPaymentDate"/>
          </app:NextPaymentDate>
          <app:NextPaymentAmount/>
          <app:PayoffAmount/>
          <app:PrincipelClosingBalance/>
          <app:DisbursementAccount>
            <xsl:value-of select="eo:DisbursementAccount"/>
          </app:DisbursementAccount>
          <app:InterestRepaymentAccount>
            <xsl:value-of select="eo:InterestRepaymentAccount"/>
          </app:InterestRepaymentAccount>
          <app:Loanstatus>
            <xsl:value-of select="eo:AccountStatus"/>
          </app:Loanstatus>
          <app:Tenure>
            <xsl:value-of select="eo:Tenure"/>
          </app:Tenure>
          <app:LoanClosureDate>
            <xsl:value-of select="com:EndDate"/>
          </app:LoanClosureDate>
          <app:ApprovedLimit>
            <xsl:value-of select="eo:ApprovedLimit"/>
          </app:ApprovedLimit>
          <app:PenaltyInterestRate/>
          <app:PenaltiesDue/>
          <app:DelinquencyStatus>
            <xsl:value-of select="eo:DelinquencyStatus"/>
          </app:DelinquencyStatus>
          <app:NextPrincipalDueDate>
            <xsl:value-of select="eo:NextPrincipalDueDate"/>
          </app:NextPrincipalDueDate>
          <app:NextInterestDueDate>
            <xsl:value-of select="eo:NextInterestDueDate"/>
          </app:NextInterestDueDate>
          <app:NoOfDelayedPayments>
            <xsl:value-of select="eo:NoofDelayed_Payments"/>
          </app:NoOfDelayedPayments>
          <app:DisbursedAmount>
            <xsl:value-of select="eo:DisbursedAmount"/>
          </app:DisbursedAmount>
        </app:DataLine>
      </xsl:for-each>
      <app:TrailerLine>
        <app:LineIdentifier>T</app:LineIdentifier>
        <app:NumberOfRows>
          <xsl:value-of select="count(/eo:ESBMsg/eo:RqData/eo:Project)"/>
        </app:NumberOfRows>
      </app:TrailerLine>
    </app:LoanAccountMasterFileInput>
  </xsl:template>
</xsl:stylesheet>
