<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:tns="http://xmlns.equitybank.co.ke/RM/MobileDevice/ListOfValues/V1"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://xmlns.equitybank.co.ke/EM/Resilience/ListOfValues/V1"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:eo="http://xmlns.equitybank.co.ke/EO/Resilience/ListOfValues/V1"
                xmlns:listeo="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/ListOfValues/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/ListOfValues/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Resilience/ListOfValues/V1/ListOfValuesEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/ListOfValues/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/ListOfValues/V1/ListOfValuesRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="QueryListOfValuesResponseRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/ListOfValues/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAR 12 14:01:47 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ro:QueryListOfValuesResponseRM>
      <xsl:for-each select="/listeo:ESBMsg/listeo:RsData/listeo:ListOfValues">
        <listeo:ListOfValues>
          <listeo:ListName>
            <xsl:value-of select="listeo:ListName"/>
          </listeo:ListName>
          <listeo:ValueList>
            <xsl:for-each select="listeo:ValueList/listeo:Value">
              <listeo:Value>
                <listeo:Code>
                  <xsl:value-of select="listeo:Code"/>
                </listeo:Code>
                <listeo:Description>
                  <xsl:value-of select="listeo:Description"/>
                </listeo:Description>
                <listeo:Parent>
                  <xsl:value-of select="listeo:Parent"/>
                </listeo:Parent>
              </listeo:Value>
            </xsl:for-each>
          </listeo:ValueList>
        </listeo:ListOfValues>
      </xsl:for-each>
    </ro:QueryListOfValuesResponseRM>
  </xsl:template>
</xsl:stylesheet>