<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="2.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Cheque/V1"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Instruments/Cheque/V1/ChequeEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Cheque/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Instruments/Cheque/V1/ChequeEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Cheque/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUN 04 09:54:44 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <soap:Body xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
      <ns0:ESBMsg>
        <com:MsgID>
          <xsl:value-of select="/ns0:ESBMsg/com:MsgID"/>
        </com:MsgID>
        <com:Source>
          <xsl:value-of select="/ns0:ESBMsg/com:Source"/>
        </com:Source>
        <com:MsgType>
          <xsl:value-of select="/ns0:ESBMsg/com:MsgType"/>
        </com:MsgType>
        <com:Service>
          <xsl:value-of select="/ns0:ESBMsg/com:Service"/>
        </com:Service>
        <ns0:RqData>
          <xsl:for-each select="(/ns0:ESBMsg/ns0:RqData/ns0:Cheque/ns0:BeginChequeNumber) to (/ns0:ESBMsg/ns0:RqData/ns0:Cheque/ns0:EndChequeNumber)">
            <ns0:Cheque>
              <com:ChequeIdentifier>
                <com:BankID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Cheque/com:ChequeIdentifier/com:BankID"/>
                </com:BankID>
                <com:BranchID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Cheque/com:ChequeIdentifier/com:BranchID"/>
                </com:BranchID>
                <com:AccountID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Cheque/com:ChequeIdentifier/com:AccountID"/>
                </com:AccountID>
              </com:ChequeIdentifier>
              <com:BeginChequeNumber>
                <xsl:value-of select="position ( )+ /ns0:ESBMsg/ns0:RqData/ns0:Cheque/ns0:BeginChequeNumber -1 "/>
              </com:BeginChequeNumber>
              <com:EndChequeNumber>
                <xsl:value-of select="position ( )+ /ns0:ESBMsg/ns0:RqData/ns0:Cheque/ns0:BeginChequeNumber -1 "/>
              </com:EndChequeNumber>
              <com:StopPaymentInstruction>
                <com:ReasonCode>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Cheque/com:StopPaymentInstruction/com:ReasonCode"/>
                </com:ReasonCode>
              </com:StopPaymentInstruction>
            </ns0:Cheque>
          </xsl:for-each>
        </ns0:RqData>
      </ns0:ESBMsg>
    </soap:Body>
  </xsl:template>
</xsl:stylesheet>