<wsdl:definitions
     name="StagingDBAdapterBS"
     targetNamespace="http://xmlns.equitybank.co.ke/ESB/ES/StagingDB/Adapter/db"
     xmlns:tns="http://xmlns.equitybank.co.ke/ESB/ES/StagingDB/Adapter/db"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/StagingDBAdapterBS"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="StagingDBAdapterBS_plt" >
    <plt:role name="StagingDBAdapterBS_role" >
      <plt:portType name="tns:StagingDBAdapterBS_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/StagingDBAdapterBS" schemaLocation="../../Schemas/StagingDBAdapterBS_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="CustMasterTranTableCollection_msg">
        <wsdl:part name="CustMasterTranTableCollection" element="top:CustMasterTranTableCollection"/>
    </wsdl:message>
    <wsdl:portType name="StagingDBAdapterBS_ptt">
        <wsdl:operation name="update">
            <wsdl:input message="tns:CustMasterTranTableCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
