<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:tns="http://xmlns.oracle.com/EnterpriseService_Transactions/BillPaymentES/NotifyBill"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollingDB"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl xp20 xref mhdr oraext dvm socket"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/db/EnterpriseService.Transactions/BillPaymentES/PollingDB"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/PollingDB.wsdl"/>
        <oracle-xsl-mapper:rootElement name="CustMasterTranTableCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/PollingDB"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/NotifyBill.wsdl"/>
        <oracle-xsl-mapper:rootElement name="NotifyBillRequest"
                                       namespace="http://xmlns.oracle.com/EnterpriseService_Transactions/BillPaymentES/NotifyBill"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU APR 30 15:25:02 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:NotifyBillRequest>
      <xsl:for-each select="/ns0:CustMasterTranTableCollection/ns0:CustMasterTranTable">
        <xsl:if test=".">
          <tns:Payments>
            <xsl:if test="ns0:foracid">
              <tns:foracid>
                <xsl:if test="ns0:foracid/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:foracid/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:foracid"/>
              </tns:foracid>
            </xsl:if>
            <xsl:if test="ns0:tranDate">
              <tns:tranDate>
                <xsl:if test="ns0:tranDate/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:tranDate/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:tranDate"/>
              </tns:tranDate>
            </xsl:if>
            <xsl:if test="ns0:refNum">
              <tns:tranId>
                <xsl:if test="ns0:refNum/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:refNum/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:refNum"/>
              </tns:tranId>
            </xsl:if>
            <xsl:if test="ns0:tranAmt">
              <tns:tranAmt>
                <xsl:if test="ns0:tranAmt/@xsi:nil">
                  <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                    <xsl:value-of select="ns0:tranAmt/@xsi:nil"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="ns0:tranAmt"/>
              </tns:tranAmt>
            </xsl:if>
            <tns:id>
              <xsl:if test="ns0:id/@xsi:nil">
                <xsl:attribute name="nil" namespace="http://www.w3.org/2001/XMLSchema-instance">
                  <xsl:value-of select="ns0:id/@xsi:nil"/>
                </xsl:attribute>
              </xsl:if>
              <xsl:value-of select="ns0:id"/>
            </tns:id>
          </tns:Payments>
        </xsl:if>
      </xsl:for-each>
    </tns:NotifyBillRequest>
  </xsl:template>
</xsl:stylesheet>
