<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:v1="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/CurrencyExchange/V1"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:v13="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/CurrencyExchange/V1"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd v13 v1 oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:v12="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:v11="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <xsl:import href="../../../../ESBMetadata/XSL/DateTime_Functions.xsl"/>
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/CurrencyExchange/V1/CurrencyExchangeEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/CurrencyExchange/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/CurrencyExchange/V1/CurrencyExchangeRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/CurrencyExchange/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 26 19:31:34 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <v1:ESBMsg>
      <v11:MsgID>
        <xsl:value-of select="/v13:ESBMsg/v12:MsgID"/>
      </v11:MsgID>
      <v1:RsData>
        <v12:BankID>
          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v12:BankID"/>
        </v12:BankID>
        <v1:CurrencyExchange>
          <v12:CustomerID>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v12:CustomerID"/>
          </v12:CustomerID>
          <v1:CurrencyExchangeID>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v12:CurrencyExchangeIdentifier/v12:CurrencyExchangeID"/>
          </v1:CurrencyExchangeID>
          <v1:ConversionRate>
            <v11:Value>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v13:ConversionRate"/>
            </v11:Value>
          </v1:ConversionRate>
          <v1:DealDate>
            <xsl:call-template name="formatDate_From_DD-Mon-YY_To_YYYYMMDD">
              <xsl:with-param name="Date" select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v13:ConversionDateTime"/>
            </xsl:call-template>
          </v1:DealDate>
          <v1:DealCurrency>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v13:FromCurrencyCode"/>
          </v1:DealCurrency>
          <v1:DealCurrencyTo>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v13:ToCurrencyCode"/>
          </v1:DealCurrencyTo>
          <v1:DealBookingAmount>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:CurrencyExchange/v12:Amount"/>
          </v1:DealBookingAmount>
        </v1:CurrencyExchange>
        <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status">
          <v12:Status>
            <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Code">
              <v12:Code>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Code"/>
              </v12:Code>
            </xsl:if>
            <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Type">
              <v12:Type>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Type"/>
              </v12:Type>
            </xsl:if>
            <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text">
              <v12:Text>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text"/>
              </v12:Text>
            </xsl:if>
          </v12:Status>
        </xsl:if>
      </v1:RsData>
    </v1:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
