<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"
                xmlns:rs="urn:control.services.tiplus2.misys.com"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:id="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:msg="urn:messages.service.ti.apps.tiplus2.misys.com"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/CurrencyExchange/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/CurrencyExchange/V1/CurrencyExchangeEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/CurrencyExchange/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Misys/AppMetadata/V1/Control.xsd"/>
        <oracle-xsl-mapper:rootElement name="ServiceRequest" namespace="urn:control.services.tiplus2.misys.com"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 22 04:08:29 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <rs:ServiceRequest>
      <RequestHeader>
        <Service>TI</Service>
        <Operation>FXRate</Operation>
        <ReplyFormat>FULL</ReplyFormat>
        <NoRepair>Y</NoRepair>
        <NoOverride>Y</NoOverride>
        <TransactionControl>NONE</TransactionControl>
        <CorrelationId>9402</CorrelationId>
      </RequestHeader>
      <msg:FXRate>
        <msg:MaintType>A</msg:MaintType>
        <msg:MaintainedInBackOffice>Y</msg:MaintainedInBackOffice>
        <msg:FxRateCode>CORP</msg:FxRateCode>
        <msg:BankingEntity>EQBL KE</msg:BankingEntity>
        <msg:Currency>
          <xsl:value-of select="/eo:CurrencyExchange/eo:FixedCurrencyUnit"/>
        </msg:Currency>
        <msg:BuyExchangeRate>
          <xsl:value-of select="/eo:CurrencyExchange/eo:BidRate"/>
        </msg:BuyExchangeRate>
        <msg:SellExchangeRate>
          <xsl:value-of select="/eo:CurrencyExchange/eo:OfferRate"/>
        </msg:SellExchangeRate>
        <msg:BuyRateSpecific>T</msg:BuyRateSpecific>
        <msg:SellRateSpecific>T</msg:SellRateSpecific>
        <msg:BaseCurrency>
          <xsl:value-of select="/eo:CurrencyExchange/eo:VarCurrencyUnit"/>
        </msg:BaseCurrency>
        <msg:Reciprocal>N</msg:Reciprocal>
      </msg:FXRate>
    </rs:ServiceRequest>
  </xsl:template>
</xsl:stylesheet>