<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:rs="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Statement/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:stmteo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Statement/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl rs stmteo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:rcom="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Statement/V1/StatementRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Statement/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Statement/V1/StatementEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Statement/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 23 22:02:36 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <stmteo:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/rs:ESBMsg/rcom:MsgID"/>
      </com:MsgID>
      <com:Source>COR</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>StatementES</com:Service>
      <xsl:choose>
        <xsl:when test="/rs:ESBMsg/rs:RqData/rs:Statement/rs:StatementType!= 'Card'">
          <stmteo:RqData actionCode="QueryRetailAccountStatementByID">
            <stmteo:Statement>
              <com:AccountIdentifier>
                <com:BankID>
                  <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Statement/com:BankID"/>
                </com:BankID>
                <com:BranchID>
                  <xsl:value-of select="substring(/rs:ESBMsg/rs:RqData/rs:Statement/com:AccountID,0,4)"/>
                </com:BranchID>
                <com:AccountID>
                  <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Statement/com:AccountID"/>
                </com:AccountID>
              </com:AccountIdentifier>
              <stmteo:FromDate>
                <xsl:value-of select="concat(substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:FromDate,1,4),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:FromDate,5,2),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:FromDate,7,2))"/>
              </stmteo:FromDate>
              <stmteo:ToDate>
                <xsl:value-of select="concat(substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:ToDate,1,4),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:ToDate,5,2),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:ToDate,7,2)) "/>
              </stmteo:ToDate>
            </stmteo:Statement>
          </stmteo:RqData>
        </xsl:when>
        <xsl:otherwise>
          <stmteo:RqData actionCode="QueryCardStatementByNumber">
            <stmteo:Statement>
              <com:CardIdentifier>
                <com:BankID>
                  <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Statement/com:CardIdentifier/com:BankID"/>
                </com:BankID>
                <com:CardNumber>
                  <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Statement/com:CardIdentifier/com:CardNumber"/>
                </com:CardNumber>
              </com:CardIdentifier>
              <stmteo:FromDate>
                <xsl:value-of select="concat(substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:FromDate,1,4),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:FromDate,5,2),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:FromDate,7,2))"/>
              </stmteo:FromDate>
              <stmteo:ToDate>
                <xsl:value-of select="concat(substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:ToDate,1,4),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:ToDate,5,2),'-',substring(/rs:ESBMsg/rs:RqData/rs:Statement/rs:ToDate,7,2)) "/>
              </stmteo:ToDate>
            </stmteo:Statement>
          </stmteo:RqData>
        </xsl:otherwise>
      </xsl:choose>
    </stmteo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
