<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ns0="http://xmlns.equitybank.co.ke/BM/Party/Employee/V1"
                xmlns:tns="http://xmlns.equitybank.co.ke/RM/MobileDevice/Employee/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:eo="http://xmlns.equitybank.co.ke/EO/Parties/Customer/V1"
                xmlns:empeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"
                xmlns:id="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Employee/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Parties/Employee/V1/EmployeeEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Employee/V1/EmployeeRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="EmployeeValidationResponseRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Employee/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAR 12 20:29:21 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ro:EmployeeValidationResponseRM>
      <ro:AgentDetails>
        <ro:CIFKey>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/empeo:Employee/bio:Biometric/com:BiometricIdentifier/com:BiometricID"/>
        </ro:CIFKey>
        <ro:BankCode>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/empeo:Employee/bio:Biometric/com:CustomerIdentifier/com:BankID"/>
        </ro:BankCode>
        <ro:BranchCode>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/empeo:Employee/bio:Biometric/com:CustomerIdentifier/com:BranchID"/>
        </ro:BranchCode>
      </ro:AgentDetails>
      <ro:CustomerInfo>
        <ro:FirstName>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:PersonName/com:FirstName"/>
        </ro:FirstName>
        <ro:MiddleName>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:PersonName/com:MiddleName"/>
        </ro:MiddleName>
        <ro:Surname>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:PersonName/com:LastName"/>
        </ro:Surname>
        <ro:Gender>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:GenderCode"/>
        </ro:Gender>
        <ro:Citizenship>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:Nationality"/>
        </ro:Citizenship>
        <ro:DateOfBirth>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:BirthDate"/>
        </ro:DateOfBirth>
        <ro:ApplicantSignature>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:SignatureImage"/>
        </ro:ApplicantSignature>
        <ro:ApplicantPhoto>
          <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:FaceImage"/>
        </ro:ApplicantPhoto>
      </ro:CustomerInfo>
      <ro:Status>
        <xsl:choose>
          <xsl:when test='/empeo:ESBMsg/empeo:RsData/com:Status/com:Code = "" and /empeo:ESBMsg/empeo:RsData/id:NationalIdentity/com:Person/com:PersonName/com:FirstName != ""'>
            <ro:Status>SUCCESS</ro:Status>
          </xsl:when>
          <xsl:otherwise>
            <ro:Status>
              <xsl:value-of select="/empeo:ESBMsg/empeo:RsData/com:Status/com:Code"/>
            </ro:Status>
          </xsl:otherwise>
        </xsl:choose>
      </ro:Status>
    </ro:EmployeeValidationResponseRM>
  </xsl:template>
</xsl:stylesheet>