<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:rs="urn:control.services.tiplus2.misys.com"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:acceo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:msg="urn:messages.service.ti.apps.tiplus2.misys.com"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Parties/Customer/V1/CustomerEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Misys/AppMetadata/V1/Control.xsd"/>
        <oracle-xsl-mapper:rootElement name="ServiceResponse" namespace="urn:control.services.tiplus2.misys.com"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUN 11 16:02:31 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <rs:ServiceResponse>
      <rs:ResponseHeader>
        <rs:Service>Customer</rs:Service>
        <rs:Operation>CustomerSearch</rs:Operation>
        <xsl:choose>
          <xsl:when test='/eo:ESBMsg/eo:RsData/com:Status/com:Type = "Success"'>
            <rs:Status>SUCCEEDED</rs:Status>
          </xsl:when>
          <xsl:when test='/eo:ESBMsg/eo:RsData/com:Status/com:Type = "Failure"'>
            <rs:Status>FAILED</rs:Status>
          </xsl:when>
          <xsl:otherwise>
            <rs:Status>UNAVAILABLE</rs:Status>
          </xsl:otherwise>
        </xsl:choose>
        <rs:Details>
          <xsl:choose>
            <xsl:when test='/eo:ESBMsg/eo:RsData/com:Status/com:Type = "Failure"'>
              <rs:Error>ESB-100</rs:Error>
            </xsl:when>
          </xsl:choose>
          <rs:Info>
            <xsl:value-of select="/eo:ESBMsg/eo:RsData/com:Status/com:Text"/>
          </rs:Info>
        </rs:Details>
        <rs:CorrelationId>1402</rs:CorrelationId>
      </rs:ResponseHeader>
      <msg:CustomerSearchResponse>
        <msg:CustomerSearchResults>
          <msg:CustomerSearchResult>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Customer/com:CustomerIdentifier/com:CustomerID">
              <msg:CustomerMnemonic>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Customer/com:CustomerIdentifier/com:CustomerID"/>
              </msg:CustomerMnemonic>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Customer/com:Person/com:PersonName/com:FullName">
              <msg:FullName>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Customer/com:Person/com:PersonName/com:FullName"/>
              </msg:FullName>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Customer/com:CustomerIdentifier/com:CustomerID">
              <msg:CustomerNumber>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Customer/com:CustomerIdentifier/com:CustomerID"/>
              </msg:CustomerNumber>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Customer/com:Address/com:CountryName">
              <msg:CountryOfResidence>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Customer/com:Address/com:CountryName"/>
              </msg:CountryOfResidence>
            </xsl:if>
          </msg:CustomerSearchResult>
        </msg:CustomerSearchResults>
      </msg:CustomerSearchResponse>
    </rs:ServiceResponse>
  </xsl:template>
</xsl:stylesheet>