<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Finacle/Adapter/db"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/db/FIN_DB_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="QueryLoanAccountMasterOutputCollection"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Finacle/Adapter/db"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN MAY 10 10:37:31 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <eo:RsData>
        <xsl:for-each select="/app:QueryLoanAccountMasterOutputCollection/app:QueryLoanAccountMasterOutput">
          <eo:Account>
            <com:AccountIdentifier>
              <com:BankID>
                <xsl:value-of select="app:UnitId"/>
              </com:BankID>
              <com:AccountID>
                <xsl:value-of select="app:LoanAccountNumber"/>
              </com:AccountID>
              <com:AccountCurrency>
                <xsl:value-of select="app:LoanCurrency"/>
              </com:AccountCurrency>
            </com:AccountIdentifier>
            <eo:AccountType>
              <xsl:value-of select="app:AccType"/>
            </eo:AccountType>
            <eo:AccountSubType>
              <xsl:value-of select="app:AccSubType"/>
            </eo:AccountSubType>
            <custeo:Customer>
              <com:Person>
                <com:PersonName>
                  <com:FullName>
                    <xsl:value-of select="app:LoanAccountName"/>
                  </com:FullName>
                </com:PersonName>
              </com:Person>
            </custeo:Customer>
            <eo:DelinquencyStatus>
              <xsl:value-of select="app:DelinquencyStatus"/>
            </eo:DelinquencyStatus>
            <com:Amount currencyCode=""/>
            <eo:MaturityDate>
              <xsl:value-of select="app:LoanMaturityDate"/>
            </eo:MaturityDate>
            <eo:InterestRate>
              <xsl:value-of select="app:InterestRate"/>
            </eo:InterestRate>
            <eo:InterestAccrued>
              <xsl:value-of select="app:InterestAccrued"/>
            </eo:InterestAccrued>
            <eo:SettlementCurrency>
              <xsl:value-of select="app:SettlementCurrency"/>
            </eo:SettlementCurrency>
            <eo:LoanType>
              <xsl:value-of select="app:LoanType"/>
            </eo:LoanType>
            <eo:FundingAccount>
              <xsl:value-of select="app:FundingAccount"/>
            </eo:FundingAccount>
            <eo:PaymentFrequency>
              <xsl:value-of select="app:PaymentFrequency"/>
            </eo:PaymentFrequency>
            <eo:Original_Amount>
              <xsl:value-of select="app:OriginalAmount"/>
            </eo:Original_Amount>
            <eo:OutStanding_Amount>
              <xsl:value-of select="app:OutStandingAmount"/>
            </eo:OutStanding_Amount>
            <eo:PastDueAmount>
              <xsl:value-of select="app:PastDueAmount"/>
            </eo:PastDueAmount>
            <eo:LastPaymentAmount>
              <xsl:value-of select="app:LastPaymentAmount"/>
            </eo:LastPaymentAmount>
            <eo:LastPaymentReceivedDate>
              <xsl:value-of select="app:LastPaymentReceivedDate"/>
            </eo:LastPaymentReceivedDate>
            <eo:TotalNumberofInstallments>
              <xsl:value-of select="app:TotalNumberofInstallments"/>
            </eo:TotalNumberofInstallments>
            <eo:InstallmentsPaid>
              <xsl:value-of select="app:InstallmentsPaid"/>
            </eo:InstallmentsPaid>
            <eo:NextPaymentDate>
              <xsl:value-of select="app:NextPaymentDate"/>
            </eo:NextPaymentDate>
            <eo:DisbursementAccount>
              <xsl:value-of select="app:DisbursementAccount"/>
            </eo:DisbursementAccount>
            <eo:InterestRepaymentAccount>
              <xsl:value-of select="app:InterestRepaymentAccount"/>
            </eo:InterestRepaymentAccount>
            <eo:Tenure>
              <xsl:value-of select="app:Tenure"/>
            </eo:Tenure>
            <eo:ApprovedLimit>
              <xsl:value-of select="app:ApprovedLimit"/>
            </eo:ApprovedLimit>
            <eo:NextPrincipalDueDate>
              <xsl:value-of select="app:NextPrincipalDueDate"/>
            </eo:NextPrincipalDueDate>
            <eo:NextInterestDueDate>
              <xsl:value-of select="app:NextInterestDueDate"/>
            </eo:NextInterestDueDate>
            <eo:NoofDelayed_Payments>
              <xsl:value-of select="app:NoofDelayedPayments"/>
            </eo:NoofDelayed_Payments>
            <eo:DisbursedAmount>
              <xsl:value-of select="app:DisbursedAmount"/>
            </eo:DisbursedAmount>
            <com:StartDate>
              <xsl:value-of select="app:LoanStartDate"/>
            </com:StartDate>
            <com:EndDate/>
            <com:TotalAmount>
              <xsl:value-of select="app:TotalLoanAmount"/>
            </com:TotalAmount>
            <eo:ClosureDate>
              <xsl:value-of select="app:LoanClosureDate"/>
            </eo:ClosureDate>
            <eo:AccountStatus>
              <xsl:value-of select="app:Loanstatus"/>
            </eo:AccountStatus>
          </eo:Account>
        </xsl:for-each>
        <xsl:if test="count (/app:QueryLoanAccountMasterOutputCollection/app:QueryLoanAccountMasterOutput ) > 0">
          <com:Status>
            <com:Code>ESB-00</com:Code>
            <com:Type>Success</com:Type>
            <com:Text>Loan account master details queried successfully</com:Text>
          </com:Status>
        </xsl:if>
        <xsl:if test="count (/app:QueryLoanAccountMasterOutputCollection/app:QueryLoanAccountMasterOutput ) &lt;= 0">
          <com:Status>
            <com:Code>ESB-100</com:Code>
            <com:Type>Failue</com:Type>
            <com:Text>Loan account master details not found</com:Text>
          </com:Status>
        </xsl:if>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
