<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:app="http://www.finacle.com/fixml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo app oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Finacle/AppMetadata/xsds/FIXML.xsd"/>
        <oracle-xsl-mapper:rootElement name="FIXML" namespace="http://www.finacle.com/fixml"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED JUN 10 17:10:37 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="date"/>
  <xsl:template match="/">
    <FIXML xmlns="http://www.finacle.com/fixml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
      <Header>
        <RequestHeader>
          <MessageKey>
            <RequestUUID>
              <xsl:value-of select="/eo:ESBMsg/com:MsgID"/>
            </RequestUUID>
            <ServiceRequestId>CAAcctAdd</ServiceRequestId>
            <ServiceRequestVersion>10.2</ServiceRequestVersion>
            <ChannelId>
              <xsl:value-of select="/eo:ESBMsg/com:Source"/>
            </ChannelId>
            <LanguageId/>
          </MessageKey>
          <RequestMessageInfo>
            <BankId>
              <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BankID"/>
            </BankId>
            <TimeZone/>
            <EntityId/>
            <EntityType/>
            <ArmCorrelationId/>
            <MessageDateTime>
              <xsl:value-of select="$date"/>
            </MessageDateTime>
          </RequestMessageInfo>
          <Security>
            <Token>
              <PasswordToken>
                <UserId/>
                <Password/>
              </PasswordToken>
            </Token>
            <FICertToken/>
            <RealUserLoginSessionId/>
            <RealUser/>
            <RealUserPwd/>
            <SSOTransferToken/>
          </Security>
        </RequestHeader>
      </Header>
      <Body>
        <CAAcctAddRequest>
          <CAAcctAddRq>
            <CustId>
              <CustId>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
              </CustId>
              <PersonName>
                <LastName>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:LastName"/>
                </LastName>
                <FirstName>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:FirstName"/>
                </FirstName>
                <MiddleName>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:MiddleName"/>
                </MiddleName>
                <Name>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:ShortName"/>
                </Name>
                <TitlePrefix>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:Title"/>
                </TitlePrefix>
              </PersonName>
            </CustId>
            <!--MultiCurAcctId>
              <AcctId>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:AccountID"/>
              </AcctId>
              <AcctType>
                <SchmCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:SchemeCode"/>
                </SchmCode>
                <SchmType>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountType"/>
                </SchmType>
              </AcctType>
              <AcctCurr>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:AccountCurrency"/>
              </AcctCurr>
              <BankInfo>
                <BankId>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BankID"/>
                </BankId>
                <Name>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:BankName"/>
                </Name>
                <BranchId>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BranchID"/>
                </BranchId>
                <BranchName>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:BranchName"/>
                </BranchName>
                <PostAddr>
                  <Addr1>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:LineOne"/>
                  </Addr1>
                  <Addr2>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:LineTwo"/>
                  </Addr2>
                  <Addr3>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:LineThree"/>
                  </Addr3>
                  <City>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:CityName"/>
                  </City>
                  <StateProv>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:StateName"/>
                  </StateProv>
                  <PostalCode>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:PostalCode"/>
                  </PostalCode>
                  <Country>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:CountryName"/>
                  </Country>
                  <AddrType>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:AddressType"/>
                  </AddrType>
                </PostAddr>
              </BankInfo>
            </MultiCurAcctId-->
            <CAAcctId>
              <AcctId>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:AccountID"/>
              </AcctId>
              <AcctType>
                <SchmCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountSubType"/>
                </SchmCode>
                <SchmType>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountType"/>
                </SchmType>
              </AcctType>
              <AcctCurr>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:AccountCurrency"/>
              </AcctCurr>
              <BankInfo>
                <BankId>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BankID"/>
                </BankId>
                <Name>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:BankName"/>
                </Name>
                <BranchId>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BranchID"/>
                </BranchId>
                <BranchName>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:BranchName"/>
                </BranchName>
                <PostAddr>
                  <Addr1>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:LineOne"/>
                  </Addr1>
                  <Addr2>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:LineTwo"/>
                  </Addr2>
                  <Addr3>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:LineThree"/>
                  </Addr3>
                  <City>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:CityName"/>
                  </City>
                  <StateProv>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:StateName"/>
                  </StateProv>
                  <PostalCode>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:PostalCode"/>
                  </PostalCode>
                  <Country>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:CountryName"/>
                  </Country>
                  <AddrType>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Address/com:AddressType"/>
                  </AddrType>
                </PostAddr>
              </BankInfo>
            </CAAcctId>
            <CAAcctGenInfo>
              <EotEnabled>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:EndOfTransactionBalanceMethod"/>
              </EotEnabled>
              <DrIntMethodInd>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:DebitInterestMethodIndicator"/>
              </DrIntMethodInd>
              <CorpRepresentativeSigFlg>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:CorporateRepresentativeSigFlag"/>
              </CorpRepresentativeSigFlg>
              <MinStmtFreqPeriod>
                <Days>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TenorDays"/>
                </Days>
                <Months>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TenorMonths"/>
                </Months>
              </MinStmtFreqPeriod>
              <DebitIntPrenotificationPeriod>
                <Days>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TenorDays"/>
                </Days>
                <Months>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TenorMonths"/>
                </Months>
              </DebitIntPrenotificationPeriod>
              <MinStmtRequiredFlg>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:MinimumStatementRequiredIndicator"/>
              </MinStmtRequiredFlg>
              <DebitIntPrenotificationInd>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:DebitIntPrenotificationIndicator"/>
              </DebitIntPrenotificationInd>
              <GenLedgerSubHead>
                <GenLedgerSubHeadCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:GeneralLedgerSubHeadCode"/>
                </GenLedgerSubHeadCode>
                <CurCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:GeneralLedgerSubHeadCurrency"/>
                </CurCode>
              </GenLedgerSubHead>
              <AcctName>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:FullName"/>
              </AcctName>
              <AcctShortName>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:ShortName"/>
              </AcctShortName>
              <AcctStmtMode>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountStmtCode"/>
              </AcctStmtMode>
              <AcctStmtFreq>
                <Cal>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:StatementFrequency/eo:CalenderType"/>
                </Cal>
                <Type>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:StatementFrequency/eo:StmtDuration"/>
                </Type>
                <StartDt>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:StatementFrequency/eo:StartDay"/>
                </StartDt>
                <WeekDay>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:StatementFrequency/eo:WeekDay"/>
                </WeekDay>
                <WeekNum>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:StatementFrequency/eo:WeekNum"/>
                </WeekNum>
                <HolStat>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:StatementFrequency/eo:HolidaytStatus"/>
                </HolStat>
              </AcctStmtFreq>
              <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountStatementNextPrintDate">
                <AcctStmtNxtPrintDt>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountStatementNextPrintDate"/>
                </AcctStmtNxtPrintDt>
              </xsl:if>
              <DespatchMode>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:AccountDespatchCode"/>
              </DespatchMode>
            </CAAcctGenInfo>
            <!--NomineeInfoRec>
              <RegNum>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:NomineeRegistrationNumber"/>
              </RegNum>
              <NomineeName>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:NomineeName"/>
              </NomineeName>
              <RelType>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:RelationType"/>
              </RelType>
              <NomineeContactInfo>
                <PhoneNum>
                  <TelephoneNum>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Phone/com:LocalNumber"/>
                  </TelephoneNum>
                  <FaxNum>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:FaxNumber"/>
                  </FaxNum>
                  <TelexNum>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TelexNumber"/>
                  </TelexNum>
                </PhoneNum>
                <EmailAddr>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Email/com:EmailAddress"/>
                </EmailAddr>
              </NomineeContactInfo>
              <NomineeMinorFlg>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:NomineeMinorIndicator"/>
              </NomineeMinorFlg>
              <NomineeBirthDt>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:NomineeBirthDate"/>
              </NomineeBirthDt>
              <NomineePercent>
                <value>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:NomineePercentValue"/>
                </value>
              </NomineePercent>
              <GuardianInfo>
                <GuardianCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:GuardianCode"/>
                </GuardianCode>
                <GuardianName>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:GuardianName"/>
                </GuardianName>
                <GuardianContactInfo>
                  <EmailAddr>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Email/com:EmailAddress"/>
                  </EmailAddr>
                  <PhoneNum>
                    <FaxNum>
                      <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:FaxNumber"/>
                    </FaxNum>
                    <TelephoneNum>
                      <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Phone/com:LocalNumber"/>
                    </TelephoneNum>
                    <TelexNum>
                      <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TelexNumber"/>
                    </TelexNum>
                  </PhoneNum>
                </GuardianContactInfo>
              </GuardianInfo>
              <RecDelFlg>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:RecordDeleteIndicator"/>
              </RecDelFlg>
            </NomineeInfoRec>
            <RelPartyRec>
              <RelPartyType>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:RelatedPartyType"/>
              </RelPartyType>
              <RelPartyTypeDesc>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:RelatedPartyTypeDesc"/>
              </RelPartyTypeDesc>
              <RelPartyCode>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:RelatedPartyCode"/>
              </RelPartyCode>
              <RelPartyCodeDesc>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:RelatedPartyCodeDesc"/>
              </RelPartyCodeDesc>
              <RelPartyContactInfo>
                <EmailAddr>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Email/com:EmailAddress"/>
                </EmailAddr>
                <PhoneNum>
                  <FaxNum>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:FaxNumber"/>
                  </FaxNum>
                  <TelephoneNum>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/custeo:Customer/com:Phone/com:LocalNumber"/>
                  </TelephoneNum>
                  <TelexNum>
                    <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/com:TelexNumber"/>
                  </TelexNum>
                </PhoneNum>
              </RelPartyContactInfo>
              <RecDelFlg></RecDelFlg>
            </RelPartyRec-->
            <!--basel>
              <security_indicator>
                <value>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:SecurityPercentage"/>
                </value>
              </security_indicator>
              <debt_seniority>
                <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:DebtSeniority"/>
              </debt_seniority>
              <security_code>
                <code>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:SecurityCode"/>
                </code>
                <codeDesc>
                  <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Account/eo:SecurityCodeDescription"/>
                </codeDesc>
              </security_code>
            </basel-->
          </CAAcctAddRq>
          <CAAcctAdd_CustomData>
            <INTCRACCTFLG>S</INTCRACCTFLG>
            <INTDRACCTFLG>S</INTDRACCTFLG>
            <NRE>N</NRE>
            <ALLOWSWEEPS>N</ALLOWSWEEPS>
            <BORROWERCAT>SOLE</BORROWERCAT>
            <ADVPURPOSE>BEXPA</ADVPURPOSE>
            <SOLID><xsl:value-of select="concat(substring('00',string-length(/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BranchID/text())),/eo:ESBMsg/eo:RqData/eo:Account/com:AccountIdentifier/com:BranchID/text())"/></SOLID>
            <ACCT_MGR/>
            <CRCOMPRESTIND>M</CRCOMPRESTIND>
            <MODE_OF_OPER_CODE>SELF</MODE_OF_OPER_CODE>
          </CAAcctAdd_CustomData>
        </CAAcctAddRequest>
      </Body>
    </FIXML>
  </xsl:template>
</xsl:stylesheet>