<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:app="http://www.finacle.com/fixml" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl app eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Finacle/AppMetadata/xsds/FIXML.xsd"/>
        <oracle-xsl-mapper:rootElement name="ForEachFiXml" namespace="http://www.finacle.com/fixml"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 23 10:03:22 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/app:FIXML/app:Header/app:ResponseHeader/app:RequestMessageKey/app:RequestUUID"/>
      </com:MsgID>
      <eo:RsData>
        <xsl:for-each select="/app:ForEachFiXml/app:FIXML">
          <eo:Account>
            <com:AccountIdentifier>
              <com:BankID>
                <xsl:value-of select="app:Header/app:ResponseHeader/app:ResponseMessageInfo/app:BankId"/>
              </com:BankID>
              <com:BranchID>
                <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:BranchCode"/>
              </com:BranchID>
              <com:AccountID>
                <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountID"/>
              </com:AccountID>
              <com:AccountCurrency>
                <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:Currency"/>
              </com:AccountCurrency>
            </com:AccountIdentifier>
            <eo:AccountType>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:SchemeType"/>
            </eo:AccountType>
            <eo:AccountSubType>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:SchemeCode"/>
            </eo:AccountSubType>
            <eo:AccountOpenDate>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AcctOpenDate"/>
            </eo:AccountOpenDate>
            <eo:AccountOwnership>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountOwnership"/>
            </eo:AccountOwnership>
            <eo:ModeOfOperation>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:ModeOfOperation"/>
            </eo:ModeOfOperation>
            <custeo:Customer>
              <com:CustomerIdentifier>
                <com:CustomerID>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:CustomerID"/>
                </com:CustomerID>
              </com:CustomerIdentifier>
              <custeo:CustomerType>
                <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:RetCorpFlg"/>
              </custeo:CustomerType>
              <com:Person>
                <com:PersonName>
                  <com:FullName>
                    <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountName"/>
                  </com:FullName>
                  <com:FirstName>
                    <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:CustomerFirstName"/>
                  </com:FirstName>
                  <com:LastName>
                    <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:CustomerLastName"/>
                  </com:LastName>
                  <com:ShortName>
                    <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:CustomerShortName"/>
                  </com:ShortName>
                  <com:Title>
                    <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:CustomerTitleCode"/>
                  </com:Title>
                </com:PersonName>
                <com:BirthDate>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:DateOfBirth"/>
                </com:BirthDate>
              </com:Person>
              <com:Address>
                <com:LineOne>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:PrefAddress/app:Address1"/>
                </com:LineOne>
                <com:LineTwo>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:PrefAddress/app:Address2"/>
                </com:LineTwo>
                <com:PostalCode>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:PrefAddress/app:PinCode"/>
                </com:PostalCode>
              </com:Address>
              <com:Phone>
                <com:CountryCode>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:PrefAddress/app:CountryCode"/>
                </com:CountryCode>
              </com:Phone>
              <com:Phone>
                <com:PhoneType>PHONE</com:PhoneType>
                <com:CompleteNumber>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:PhoneNo"/>
                </com:CompleteNumber>
                <com:LocalNumber>
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:PhoneNo"/>
                </com:LocalNumber>
              </com:Phone>
              <com:Email>
                <xsl:if test="string-length (app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:EmailID/text()) >0">
                  <com:EmailAddress>
                    <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:EmailID"/>
                  </com:EmailAddress>
                </xsl:if>
              </com:Email>
            </custeo:Customer>
            <com:Balance>
              <xsl:if test="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:ClearBalance">
                <com:BalanceAmount currencyCode="{app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:Currency}">
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:ClearBalance"/>
                </com:BalanceAmount>
                <com:BalanceType>CLRBAL</com:BalanceType>
              </xsl:if>
            </com:Balance>
            <com:Balance>
              <xsl:if test="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:UnclearBalance">
                <com:BalanceAmount currencyCode="{app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:Currency}">
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:UnclearBalance"/>
                </com:BalanceAmount>
                <com:BalanceType>UNCLRBAL</com:BalanceType>
              </xsl:if>
            </com:Balance>
            <com:Balance>
              <xsl:if test="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:SanctionLimit">
                <com:BalanceAmount currencyCode="{app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:Currency}">
                  <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:SanctionLimit"/>
                </com:BalanceAmount>
                <com:BalanceType>SANLIM</com:BalanceType>
              </xsl:if>
            </com:Balance>
            <eo:AccountClosureFlag>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountClosureFlag"/>
            </eo:AccountClosureFlag>
            <eo:AccountStatus>
              <xsl:value-of select="app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountStatus"/>
            </eo:AccountStatus>
          </eo:Account>
          <xsl:choose>
            <xsl:when test="app:Body/app:Error">
              <com:Status>
                <com:Code>ESB-100</com:Code>
                <com:Type>
                  <xsl:value-of select="app:Header/app:ResponseHeader/app:HostTransaction/app:Status"/>
                </com:Type>
                <xsl:choose>
                  <xsl:when test="count (app:Body/app:Error/app:FIBusinessException ) > 0">
                    <com:Text>
                      <xsl:value-of select="concat ('ErrorCode ', app:Body/app:Error/app:FIBusinessException/app:ErrorDetail/app:ErrorCode, ',  ErrorDesc ', app:Body/app:Error/app:FIBusinessException/app:ErrorDetail/app:ErrorDesc )"/>
                    </com:Text>
                  </xsl:when>
                  <xsl:otherwise>
                    <com:Text>
                      <xsl:value-of select="concat ('ErrorCode ', app:Body/app:Error/app:FISystemException/app:ErrorDetail/app:ErrorCode, ',  ErrorDesc ', app:Body/app:Error/app:FISystemException/app:ErrorDetail/app:ErrorDesc )"/>
                    </com:Text>
                  </xsl:otherwise>
                </xsl:choose>
              </com:Status>
            </xsl:when>
            <xsl:otherwise>
              <com:Status>
                <com:Code>ESB-00</com:Code>
                <com:Type>
                  <xsl:value-of select="app:Header/app:ResponseHeader/app:HostTransaction/app:Status"/>
                </com:Type>
                <com:Text>Success</com:Text>
              </com:Status>
            </xsl:otherwise>
          </xsl:choose>
        </xsl:for-each>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
