<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:app="http://www.finacle.com/fixml" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Finacle/AppMetadata/xsds/FIXML.xsd"/>
        <oracle-xsl-mapper:rootElement name="FIXML" namespace="http://www.finacle.com/fixml"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="Account"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 30 10:39:54 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:Account>
      <com:AccountIdentifier>
        <com:BankID>
          <xsl:value-of select="/app:FIXML/app:Header/app:ResponseHeader/app:ResponseMessageInfo/app:BankId"/>
        </com:BankID>
        <com:BranchID>
          <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:BranchCode"/>
        </com:BranchID>
        <com:AccountID>
          <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountID"/>
        </com:AccountID>
        <com:AccountCurrency>
          <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:Currency"/>
        </com:AccountCurrency>
      </com:AccountIdentifier>
      <eo:AccountType>
        <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:SchemeType"/>
      </eo:AccountType>
      <eo:AccountSubType>
        <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:SchemeCode"/>
      </eo:AccountSubType>
      <eo:AccountOwnership>
        <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountOwnership"/>
      </eo:AccountOwnership>
      <custeo:Customer>
        <com:CustomerIdentifier>
          <com:CustomerID>
            <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:CustomerID"/>
          </com:CustomerID>
        </com:CustomerIdentifier>
        <com:Person>
          <com:PersonName>
            <com:FullName>
              <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountName"/>
            </com:FullName>
          </com:PersonName>
        </com:Person>
      </custeo:Customer>
      <eo:AccountStatus>
        <xsl:value-of select="/app:FIXML/app:Body/app:executeFinacleScriptResponse/app:executeFinacleScript_CustomData/app:CustAcctInquiry_RES/app:AcctDtls/app:AccountStatus"/>
      </eo:AccountStatus>
    </eo:Account>
  </xsl:template>
</xsl:stylesheet>
