<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:app="http://www.finacle.com/fixml" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl app eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Finacle/AppMetadata/xsds/FIXML.xsd"/>
        <oracle-xsl-mapper:rootElement name="FIXML" namespace="http://www.finacle.com/fixml"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 14 05:06:31 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <eo:RsData>
        <eo:Account>
          <com:AccountIdentifier>
            <com:BankID>
              <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:BankID"/>
            </com:BankID>
            <com:BranchID>
              <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:BranchID"/>
            </com:BranchID>
            <com:AccountID>
              <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:AcctId"/>
            </com:AccountID>
            <com:AccountCurrency>
              <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/AcctCurr"/>
            </com:AccountCurrency>
          </com:AccountIdentifier>
          <eo:AccountType>
            <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:AcctType/app:SchmType"/>
          </eo:AccountType>
          <custeo:Customer>
            <com:Address>
              <com:AddressType>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:AddrType"/>
              </com:AddressType>
              <com:LineOne>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:Addr1"/>
              </com:LineOne>
              <com:LineTwo>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:Addr2"/>
              </com:LineTwo>
              <com:LineThree>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:Addr3"/>
              </com:LineThree>
              <com:CityName>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:City"/>
              </com:CityName>
              <com:StateName>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:StateProv"/>
              </com:StateName>
              <com:CountryName>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:Country"/>
              </com:CountryName>
              <com:PostalCode>
                <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:PostAddr/app:PostalCode"/>
              </com:PostalCode>
            </com:Address>
          </custeo:Customer>
          <eo:SchemeCode>
            <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:AcctType/app:SchmCode"/>
          </eo:SchemeCode>
          <com:BankName>
            <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo//app:Name"/>
          </com:BankName>
          <com:BranchName>
            <xsl:value-of select="/app:FIXML/app:Body/app:CAAcctAddResponse/app:CAAcctAddRs/app:CAAcctId/app:BankInfo/app:BranchName"/>
          </com:BranchName>
        </eo:Account>
        <xsl:choose>
          <xsl:when test="count (/app:FIXML/app:Body/app:Error ) &lt;= 0">
            <com:Status>
              <com:Code>ESB-00</com:Code>
              <com:Type>
                <xsl:value-of select="/app:FIXML/app:Header/app:ResponseHeader/app:HostTransaction/app:Status"/>
              </com:Type>
              <com:Text>Current account created successfully</com:Text>
            </com:Status>
          </xsl:when>
          <xsl:otherwise>
            <com:Status>
              <com:Code>ESB-100</com:Code>
              <com:Type>
                <xsl:value-of select="/app:FIXML/app:Header/app:ResponseHeader/app:HostTransaction/app:Status"/>
              </com:Type>
              <xsl:choose>
                <xsl:when test="count (/app:FIXML/app:Body/app:Error/app:FIBusinessException ) > 0">
                  <com:Text>
                    <xsl:value-of select="concat ('ErrorCode ', /app:FIXML/app:Body/app:Error/app:FIBusinessException/app:ErrorDetail/app:ErrorCode, ',  ErrorDesc ', /app:FIXML/app:Body/app:Error/app:FIBusinessException/app:ErrorDetail/app:ErrorDesc, ',    ErrorSource ', /app:FIXML/app:Body/app:Error/app:FISystemException/app:ErrorDetail/app:ErrorSource )"/>
                  </com:Text>
                </xsl:when>
                <xsl:otherwise>
                  <com:Text>
                    <xsl:value-of select="concat ('ErrorCode ', /app:FIXML/app:Body/app:Error/app:FISystemException/app:ErrorDetail/app:ErrorCode, ',  ErrorDesc ', /app:FIXML/app:Body/app:Error/app:FISystemException/app:ErrorDetail/app:ErrorDesc, ',    ErrorSource ', /app:FIXML/app:Body/app:Error/app:FISystemException/app:ErrorDetail/app:ErrorSource )"/>
                  </com:Text>
                </xsl:otherwise>
              </xsl:choose>
            </com:Status>
          </xsl:otherwise>
        </xsl:choose>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>