<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:trnseo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:cardeo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:ns3="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Card/V1/CardBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"/>
        <oracle-xsl-mapper:param name="cardPaymentDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Payment/V1/PaymentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 30 15:03:28 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgID"/>
      </com:MsgID>
      <com:Source>COR</com:Source>
      <com:MsgType>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgType"/>
      </com:MsgType>
      <com:Service>
        <xsl:value-of select="/ns0:ESBMsg/com:Service"/>
      </com:Service>
      <tns:RqData actionCode="CreateBillPayment">
        <tns:Payment>
          <com:PaymentIdentifier/>
          <com:BillIdentifier>
            <xsl:choose>
              <xsl:when test="starts-with(/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardNumber,'37999')">
                <com:BillerID>1379</com:BillerID>
                <com:BillID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardNumber"/>
                </com:BillID>
              </xsl:when>
              <xsl:otherwise>
                <com:BillerID>1194</com:BillerID>
                <com:BillID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardNumber"/>
                </com:BillID>
              </xsl:otherwise>
            </xsl:choose>
          </com:BillIdentifier>
          <com:BillAmount currencyCode="{/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount/@currencyCode}">
            <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount"/>
          </com:BillAmount>
          <com:TotalAmount currencyCode="{/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount/@currencyCode}">
            <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount"/>
          </com:TotalAmount>
          <com:ChargeAmount currencyCode="KES">00.00</com:ChargeAmount>
          <com:PersonName>
            <com:FullName>EQUITY BANK LIMITED</com:FullName>
          </com:PersonName>
          <com:Remarks>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Remarks"/>
          </com:Remarks>
          <com:PayFromAccount>
            <com:AccountIdentifier>
              <com:BankID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PaymentIdentifier/com:BankID"/>
              </com:BankID>
              <xsl:choose>
                <xsl:when test='starts-with (/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardNumber, "37999" )'>
                  <com:AccountID>0810263450692</com:AccountID>
                </xsl:when>
                <xsl:otherwise>
                  <com:AccountID>0810297000152</com:AccountID>
                </xsl:otherwise>
              </xsl:choose>
              <com:AccountCurrency>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency"/>
              </com:AccountCurrency>
            </com:AccountIdentifier>
          </com:PayFromAccount>
          <com:PayeeAccount>
            <com:AccountIdentifier>
            <com:AccountID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID"/>
              </com:AccountID>
            </com:AccountIdentifier>
            
          </com:PayeeAccount>
          <tns:FunctionCode>T</tns:FunctionCode>
          <tns:ValType>L</tns:ValType>
          <tns:PayReferenceCurrency>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount/@currencyCode"/>
          </tns:PayReferenceCurrency>
        </tns:Payment>
      </tns:RqData>
    </tns:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
