<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:trnseo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:cardeo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:ns3="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Card/V1/CardBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"/>
        <oracle-xsl-mapper:param name="cardPaymentDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Payment/V1/PaymentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUN 04 14:23:26 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgID"/>
      </com:MsgID>
      <com:Source>
        <xsl:value-of select="/ns0:ESBMsg/com:Source"/>
      </com:Source>
      <com:MsgType>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgType"/>
      </com:MsgType>
      <com:Service>
        <xsl:value-of select="/ns0:ESBMsg/com:Service"/>
      </com:Service>
      <xsl:if test="/ns0:ESBMsg/ns0:RqData">
        <tns:RqData actionCode="CreateCardPayment">
          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment">
            <tns:Payment>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PaymentIdentifier">
                <com:PaymentIdentifier>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PaymentIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PaymentIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PaymentIdentifier/com:PaymentID">
                    <com:PaymentID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PaymentIdentifier/com:PaymentID"/>
                    </com:PaymentID>
                  </xsl:if>
                </com:PaymentIdentifier>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:PaymentType">
                <tns:PaymentType>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:PaymentType"/>
                </tns:PaymentType>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier">
                <com:BillIdentifier>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BankBIC">
                    <com:BankBIC>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BankBIC"/>
                    </com:BankBIC>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BranchID">
                    <com:BranchID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BranchID"/>
                    </com:BranchID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:AccountID">
                    <com:AccountID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:AccountID"/>
                    </com:AccountID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:IBAN">
                    <com:IBAN>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:IBAN"/>
                    </com:IBAN>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:AccountCurrency">
                    <com:AccountCurrency>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:AccountCurrency"/>
                    </com:AccountCurrency>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BillerID">
                    <com:BillerID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BillerID"/>
                    </com:BillerID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BillID">
                    <com:BillID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillIdentifier/com:BillID"/>
                    </com:BillID>
                  </xsl:if>
                </com:BillIdentifier>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillAmount">
                <com:BillAmount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillAmount/@currencyCode">
                    <xsl:attribute name="currencyCode">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillAmount/@currencyCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:BillAmount"/>
                </com:BillAmount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier">
                <com:CardIdentifier>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:BankBIC">
                    <com:BankBIC>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:BankBIC"/>
                    </com:BankBIC>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:BranchID">
                    <com:BranchID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:BranchID"/>
                    </com:BranchID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:AccountID">
                    <com:AccountID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:AccountID"/>
                    </com:AccountID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:IBAN">
                    <com:IBAN>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:IBAN"/>
                    </com:IBAN>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:AccountCurrency">
                    <com:AccountCurrency>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:AccountCurrency"/>
                    </com:AccountCurrency>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardID">
                    <com:CardID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardID"/>
                    </com:CardID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardNumber">
                    <com:CardNumber>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:CardIdentifier/com:CardNumber"/>
                    </com:CardNumber>
                  </xsl:if>
                </com:CardIdentifier>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount">
                <com:Amount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount/@currencyCode">
                    <xsl:attribute name="currencyCode">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount/@currencyCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Amount"/>
                </com:Amount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:ValueDate">
                <com:ValueDate>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:ValueDate"/>
                </com:ValueDate>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:TotalAmount">
                <com:TotalAmount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:TotalAmount/@currencyCode">
                    <xsl:attribute name="currencyCode">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:TotalAmount/@currencyCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:TotalAmount"/>
                </com:TotalAmount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:ChargeAmount">
                <com:ChargeAmount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:ChargeAmount/@currencyCode">
                    <xsl:attribute name="currencyCode">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:ChargeAmount/@currencyCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:ChargeAmount"/>
                </com:ChargeAmount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName">
                <com:PersonName>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:FullName">
                    <com:FullName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:FullName"/>
                    </com:FullName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:FirstName">
                    <com:FirstName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:FirstName"/>
                    </com:FirstName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:MiddleName">
                    <com:MiddleName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:MiddleName"/>
                    </com:MiddleName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:LastName">
                    <com:LastName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:LastName"/>
                    </com:LastName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:ShortName">
                    <com:ShortName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:ShortName"/>
                    </com:ShortName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:Title">
                    <com:Title>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PersonName/com:Title"/>
                    </com:Title>
                  </xsl:if>
                </com:PersonName>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Remarks">
                <com:Remarks>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Remarks"/>
                </com:Remarks>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount">
                <com:PayFromAccount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:ShortName">
                            <com:ShortName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:ShortName"/>
                            </com:ShortName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </com:PayFromAccount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount">
                <com:PayeeAccount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:ShortName">
                            <com:ShortName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:ShortName"/>
                            </com:ShortName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </com:PayeeAccount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate">
                <com:Rate>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate/@unitCode">
                    <xsl:attribute name="unitCode">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate/@unitCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate/@baseValue">
                    <xsl:attribute name="baseValue">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate/@baseValue"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate/@baseUnitCode">
                    <xsl:attribute name="baseUnitCode">
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate/@baseUnitCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Rate"/>
                </com:Rate>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:TransactionRemarks">
                <tns:TransactionRemarks>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:TransactionRemarks"/>
                </tns:TransactionRemarks>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ChangeEventID">
                <tns:ChangeEventID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ChangeEventID"/>
                </tns:ChangeEventID>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:TransactionParticulars">
                <tns:TransactionParticulars>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:TransactionParticulars"/>
                </tns:TransactionParticulars>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:FunctionCode">
                <tns:FunctionCode>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:FunctionCode"/>
                </tns:FunctionCode>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ValType">
                <tns:ValType>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ValType"/>
                </tns:ValType>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ChargeEventID">
                <tns:ChargeEventID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ChargeEventID"/>
                </tns:ChargeEventID>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:PayReferenceCurrency">
                <tns:PayReferenceCurrency>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:PayReferenceCurrency"/>
                </tns:PayReferenceCurrency>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ParmCode">
                <tns:ParmCode>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:ParmCode"/>
                </tns:ParmCode>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction">
                <com:Transaction>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionID">
                    <com:TransactionID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionID"/>
                    </com:TransactionID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionType">
                    <com:TransactionType>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionType"/>
                    </com:TransactionType>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionCategory">
                    <com:TransactionCategory>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionCategory"/>
                    </com:TransactionCategory>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionSerialNumber">
                    <com:TransactionSerialNumber>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionSerialNumber"/>
                    </com:TransactionSerialNumber>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionReferenceNumber">
                    <com:TransactionReferenceNumber>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionReferenceNumber"/>
                    </com:TransactionReferenceNumber>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionDescription">
                    <com:TransactionDescription>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionDescription"/>
                    </com:TransactionDescription>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:InstrumentReferenceNumber">
                    <com:InstrumentReferenceNumber>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:InstrumentReferenceNumber"/>
                    </com:InstrumentReferenceNumber>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionAmount">
                    <com:TransactionAmount>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionAmount/@currencyCode">
                        <xsl:attribute name="currencyCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionAmount/@currencyCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionAmount"/>
                    </com:TransactionAmount>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:Remarks">
                    <com:Remarks>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:Remarks"/>
                    </com:Remarks>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:PostedDateTime">
                    <com:PostedDateTime>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:PostedDateTime"/>
                    </com:PostedDateTime>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionDateTime">
                    <com:TransactionDateTime>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:TransactionDateTime"/>
                    </com:TransactionDateTime>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:ValueDate">
                    <com:ValueDate>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/com:Transaction/com:ValueDate"/>
                    </com:ValueDate>
                  </xsl:if>
                </com:Transaction>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:PaymentStatus">
                <tns:PaymentStatus>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/tns:Payment/tns:PaymentStatus"/>
                </tns:PaymentStatus>
              </xsl:if>
            </tns:Payment>
          </xsl:if>
        </tns:RqData>
      </xsl:if>
    </tns:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
