<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:EncryptionFunctions="http://www.oracle.com/XSL/Transform/java/ke.co.equitybank.esb.functions.EncryptionFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                exclude-result-prefixes="xsd xsi com eo oracle-xsl-mapper xsl EncryptionFunctions oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Transfer/V1/TransferEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Way4/AppMetadata/xsds/EazzyCash.xsd"/>
        <oracle-xsl-mapper:rootElement name="request" namespace=""/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT MAY 02 13:06:37 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <request>
      <eazzycash>
        <amount>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Transfer/com:Amount"/>
        </amount>
        <sender>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Transfer/com:PayFromMobileWallet/com:MobileNumber"/>
        </sender>
        <name>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Transfer/com:PayFromMobileWallet/com:MobileUser"/>
        </name>
        <number>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Transfer/com:PayeeMobileWallet/com:MobileNumber"/>
        </number>
        <telco>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Transfer/com:MobileWalletVendor"/>
        </telco>
        <rrn>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Transfer/com:TransactionReferenceNumber"/>
        </rrn>
        <signature>
          <xsl:value-of select="EncryptionFunctions:encrypt(concat(/eo:ESBMsg/eo:RqData/eo:Transfer/com:Amount,/eo:ESBMsg/eo:RqData/eo:Transfer/com:PayFromMobileWallet/com:MobileNumber,/eo:ESBMsg/eo:RqData/eo:Transfer/com:PayFromMobileWallet/com:MobileUser,/eo:ESBMsg/eo:RqData/eo:Transfer/com:PayeeMobileWallet/com:MobileNumber,/eo:ESBMsg/eo:RqData/eo:Transfer/com:MobileWalletVendor,/eo:ESBMsg/eo:RqData/eo:Transfer/com:TransactionReferenceNumber), 'Keystore.jks', 'password', 'wambugu.com', 'wambugu')"/>
        </signature>
      </eazzycash>
    </request>
  </xsl:template>
</xsl:stylesheet>
