<xsl:stylesheet version="1.0" exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java" xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction" xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction" xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Charge/V1" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction" xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction" xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions" xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Charge/V1/ChargeEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Charge/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../ESBMetadata/ComponentLibrary/ProviderServices/ESBPortal/AppMetadata/xsds/Charges.xsd"/>
        <oracle-xsl-mapper:rootElement name="chargeMasterVO" namespace=""/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED JUL 01 12:05:18 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="index"/>
  <xsl:template match="/">
    <chargeMasterVO>
      <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Charge/com:ChargeIdentifier/com:ChargeID">
        <id>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Charge[number($index)]/com:ChargeIdentifier/com:ChargeID"/>
        </id>
      </xsl:if>
      <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Charge/com:ChargeAmount">
      <chargeAmount>
        <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Charge[number($index)]/com:ChargeAmount"/>
      </chargeAmount>
      </xsl:if>
      <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Charge/eo:ChargeType">
        <chargeType>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Charge[number($index)]/eo:ChargeType"/>
        </chargeType>
      </xsl:if>
      <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Charge/eo:ChargeFrequency">
        <frequency>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Charge[number($index)]/eo:ChargeFrequency"/>
        </frequency>
      </xsl:if>
      <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Charge/eo:UpdatedBy">
        <updateBy>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Charge[number($index)]/eo:UpdatedBy"/>
        </updateBy>
      </xsl:if>
    </chargeMasterVO>
  </xsl:template>
</xsl:stylesheet>