<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:v1="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Customer/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:v13="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:v14="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:v12="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:v11="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Parties/Customer/V1/CustomerEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Customer/V1/CustomerRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Customer/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU JUN 11 12:20:13 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <v1:ESBMsg>
      <v11:MsgID>
        <xsl:value-of select="/v13:ESBMsg/v12:MsgID"/>
      </v11:MsgID>
      <v1:RsData>
        <v1:Customer>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:BankID">
            <v12:BankID>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:BankID"/>
            </v12:BankID>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:CustomerID">
            <v12:CustomerID>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:CustomerID"/>
            </v12:CustomerID>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer">
            <v12:Person>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName">
                <v12:PersonName>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:FullName">
                    <v12:FullName>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:FullName"/>
                    </v12:FullName>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:FirstName">
                    <v12:FirstName>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:FirstName"/>
                    </v12:FirstName>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:MiddleName">
                    <v12:MiddleName>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:MiddleName"/>
                    </v12:MiddleName>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:LastName">
                    <v12:LastName>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:LastName"/>
                    </v12:LastName>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:ShortName">
                    <v12:ShortName>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:ShortName"/>
                    </v12:ShortName>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:Title">
                    <v12:Title>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:Title"/>
                    </v12:Title>
                  </xsl:if>
                </v12:PersonName>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment">
                <v12:Employment>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:CompanyID">
                    <v12:CompanyID>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:CompanyID"/>
                    </v12:CompanyID>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:CompanyName">
                    <v12:CompanyName>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:CompanyName"/>
                    </v12:CompanyName>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Income">
                    <v12:Income>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Income"/>
                    </v12:Income>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Occupation">
                    <v12:Occupation>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Occupation"/>
                    </v12:Occupation>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:EmploymentStatus">
                    <v12:EmploymentStatus>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:EmploymentStatus"/>
                    </v12:EmploymentStatus>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:TimeInEmploymentYY">
                    <v12:TimeInEmploymentYY>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:TimeInEmploymentYY"/>
                    </v12:TimeInEmploymentYY>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:TimeInEmploymentMM">
                    <v12:TimeInEmploymentMM>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:TimeInEmploymentMM"/>
                    </v12:TimeInEmploymentMM>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address">
                    <v12:Address>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:AddressType">
                        <v12:AddressType>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:AddressType"/>
                        </v12:AddressType>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineOne">
                        <v12:LineOne>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineOne"/>
                        </v12:LineOne>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineTwo">
                        <v12:LineTwo>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineTwo"/>
                        </v12:LineTwo>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineThree">
                        <v12:LineThree>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineThree"/>
                        </v12:LineThree>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineFour">
                        <v12:LineFour>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:LineFour"/>
                        </v12:LineFour>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:CityName">
                        <v12:CityName>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:CityName"/>
                        </v12:CityName>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:StateName">
                        <v12:StateName>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:StateName"/>
                        </v12:StateName>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:CountyName">
                        <v12:CountyName>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:CountyName"/>
                        </v12:CountyName>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:CountryName">
                        <v12:CountryName>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:CountryName"/>
                        </v12:CountryName>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:PostalCode">
                        <v12:PostalCode>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:PostalCode"/>
                        </v12:PostalCode>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:PreferredIndicator">
                        <v12:PreferredIndicator>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Address/v12:PreferredIndicator"/>
                        </v12:PreferredIndicator>
                      </xsl:if>
                    </v12:Address>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone">
                    <v12:Phone>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:PhoneType">
                        <v12:PhoneType>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:PhoneType"/>
                        </v12:PhoneType>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:CompleteNumber">
                        <v12:CompleteNumber>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:CompleteNumber"/>
                        </v12:CompleteNumber>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:CountryCode">
                        <v12:CountryCode>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:CountryCode"/>
                        </v12:CountryCode>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:AreaCode">
                        <v12:AreaCode>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:AreaCode"/>
                        </v12:AreaCode>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:LocalNumber">
                        <v12:LocalNumber>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:LocalNumber"/>
                        </v12:LocalNumber>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:ExtensionNumber">
                        <v12:ExtensionNumber>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:ExtensionNumber"/>
                        </v12:ExtensionNumber>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:PreferredIndicator">
                        <v12:PreferredIndicator>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Phone/v12:PreferredIndicator"/>
                        </v12:PreferredIndicator>
                      </xsl:if>
                    </v12:Phone>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email">
                    <v12:Email>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email/v12:EmailType">
                        <v12:EmailType>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email/v12:EmailType"/>
                        </v12:EmailType>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email/v12:EmailAddress">
                        <v12:EmailAddress>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email/v12:EmailAddress"/>
                        </v12:EmailAddress>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email/v12:PreferredIndicator">
                        <v12:PreferredIndicator>
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:Employment/v12:Email/v12:PreferredIndicator"/>
                        </v12:PreferredIndicator>
                      </xsl:if>
                    </v12:Email>
                  </xsl:if>
                </v12:Employment>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage">
                <v12:FaceImage>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage/@characterSetCode">
                    <xsl:attribute name="characterSetCode">
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage/@characterSetCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage/@fileName">
                    <xsl:attribute name="fileName">
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage/@fileName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage/@mimeCode">
                    <xsl:attribute name="mimeCode">
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FaceImage/@mimeCode"/>
                    </xsl:attribute>
                  </xsl:if>
                </v12:FaceImage>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints">
                <v12:FingerPrints>
                  <v12:ImageL1>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL1"/>
                  </v12:ImageL1>
                  <v12:ImageL2>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL2"/>
                  </v12:ImageL2>
                  <v12:ImageL3>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL3"/>
                  </v12:ImageL3>
                  <v12:ImageL4>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL4"/>
                  </v12:ImageL4>
                  <v12:ImageL5>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageL5"/>
                  </v12:ImageL5>
                  <v12:ImageR1>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR1"/>
                  </v12:ImageR1>
                  <v12:ImageR2>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR2"/>
                  </v12:ImageR2>
                  <v12:ImageR3>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR3"/>
                  </v12:ImageR3>
                  <v12:ImageR4>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR4"/>
                  </v12:ImageR4>
                  <v12:ImageR5>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:FingerPrints/v12:ImageR5"/>
                  </v12:ImageR5>
                </v12:FingerPrints>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument">
                <v12:IdentityDocument>
                  <v12:IdentityDocumentID>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentID"/>
                  </v12:IdentityDocumentID>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentSerialNumber">
                    <v12:IdentityDocumentSerialNumber>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentSerialNumber"/>
                    </v12:IdentityDocumentSerialNumber>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentType">
                    <v12:IdentityDocumentType>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentType"/>
                    </v12:IdentityDocumentType>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssueDate">
                    <v12:IssueDate>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssueDate"/>
                    </v12:IssueDate>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:ExpirationDate">
                    <v12:ExpirationDate>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:ExpirationDate"/>
                    </v12:ExpirationDate>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssuingCountry">
                    <v12:IssuingCountry>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssuingCountry"/>
                    </v12:IssuingCountry>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssuingLocation">
                    <v12:IssuingLocation>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssuingLocation"/>
                    </v12:IssuingLocation>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssuingAuthority">
                    <v12:IssuingAuthority>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IssuingAuthority"/>
                    </v12:IssuingAuthority>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1">
                    <v12:DocImage1>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage1"/>
                    </v12:DocImage1>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2">
                    <v12:DocImage2>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:DocImage2"/>
                    </v12:DocImage2>
                  </xsl:if>
                </v12:IdentityDocument>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage">
                <v12:SignatureImage>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage/@characterSetCode">
                    <xsl:attribute name="characterSetCode">
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage/@characterSetCode"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage/@fileName">
                    <xsl:attribute name="fileName">
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage/@fileName"/>
                    </xsl:attribute>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage/@mimeCode">
                    <xsl:attribute name="mimeCode">
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:SignatureImage/@mimeCode"/>
                    </xsl:attribute>
                  </xsl:if>
                </v12:SignatureImage>
              </xsl:if>
            </v12:Person>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentID">
            <v1:IdentityDocumentID>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:PrimaryIdentityDocument/v12:IdentityDocumentID"/>
            </v1:IdentityDocumentID>
          </xsl:if>
          <v11:HostSystem>FINN</v11:HostSystem>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:RelationshipManagerName">
            <v1:RelationshipManagerName>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:RelationshipManagerName"/>
            </v1:RelationshipManagerName>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:RelationshipManagerEmailID">
            <v1:RelationshipManagerEmailID>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:RelationshipManagerEmailID"/>
            </v1:RelationshipManagerEmailID>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address">
            <v12:Address>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:AddressType">
                <v12:AddressType>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:AddressType"/>
                </v12:AddressType>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineOne">
                <v12:LineOne>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineOne"/>
                </v12:LineOne>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineTwo">
                <v12:LineTwo>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineTwo"/>
                </v12:LineTwo>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineThree">
                <v12:LineThree>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineThree"/>
                </v12:LineThree>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineFour">
                <v12:LineFour>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:LineFour"/>
                </v12:LineFour>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:CityName">
                <v12:CityName>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:CityName"/>
                </v12:CityName>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:StateName">
                <v12:StateName>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:StateName"/>
                </v12:StateName>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:CountyName">
                <v12:CountyName>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:CountyName"/>
                </v12:CountyName>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:CountryName">
                <v12:CountryName>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:CountryName"/>
                </v12:CountryName>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:PostalCode">
                <v12:PostalCode>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:PostalCode"/>
                </v12:PostalCode>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:PreferredIndicator">
                <v12:PreferredIndicator>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Address/v12:PreferredIndicator"/>
                </v12:PreferredIndicator>
              </xsl:if>
            </v12:Address>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone">
            <v12:Phone>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:PhoneType">
                <v12:PhoneType>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:PhoneType"/>
                </v12:PhoneType>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:CompleteNumber">
                <v12:CompleteNumber>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:CompleteNumber"/>
                </v12:CompleteNumber>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:CountryCode">
                <v12:CountryCode>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:CountryCode"/>
                </v12:CountryCode>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:AreaCode">
                <v12:AreaCode>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:AreaCode"/>
                </v12:AreaCode>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:LocalNumber">
                <v12:LocalNumber>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:LocalNumber"/>
                </v12:LocalNumber>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:ExtensionNumber">
                <v12:ExtensionNumber>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:ExtensionNumber"/>
                </v12:ExtensionNumber>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:PreferredIndicator">
                <v12:PreferredIndicator>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Phone/v12:PreferredIndicator"/>
                </v12:PreferredIndicator>
              </xsl:if>
            </v12:Phone>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email">
            <v12:Email>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email/v12:EmailType">
                <v12:EmailType>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email/v12:EmailType"/>
                </v12:EmailType>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email/v12:EmailAddress">
                <v12:EmailAddress>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email/v12:EmailAddress"/>
                </v12:EmailAddress>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email/v12:PreferredIndicator">
                <v12:PreferredIndicator>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Email/v12:PreferredIndicator"/>
                </v12:PreferredIndicator>
              </xsl:if>
            </v12:Email>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:BranchID">
            <v12:BranchID>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:BranchID"/>
            </v12:BranchID>
          </xsl:if>
          <v11:PostingBranchID>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v13:PostingBranchID"/>
          </v11:PostingBranchID>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v13:CustomerType">
            <v1:CustomerType>
              <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v13:CustomerType"/>
            </v1:CustomerType>
          </xsl:if>
          <v11:CustomerTaxCode>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v13:CustomerTaxCode"/>
          </v11:CustomerTaxCode>
          <v13:CustomerTaxID>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v13:CustomerTaxID"/>
          </v13:CustomerTaxID>
          <v11:CustomerStatus>
            <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v13:CustomerStatus"/>
          </v11:CustomerStatus>
          <xsl:for-each select="/v13:ESBMsg/v13:RsData/v13:Customer/v14:Account">
            <v1:Account>
              <v12:BankID>
                <xsl:value-of select="v12:AccountIdentifier/v12:BankID"/>
              </v12:BankID>
              <v12:AccountID>
                <xsl:value-of select="v12:AccountIdentifier/v12:AccountID"/>
              </v12:AccountID>
              <v12:AccountCurrency>
                <xsl:value-of select="v12:AccountIdentifier/v12:AccountCurrency"/>
              </v12:AccountCurrency>
              <v12:BranchID>
                <xsl:value-of select="v12:AccountIdentifier/v12:BranchID"/>
              </v12:BranchID>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:FullName">
                <v1:AccountName>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:Person/v12:PersonName/v12:FullName"/>
                </v1:AccountName>
              </xsl:if>
              <xsl:if test="v14:AccountOpenDate">
                <v14:AccountOpenDate>
                  <xsl:value-of select="v14:AccountOpenDate"/>
                </v14:AccountOpenDate>
              </xsl:if>
              <v12:CustomerID>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Customer/v12:CustomerIdentifier/v12:CustomerID"/>
              </v12:CustomerID>
              <xsl:if test="v14:AccountType">
                <v14:AccountType>
                  <xsl:value-of select="v14:AccountType"/>
                </v14:AccountType>
              </xsl:if>
              <xsl:if test="v14:AccountSubType">
                <v14:AccountSubType>
                  <xsl:value-of select="v14:AccountSubType"/>
                </v14:AccountSubType>
              </xsl:if>
              <xsl:if test="v14:AccountOwnership">
                <v14:AccountOwnership>
                  <xsl:value-of select="v14:AccountOwnership"/>
                </v14:AccountOwnership>
              </xsl:if>
              <v12:IBAN>
                <xsl:value-of select="v12:AccountIdentifier/v12:IBAN"/>
              </v12:IBAN>
              <xsl:if test="v14:AccountClosureFlag">
                <v11:ClosureFlag>
                  <xsl:value-of select="v14:AccountClosureFlag"/>
                </v11:ClosureFlag>
              </xsl:if>
              <xsl:if test="v14:ClosureDate">
                <v11:ClosureDate>
                  <xsl:value-of select="v14:ClosureDate"/>
                </v11:ClosureDate>
              </xsl:if>
              <v11:NoCreditStatus>N</v11:NoCreditStatus>
              <v11:NoDebitStatus>N</v11:NoDebitStatus>
              <v11:DelinquencyStatus>N</v11:DelinquencyStatus>
              <xsl:if test="v14:AccountStatus">
                <v14:AccountStatus>
                  <xsl:value-of select="v14:AccountStatus"/>
                </v14:AccountStatus>
              </xsl:if>
            </v1:Account>
          </xsl:for-each>
        </v1:Customer>
        <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status">
          <v12:Status>
            <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Code">
              <v12:Code>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Code"/>
              </v12:Code>
            </xsl:if>
            <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Type">
              <v12:Type>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Type"/>
              </v12:Type>
            </xsl:if>
            <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text">
              <v12:Text>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text"/>
              </v12:Text>
            </xsl:if>
          </v12:Status>
        </xsl:if>
      </v1:RsData>
    </v1:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
