<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Document/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/RO/ContentManager/Document/V1"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:ns3="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Document/V1/DocumentRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="QueryDocumentRequestRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/ContentManager/Document/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Misc/Document/V1/DocumentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Document/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 19 12:25:02 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ESBMsg>
      <com:Source>MDE</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>DocumentES</com:Service>
      <xsl:choose>
        <xsl:when test='/ns0:QueryDocumentRequestRM/ns0:RefID != "" and /ns0:QueryDocumentRequestRM/ns0:Count = "N"'>
          <tns:RqData actionCode="QueryDocumentByID">
            <tns:Document>
              <com:DocumentIdentifier>
                <com:DocumentID>
                  <xsl:value-of select="/ns0:QueryDocumentRequestRM/ns0:RefID"/>
                </com:DocumentID>
              </com:DocumentIdentifier>
              <tns:DocumentStatus>
                <xsl:value-of select="/ns0:QueryDocumentRequestRM/ns0:Count"/>
              </tns:DocumentStatus>
            </tns:Document>
          </tns:RqData>
        </xsl:when>
        <xsl:when test='/ns0:QueryDocumentRequestRM/ns0:RefID != "" and /ns0:QueryDocumentRequestRM/ns0:Count = "Y"'>
          <tns:RqData actionCode="QueryCountPendingDocumentById">
            <tns:Document>
              <com:DocumentIdentifier>
                <com:DocumentID>
                  <xsl:value-of select="/ns0:QueryDocumentRequestRM/ns0:RefID"/>
                </com:DocumentID>
              </com:DocumentIdentifier>
              <tns:DocumentStatus>
                <xsl:value-of select="/ns0:QueryDocumentRequestRM/ns0:Count"/>
              </tns:DocumentStatus>
            </tns:Document>
          </tns:RqData>
        </xsl:when>
        <xsl:when test='/ns0:QueryDocumentRequestRM/ns0:RefID = "N" and /ns0:QueryDocumentRequestRM/ns0:Count != ""'>
          <tns:RqData actionCode="QueryPendingDocumentByID">
            <tns:Document>
              <com:DocumentIdentifier>
                <com:DocumentID>
                  <xsl:value-of select="/ns0:QueryDocumentRequestRM/ns0:RefID"/>
                </com:DocumentID>
              </com:DocumentIdentifier>
              <tns:DocumentStatus>
                <xsl:value-of select="/ns0:QueryDocumentRequestRM/ns0:Count"/>
              </tns:DocumentStatus>
            </tns:Document>
          </tns:RqData>
        </xsl:when>
      </xsl:choose>
    </tns:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
