<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:v13="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:v1="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Account/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd v13 v1 oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:v12="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:v14="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Account/V1/AccountRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON JUN 15 09:57:31 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <v1:ESBMsg>
      <v14:MsgID>
        <xsl:value-of select="/v13:ESBMsg/v12:MsgID"/>
      </v14:MsgID>
      <v1:RsData>
        <xsl:for-each select="/v13:ESBMsg/v13:RsData/v13:Account">
          <v1:Balance>
            <v12:BankID>
              <xsl:value-of select="AccountIdentifier/v12:BankID"/>
            </v12:BankID>
            <v12:AccountIdentifier>
              <v12:AccountID>
                <xsl:value-of select="v12:AccountIdentifier/v12:AccountID"/>
              </v12:AccountID>
            </v12:AccountIdentifier>
            <v14:BalanceList>
              <xsl:if test="v12:Balance/v12:BalanceType='CLRBAL'">
                <v14:CurrentBalance>
                  <v14:Value>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount"/>
                  </v14:Value>
                  <v14:CurrencyCode>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount/@currencyCode"/>
                  </v14:CurrencyCode>
                </v14:CurrentBalance>
              </xsl:if>
              <xsl:if test="v12:Balance/v12:BalanceType='AVAIL'">
                <v14:AvailableBalance>
                  <v14:Value>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount"/>
                  </v14:Value>
                  <v14:CurrencyCode>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount/@currencyCode"/>
                  </v14:CurrencyCode>
                </v14:AvailableBalance>
              </xsl:if>
              <xsl:if test="v12:Balance/v12:BalanceType='SANLIM'">
                <v14:OverdraftLimit>
                  <v14:Value>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount"/>
                  </v14:Value>
                  <v14:CurrencyCode>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount/@currencyCode"/>
                  </v14:CurrencyCode>
                </v14:OverdraftLimit>
              </xsl:if>
              <xsl:if test="v12:Balance/v12:BalanceType='OVDFUT'">
                <v14:AvailableOverdraftLimit>
                  <v14:Value>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount"/>
                  </v14:Value>
                  <v14:CurrencyCode>
                    <xsl:value-of select="v12:Balance/v12:BalanceAmount/@currencyCode"/>
                  </v14:CurrencyCode>
                </v14:AvailableOverdraftLimit>
              </xsl:if>
            </v14:BalanceList>
          </v1:Balance>
        </xsl:for-each>
        <v12:Status>
          <xsl:choose>
            <xsl:when test="/v13:ESBMsg/v13:RsData/v12:Status[v12:Code='ESB-100']">
              <v12:Code>ESB-100</v12:Code>
            </xsl:when>
            <xsl:otherwise>
              <v12:Code>ESB-00</v12:Code>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/v13:ESBMsg/v13:RsData/v12:Status[v12:Code='ESB-100']">
              <v12:Type>Failure</v12:Type>
            </xsl:when>
            <xsl:otherwise>
              <v12:Type>Success</v12:Type>
            </xsl:otherwise>
          </xsl:choose>
          <xsl:choose>
            <xsl:when test="/v13:ESBMsg/v13:RsData/v12:Status[v12:Code='ESB-100']">
              <v12:Text>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status[v12:Code='ESB-100']/v12:Text"/>
              </v12:Text>
            </xsl:when>
            <xsl:otherwise>
              <v12:Text>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status[v12:Code='ESB-00']/v12:Text"/>
              </v12:Text>
            </xsl:otherwise>
          </xsl:choose>
        </v12:Status>
      </v1:RsData>
    </v1:ESBMsg>
  </xsl:template>
</xsl:stylesheet>