<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Way4/Adapter/db"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/db/WY4_DB_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="QueryCreditCardFeedOutputCollection"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Way4/Adapter/db"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Instruments/Card/V1/CardEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 14 11:00:31 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="CustID"/>
  <xsl:template match="/">
    <eo:ESBMsg>
      <eo:RsData>
        <xsl:for-each select="/app:QueryCreditCardFeedOutputCollection/app:QueryCreditCardFeedOutput">
          <eo:Card>
            <com:CardIdentifier>
              <com:BranchID>
                <xsl:value-of select="app:BranchCode"/>
              </com:BranchID>
              <com:AccountID>
                <xsl:value-of select="app:CardAccNo"/>
              </com:AccountID>
              <com:AccountCurrency>
                <xsl:value-of select="app:CardCcy"/>
              </com:AccountCurrency>
              <com:CardNumber>
                <xsl:value-of select="app:CardNo"/>
              </com:CardNumber>
            </com:CardIdentifier>
            <eo:CardType>
              <xsl:value-of select="app:CardType"/>
            </eo:CardType>
            <custeo:Customer>
              <com:CustomerIdentifier>
                <com:CustomerID>
                  <xsl:value-of select="$CustID"/>
                </com:CustomerID>
              </com:CustomerIdentifier>
              <com:Person>
                <com:PersonName>
                  <com:FullName>
                    <xsl:value-of select="app:CardHolderName"/>
                  </com:FullName>
                </com:PersonName>
              </com:Person>
              <com:Address>
                <com:CountryName/>
              </com:Address>
              <com:Phone>
                <com:CountryCode>
                  <xsl:value-of select="app:Country"/>
                </com:CountryCode>
              </com:Phone>
            </custeo:Customer>
            <eo:CardOpenDate>
              <xsl:value-of select="app:OpenDate"/>
            </eo:CardOpenDate>
            <eo:CardExpiryDate>
              <xsl:value-of select="app:ExpiryDate"/>
            </eo:CardExpiryDate>
            <eo:CardCategory>
              <xsl:value-of select="app:CardCategory"/>
            </eo:CardCategory>
            <eo:CardStatus>
              <xsl:value-of select="app:CardStatus"/>
            </eo:CardStatus>
          </eo:Card>
        </xsl:for-each>
        <xsl:if test="count (/app:QueryCreditCardFeedOutputCollection/app:QueryCreditCardFeedOutput ) > 0">
          <com:Status>
            <com:Code>ESB-00</com:Code>
            <com:Type>Success</com:Type>
            <com:Text>Credit card feed queried successfully</com:Text>
          </com:Status>
        </xsl:if>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
