<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Way4/Adapter/db"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl app eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/db/WY4_DB_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="ForEachOutputCollection"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Way4/Adapter/db"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Instruments/Card/V1/CardEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 26 15:31:31 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <eo:RsData>
        <xsl:for-each select="/app:ForEachOutputCollection/app:QueryCreditCardSummaryOutputCollection/app:QueryCreditCardSummaryOutput">
          <eo:Card>
            <com:CardIdentifier>
              <com:AccountCurrency>
                <xsl:value-of select="app:ContractCurrency"/>
              </com:AccountCurrency>
              <com:CardID>
                <xsl:value-of select="app:LoyaltyAccount"/>
              </com:CardID>
              <com:CardNumber>
                <xsl:value-of select="app:CardNumber"/>
              </com:CardNumber>
            </com:CardIdentifier>
            <eo:CardType>
              <xsl:value-of select="app:Product"/>
            </eo:CardType>
            <custeo:Customer>
              <com:Person>
                <com:PersonName>
                  <com:FullName>
                    <xsl:value-of select="app:CustomerName"/>
                  </com:FullName>
                </com:PersonName>
              </com:Person>
              <com:Phone>
                <com:PhoneType>Phone</com:PhoneType>
                <com:CompleteNumber>
                  <xsl:value-of select="app:PhoneNumber"/>
                </com:CompleteNumber>
              </com:Phone>
              <xsl:if test="string-length (app:EmailAddress/text()) >0">
                <com:Email>
                  <com:EmailAddress>
                    <xsl:value-of select="app:EmailAddress"/>
                  </com:EmailAddress>
                </com:Email>
              </xsl:if>
            </custeo:Customer>
            <eo:CardOpenDate>
              <xsl:value-of select="app:DateOpened"/>
            </eo:CardOpenDate>
            <eo:CardExpiryDate>
              <xsl:value-of select="app:ExpiryDate"/>
            </eo:CardExpiryDate>
            <eo:CardOwnership>
              <xsl:value-of select="app:IsMain"/>
            </eo:CardOwnership>
            <eo:AvailableCredit>
              <xsl:value-of select="app:AvailableCredit"/>
            </eo:AvailableCredit>
            <eo:CreditLimit>
              <xsl:value-of select="/app:ForEachOutputCollection/app:QueryCreditCardSummaryOutputCollection/app:QueryCreditCardSummaryOutput/app:AvailableCredit"/>
            </eo:CreditLimit>
            <eo:BlockedAmount>
              <xsl:value-of select="/app:ForEachOutputCollection/app:QueryCreditCardSummaryOutputCollection/app:QueryCreditCardSummaryOutput/app:BlockedAmount"/>
            </eo:BlockedAmount>
            <eo:UsedAmount>
              <xsl:value-of select="app:UsedAmount"/>
            </eo:UsedAmount>
            <eo:LastBillingDate>
              <xsl:value-of select="app:LastBillingDate"/>
            </eo:LastBillingDate>
            <eo:NextBillingDate>
              <xsl:value-of select="app:NextBillingDate"/>
            </eo:NextBillingDate>
            <eo:CardStatus>
              <xsl:value-of select="app:Status"/>
            </eo:CardStatus>
          </eo:Card>
         <xsl:choose>
          <xsl:when test="count (/app:ForEachOutputCollection/app:QueryCreditCardSummaryOutputCollection/app:QueryCreditCardSummaryOutput)">
            <com:Status>
              <com:Code>ESB-00</com:Code>
              <com:Type>Success</com:Type>
              <com:Text>Credit card summary queried successfully</com:Text>
            </com:Status>
          </xsl:when>
          <xsl:otherwise>
          <com:Status>
              <com:Code>ESB-100</com:Code>
              <com:Type>Failure</com:Type>
              <com:Text>NODATA</com:Text>
            </com:Status>
          </xsl:otherwise>
          </xsl:choose>
        </xsl:for-each>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
