<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Way4/Adapter/db"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl app eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:acceo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/db/WY4_DB_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="ForEachOutputCollection"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Way4/Adapter/db"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Instruments/Card/V1/CardEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 26 11:34:51 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="CustomerID"/>
  <xsl:template match="/">
    <eo:ESBMsg>
      <eo:RsData>
        <xsl:for-each select="/app:ForEachOutputCollection/app:QueryCreditCardDetailsOutputCollection/app:QueryCreditCardDetailsOutput">
          <eo:Card>
            <com:CardIdentifier>
              <com:CardID>
                <xsl:value-of select="app:CardID"/>
              </com:CardID>
              <com:CardNumber>
                <xsl:value-of select="app:CreditCardNo"/>
              </com:CardNumber>
            </com:CardIdentifier>
            <eo:CardType>
              <xsl:value-of select="app:CardType"/>
            </eo:CardType>
            <eo:CardSubType>
              <xsl:value-of select="app:Product"/>
            </eo:CardSubType>
            <custeo:Customer>
              <com:CustomerIdentifier>
                <com:CustomerID>
                  <xsl:value-of select="$CustomerID"/>
                </com:CustomerID>
              </com:CustomerIdentifier>
              <com:Person>
                <com:PersonName>
                  <com:FullName>
                    <xsl:value-of select="app:CardName"/>
                  </com:FullName>
                </com:PersonName>
              </com:Person>
              <acceo:Account>
                <com:AccountIdentifier>
                  <com:AccountID>
                    <xsl:value-of select="app:CardAccountNumber"/>
                  </com:AccountID>
                </com:AccountIdentifier>
                <custeo:Customer>
                  <com:Person>
                    <com:PersonName>
                      <com:FullName>
                        <xsl:value-of select="app:CardHolderName"/>
                      </com:FullName>
                    </com:PersonName>
                  </com:Person>
                </custeo:Customer>
                <com:Balance>
                  <com:BalanceAmount>
                    <xsl:value-of select="app:CurrentBalance"/>
                  </com:BalanceAmount>
                </com:Balance>
              </acceo:Account>
            </custeo:Customer>
            <eo:AvailableCredit>
              <xsl:value-of select="app:AvailableCreditLimit"/>
            </eo:AvailableCredit>
            <eo:CreditLimit>
              <xsl:value-of select="app:TotalCreditLimit"/>
            </eo:CreditLimit>
            <eo:LastBillingDate>
              <xsl:value-of select="app:LastBillingDate"/>
            </eo:LastBillingDate>
            <eo:RecoveryAccount>
              <xsl:value-of select="app:RecoveryAccount"/>
            </eo:RecoveryAccount>
            <eo:AvailableCash>
              <xsl:value-of select="app:AvailableCashLimit"/>
            </eo:AvailableCash>
            <eo:TotalPaymentDue>
              <xsl:value-of select="app:TotalPaymentDue"/>
            </eo:TotalPaymentDue>
            <eo:NextStatementDate>
              <xsl:value-of select="app:NextStatementDate"/>
            </eo:NextStatementDate>
            <eo:TotalAmountDue>
              <xsl:value-of select="app:TotalAmtDue"/>
            </eo:TotalAmountDue>
            <eo:LastPaymentDate>
              <xsl:value-of select="app:LastPaymentDate"/>
            </eo:LastPaymentDate>
            <eo:LastPaymentAmount>
              <xsl:value-of select="app:LastPaymentAmount"/>
            </eo:LastPaymentAmount>
            <eo:CardIssuer>
              <xsl:value-of select="app:CardIssuer"/>
            </eo:CardIssuer>
            <eo:MinPaymentDue>
              <xsl:value-of select="app:MinPaymentDue"/>
            </eo:MinPaymentDue>
            <eo:PaymentDueDate>
              <xsl:value-of select="app:PaymentDueDate"/>
            </eo:PaymentDueDate>
            <eo:PastDueAmount>
              <xsl:value-of select="app:PastDueAmount"/>
            </eo:PastDueAmount>
            <eo:CardReissueFlag>
              <xsl:value-of select="app:CardReissueFlag"/>
            </eo:CardReissueFlag>
            <eo:UnbilledAmount>
              <xsl:value-of select="app:UnbilledAmount"/>
            </eo:UnbilledAmount>
            <eo:CashLimit>
              <xsl:value-of select="app:CashLimit"/>
            </eo:CashLimit>
            <eo:AutoRecoveryOption>
              <xsl:value-of select="app:AutoRecoveryOption"/>
            </eo:AutoRecoveryOption>
            <eo:ContractCurrency>
              <xsl:value-of select="app:ContractCurrency"/>
            </eo:ContractCurrency>
            <eo:TotalDueAmount>
              <xsl:value-of select="app:TotalDueAmount"/>
            </eo:TotalDueAmount>
            <eo:LastStatementBalance>
              <xsl:value-of select="app:LastStatementBalance"/>
            </eo:LastStatementBalance>
            <eo:RecoveryBank>
              <xsl:value-of select="app:RecoveryBank"/>
            </eo:RecoveryBank>
            <eo:CardStatus>
              <xsl:value-of select="app:CardStatus"/>
            </eo:CardStatus>
          </eo:Card>
        </xsl:for-each>
        <xsl:if test="count (/app:ForEachOutputCollection/app:QueryCreditCardDetailsOutputCollection/app:QueryCreditCardDetailsOutput) > 0">
          <com:Status>
            <com:Code>ESB-00</com:Code>
            <com:Type>Success</com:Type>
            <com:Text>Credit card details queried successfully</com:Text>
          </com:Status>
        </xsl:if>
        <xsl:if test="count (/app:ForEachOutputCollection/app:QueryCreditCardDetailsOutputCollection/app:QueryCreditCardDetailsOutput) &lt;= 0">
          <com:Status>
            <com:Code>ESB-100</com:Code>
            <com:Type>Failue</com:Type>
            <com:Text>Credit card details no data found</com:Text>
          </com:Status>
        </xsl:if>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
