<?xml version="1.0" encoding="UTF-8"?>
<WL5G3N0:definitions
     name="BillPSC"
     targetNamespace="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"
     xmlns:WL5G3N0="http://schemas.xmlsoap.org/wsdl/"
     xmlns:WL5G3N1="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"
     xmlns:WL5G3N2="http://schemas.xmlsoap.org/wsdl/soap/"
    >
    <WL5G3N0:types>
        <xsd:schema xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:tns="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"
             xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"
                 schemaLocation="../Schemas/ChaiBillPSM.xsd"/>
        </xsd:schema>
    </WL5G3N0:types>
    <WL5G3N0:message name="QueryBillRequestMessage">
        <WL5G3N0:part name="QueryBillRequest" element="WL5G3N1:ChaiBillRequestPSM"/>
    </WL5G3N0:message>
    <WL5G3N0:message name="QueryBillResponseMessage">
        <WL5G3N0:part name="QueryBillResponse" element="WL5G3N1:ChaiBillResponsePSM"/>
    </WL5G3N0:message>
    <WL5G3N0:portType name="BillPSCPort">
        <WL5G3N0:operation name="query">
            <WL5G3N0:input message="WL5G3N1:QueryBillRequestMessage"/>
            <WL5G3N0:output message="WL5G3N1:QueryBillResponseMessage"/>
        </WL5G3N0:operation>
    </WL5G3N0:portType>
    <WL5G3N0:binding name="Bill_SOAPHttpBinding" type="WL5G3N1:BillPSCPort">
        <WL5G3N2:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <WL5G3N0:operation name="query">
            <WL5G3N2:operation style="document" soapAction="query"/>
            <WL5G3N0:input>
                <WL5G3N2:body use="literal" namespace="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"/>
            </WL5G3N0:input>
            <WL5G3N0:output>
                <WL5G3N2:body use="literal" namespace="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"/>
            </WL5G3N0:output>
        </WL5G3N0:operation>
    </WL5G3N0:binding>
    <WL5G3N0:service name="Bill_SOAPHttpBindingQSService">
        <WL5G3N0:documentation>OSB Service</WL5G3N0:documentation>
        <WL5G3N0:port name="Bill_SOAPHttpBindingQSPort" binding="WL5G3N1:Bill_SOAPHttpBinding">
            <WL5G3N2:address location="http://soa3host1vhn1uat.ebsafrica.com:8011/ESB/PS/EqpgwProv/ProxyServices/EqpgwPS"/>
        </WL5G3N0:port>
    </WL5G3N0:service>
</WL5G3N0:definitions>
