<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo app oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Instruments/Card/V1/CardEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/ftp/PRS_FTP_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="CreditCardFileInput"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 14 15:33:03 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <app:CreditCardFileInput>
      <app:HeaderLine>
        <app:LineIdentifier>H</app:LineIdentifier>
        <app:FileName>
          <xsl:value-of select="concat(/eo:ESBMsg/eo:RqData/@actionCode,'_Feed_','2015-05-14')"/>
        </app:FileName>
        <app:Date>2015-05-12</app:Date>
        <!--app:FileName>
          <xsl:value-of select="concat(/eo:ESBMsg/eo:RqData/@actionCode,'_Feed_',xp20:format-dateTime(xp20:current-date(),'[Y0001][M01][D01][H01][M01][s01]'))"/>
        </app:FileName>
        <app:Date>
          <xsl:value-of select="xp20:format-dateTime(xp20:current-date(),'[Y0001][M01][D01]')"/>
        </app:Date-->
      </app:HeaderLine>
      <xsl:for-each select="/eo:ESBMsg/eo:RqData/eo:Card">
        <app:DataLine>
          <app:LineIdentifier>D</app:LineIdentifier>
          <app:UnitID>
            <xsl:value-of select="com:CardIdentifier/com:BankID"/>
          </app:UnitID>
          <app:CardID>
            <xsl:value-of select="com:CardIdentifier/com:CardNumber"/>
          </app:CardID>
          <app:CardCcy>
            <xsl:value-of select="com:CardIdentifier/com:AccountCurrency"/>
          </app:CardCcy>
          <app:BranchCode>
            <xsl:value-of select="com:CardIdentifier/com:BranchID"/>
          </app:BranchCode>
          <app:CardHolderName>
            <xsl:value-of select="custeo:Customer/com:Person/com:PersonName/com:FullName"/>
          </app:CardHolderName>
          <app:OpenDate>
            <xsl:value-of select="eo:CardOpenDate"/>
          </app:OpenDate>
          <app:CustID>
            <xsl:value-of select="custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
          </app:CustID>
          <app:CardAccNo>
            <xsl:value-of select="com:CardIdentifier/com:AccountID"/>
          </app:CardAccNo>
          <app:CardType>
            <xsl:value-of select="eo:CardType"/>
          </app:CardType>
          <app:ExpiryDate>
            <xsl:value-of select="eo:CardExpiryDate"/>
          </app:ExpiryDate>
          <app:PrimaryFlag/>
          <app:CardStatus>
            <xsl:value-of select="eo:CardStatus"/>
          </app:CardStatus>
          <app:Country>
            <xsl:value-of select="custeo:Customer/com:Address/com:CountyName"/>
          </app:Country>
          <app:RecordType/>
          <app:CardCategory>
            <xsl:value-of select="eo:CardCategory"/>
          </app:CardCategory>
        </app:DataLine>
      </xsl:for-each>
      <app:TrailerLine>
        <app:LineIdentifier>T</app:LineIdentifier>
        <app:NumberOfRows>
          <xsl:value-of select="count(/eo:ESBMsg/eo:RqData/eo:Project)"/>
        </app:NumberOfRows>
      </app:TrailerLine>
    </app:CreditCardFileInput>
  </xsl:template>
</xsl:stylesheet>
