<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:ns0="http://xmlns.equitybank.co.ke/RM/MobileDevice/Customer/V1"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:tns="http://xmlns.equitybank.co.ke/BM/Party/Customer/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:eo="http://xmlns.equitybank.co.ke/EO/Parties/Customer/V1"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Customer/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:acceo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Customer/V1/CustomerRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="CustomerValidationRequestRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Customer/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Parties/Customer/V1/CustomerEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAR 12 20:34:18 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <custeo:ESBMsg>
    <xsl:choose>
    <xsl:when test="/ro:CustomerValidationRequestRM/ro:MsgID">
      <com:MsgID>
        <xsl:value-of select="/ro:CustomerValidationRequestRM/ro:MsgID"/>
      </com:MsgID>
      </xsl:when>
      <xsl:otherwise>
      <com:MsgID>
        <xsl:value-of select="UUIDUserFunction:uuid ( )"/>
      </com:MsgID>
      </xsl:otherwise>
      </xsl:choose>
      <com:Source>MDE</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>AccountES</com:Service>
      <custeo:RqData>
        <custeo:Customer>
          <com:Person>
            <com:IdentityDocument>
              <com:IdentityDocumentID>
                <xsl:value-of select="/ro:CustomerValidationRequestRM/ro:Idnr"/>
              </com:IdentityDocumentID>
              <com:IdentityDocumentSerialNumber>
                <xsl:value-of select="/ro:CustomerValidationRequestRM/ro:IDSerialNr"/>
              </com:IdentityDocumentSerialNumber>
              <com:IssueDate>
                <xsl:value-of select="/ro:CustomerValidationRequestRM/ro:DateofIssue"/>
              </com:IssueDate>
            </com:IdentityDocument>
          </com:Person>
        </custeo:Customer>
      </custeo:RqData>
    </custeo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>