<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:v1="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Bill/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/v12.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/v12.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:v13="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/v12.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/v12.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/v12.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/v12.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl v13 v1 oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:v12="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:v11="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:ns4="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:ns2="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns5="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:ns1="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:ns0="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ns3="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Bill/V1/BillEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Bill/V1/BillRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Bill/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 16 19:22:13 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <v1:ESBMsg>
      <v11:MsgID>
        <xsl:value-of select="/v13:ESBMsg/v12:MsgID"/>
      </v11:MsgID>
      <xsl:if test="/v13:ESBMsg/v13:RsData">
        <v1:RsData>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill">
            <v1:Bill>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier">
                <v1:BillIdentifier>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:BankID">
                    <v12:BankID>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:BankID"/>
                    </v12:BankID>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:BillerID">
                    <v12:BillerID>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:BillerID"/>
                    </v12:BillerID>
                  </xsl:if>
                  <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:BillID">
                    <v12:BillID>
                      <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:BillID"/>
                    </v12:BillID>
                  </xsl:if>
                </v1:BillIdentifier>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v13:BillType">
                <v1:BillType>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v13:BillType"/>
                </v1:BillType>
              </xsl:if>
              <xsl:choose>
                <xsl:when test="/v13:ESBMsg/v13:RsData/v13:Bill/v13:BillStatus = 'true'">
                  <v1:BillStatus>True</v1:BillStatus>
                </xsl:when>
                <xsl:when test="/v13:ESBMsg/v13:RsData/v13:Bill/v13:BillStatus = 'false'">
                  <v1:BillStatus>False</v1:BillStatus>
                </xsl:when>
                <xsl:otherwise>
                  <v1:BillStatus>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v13:BillStatus"/>
                  </v1:BillStatus>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:choose>
                <xsl:when test="/v13:ESBMsg/v13:RsData/v13:Bill/v13:Status">
                  <v1:StatusDesc>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v13:Status"/>
                  </v1:StatusDesc>
                </xsl:when>
                <xsl:otherwise>
                  <v1:StatusDesc>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text"/>
                  </v1:StatusDesc>
                </xsl:otherwise>
              </xsl:choose>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v12:Amount">
                <v11:Amount>
                  <v11:Value>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:Amount"/>
                  </v11:Value>
                  <v11:CurrencyCode>
                    <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:Amount/@currencyCode"/>
                  </v11:CurrencyCode>
                </v11:Amount>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BranchName">
                <v1:BranchName>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BranchName"/>
                </v1:BranchName>
              </xsl:if>
              <v1:DealerCode>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:DealerCode"/>
              </v1:DealerCode>
              <v1:DealerAccountNumber>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:BillIdentifier/v12:AccountID"/>
              </v1:DealerAccountNumber>
              <v1:PayMethod>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v12:PayMethod"/>
              </v1:PayMethod>
              <v1:CustomerReferenceNumber>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v13:CustomerRefNumber"/>
              </v1:CustomerReferenceNumber>
              <v1:DocumentReferenceNumber>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v13:DocumentrRefNumber"/>
              </v1:DocumentReferenceNumber>
              <v1:CustomerName>
                <xsl:value-of select="/v13:ESBMsg/v13:RsData/v13:Bill/v13:CustomerName"/>
              </v1:CustomerName>
              <v1:BillCreationDate>
                <xsl:value-of select="translate(/v13:ESBMsg/v13:RsData/v13:Bill/v13:CreatedBy,'-','')"/>
              </v1:BillCreationDate>
            </v1:Bill>
          </xsl:if>
          <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status">
            <v12:Status>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Code">
                <v12:Code>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Code"/>
                </v12:Code>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Type">
                <v12:Type>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Type"/>
                </v12:Type>
              </xsl:if>
              <xsl:if test="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text">
                <v12:Text>
                  <xsl:value-of select="/v13:ESBMsg/v13:RsData/v12:Status/v12:Text"/>
                </v12:Text>
              </xsl:if>
            </v12:Status>
          </xsl:if>
        </v1:RsData>
      </xsl:if>
    </v1:ESBMsg>
  </xsl:template>
</xsl:stylesheet>