<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl eo rs oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Settlement/V1"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas" xmlns:rs="http://xmlns.equitybank.co.ke/ESB/RS/Chai/TransferRO/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:oracFT="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:StringFunctions="http://www.oracle.com/XSL/Transform/java/utilties.xpath.extensions.StringFunctions"
                xmlns:oracEj="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:oracFf="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:DateFunctions="http://www.oracle.com/XSL/Transform/java/utilties.xpath.extensions.DateFunctions"
                xmlns:LookupTable="http://www.oracle.com/XSL/Transform/java/soa.utilities.dvm.LookupTable">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../../../Schemas/SettlementEO.xsd"/>
                <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Settlement/V1"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../../../Schemas/TransferRO.xsd"/>
                <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/RS/Chai/TransferRO/V1"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 19 12:49:46 EAT 2015].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <rs:ESBMsg>
            <xsl:for-each select="/eo:ESBMsg/eo:RsData/eo:Transfer">
                <xsl:if test='eo:RefKey !=""'>
                    <rs:transfers>
                        <rs:user>
                            <xsl:value-of select="eo:ID"/>
                        </rs:user>
                        <rs:amount>
                            <xsl:value-of select="com:Amount"/>
                        </rs:amount>
                        <rs:userGroup>
                            <xsl:value-of select="eo:UserGroup"/>
                        </rs:userGroup>
                        <rs:transRef>
                            <xsl:value-of select="eo:RefKey"/>
                        </rs:transRef>
                        <rs:statusCode>
                            <xsl:value-of select="com:Status/com:Code"/>
                        </rs:statusCode>
                        <rs:statusText>
                            <xsl:value-of select="com:Status/com:Text"/>
                        </rs:statusText>
                    </rs:transfers>
                </xsl:if>
            </xsl:for-each>
        </rs:ESBMsg>
    </xsl:template>
</xsl:stylesheet>