DROP INDEX XREF_STATECODE_ROW_ID_IDX;
DROP INDEX XREF_STATECODE_CODE_IDX;
DROP INDEX XREF_STATECODE_DESCRIPTION_IDX;

DROP TABLE XREF_STATECODE;

DROP INDEX XREF_COUNTRY_CODE_ROW_ID_IDX;
DROP INDEX XREF_COUNTRY_CODE_CODE_IDX;
DROP INDEX XREF_COUNTRY_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_COUNTRY_CODE;


DROP INDEX XREF_OCCUPATION_CODE_ROW_ID_IDX;
DROP INDEX XREF_OCCUPATION_CODE_CODE_IDX;
DROP INDEX XREF_OCCUPATION_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_OCCUPATION_CODE;

DROP INDEX XREF_INDUSTRY_CODE_ROW_ID_IDX;
DROP INDEX XREF_INDUSTRY_CODE_CODE_IDX;
DROP INDEX XREF_INDUSTRY_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_INDUSTRY_CODE;


DROP INDEX XREF_SUBTYPE_CODE_ROW_ID_IDX;
DROP INDEX XREF_SUBTYPE_CODE_CODE_IDX;
DROP INDEX XREF_SUBTYPE_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_SUBTYPE_CODE;


DROP INDEX XREF_CURRENCY_CODE_ROW_ID_IDX;
DROP INDEX XREF_CURRENCY_CODE_CODE_IDX;
DROP INDEX XREF_CURRENCY_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_CURRENCY_CODE;

DROP INDEX XREF_NATIONALITY_CODE_ROW_ID_IDX;
DROP INDEX XREF_NATIONALITY_CODE_CODE_IDX;
DROP INDEX XREF_NATIONALITY_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_NATIONALITY_CODE;

DROP INDEX XREF_DESPATCH_CODE_ROW_ID_IDX;
DROP INDEX XREF_DESPATCH_CODE_CODE_IDX;
DROP INDEX XREF_DESPATCH_CODE_DESCRIPTION_IDX;

DROP TABLE XREF_DESPATCH_CODE;



CREATE TABLE XREF_STATECODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE TABLE XREF_COUNTRY_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE TABLE XREF_OCCUPATION_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);


CREATE TABLE XREF_INDUSTRY_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE TABLE XREF_SUBTYPE_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE TABLE XREF_CURRENCY_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE TABLE XREF_NATIONALITY_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE TABLE XREF_DESPATCH_CODE (
    ROW_ID VARCHAR2(48) NOT NULL,
    CODE VARCHAR2(100),
    DESCRIPTION VARCHAR2(100),
    LAST_MODIFIED TIMESTAMP NOT NULL
);

CREATE INDEX XREF_COUNTRY_CODE_ROW_ID_IDX ON XREF_COUNTRY_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_COUNTRY_CODE_CODE_IDX ON XREF_COUNTRY_CODE(CODE);
CREATE INDEX XREF_COUNTRY_CODE_DESCRIPTION_IDX ON XREF_COUNTRY_CODE(DESCRIPTION);

CREATE INDEX XREF_STATECODE_ROW_ID_IDX ON XREF_STATECODE(ROW_ID) REVERSE;
CREATE INDEX XREF_STATECODE_CODE_IDX ON XREF_STATECODE(CODE);
CREATE INDEX XREF_STATECODE_DESCRIPTION_IDX ON XREF_STATECODE(DESCRIPTION);

CREATE INDEX XREF_OCCUPATION_CODE_ROW_ID_IDX ON XREF_OCCUPATION_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_OCCUPATION_CODE_CODE_IDX ON XREF_OCCUPATION_CODE(CODE);
CREATE INDEX XREF_OCCUPATION_CODE_DESCRIPTION_IDX ON XREF_OCCUPATION_CODE(DESCRIPTION);


CREATE INDEX XREF_INDUSTRY_CODE_ROW_ID_IDX ON XREF_INDUSTRY_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_INDUSTRY_CODE_CODE_IDX ON XREF_INDUSTRY_CODE(CODE);
CREATE INDEX XREF_INDUSTRY_CODE_DESCRIPTION_IDX ON XREF_INDUSTRY_CODE(DESCRIPTION);


CREATE INDEX XREF_SUBTYPE_CODE_ROW_ID_IDX ON XREF_SUBTYPE_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_SUBTYPE_CODE_CODE_IDX ON XREF_SUBTYPE_CODE(CODE);
CREATE INDEX XREF_SUBTYPE_CODE_DESCRIPTION_IDX ON XREF_SUBTYPE_CODE(DESCRIPTION);


CREATE INDEX XREF_CURRENCY_CODE_ROW_ID_IDX ON XREF_CURRENCY_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_CURRENCY_CODE_CODE_IDX ON XREF_CURRENCY_CODE(CODE);
CREATE INDEX XREF_CURRENCY_CODE_DESCRIPTION_IDX ON XREF_CURRENCY_CODE(DESCRIPTION);


CREATE INDEX XREF_NATIONALITY_CODE_ROW_ID_IDX ON XREF_NATIONALITY_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_NATIONALITY_CODE_CODE_IDX ON XREF_NATIONALITY_CODE(CODE);
CREATE INDEX XREF_NATIONALITY_CODE_DESCRIPTION_IDX ON XREF_NATIONALITY_CODE(DESCRIPTION);


CREATE INDEX XREF_DESPATCH_CODE_ROW_ID_IDX ON XREF_DESPATCH_CODE(ROW_ID) REVERSE;
CREATE INDEX XREF_DESPATCH_CODE_CODE_IDX ON XREF_DESPATCH_CODE(CODE);
CREATE INDEX XREF_DESPATCH_CODE_DESCRIPTION_IDX ON XREF_DESPATCH_CODE(DESCRIPTION);





INSERT INTO XREF_STATECODE VALUES (10,'CEN','CENTRAL',sysdate);
INSERT INTO XREF_STATECODE VALUES (20,'COA','COAST',sysdate);
INSERT INTO XREF_STATECODE VALUES (30,'EAS','EASTERN',sysdate);
INSERT INTO XREF_STATECODE VALUES (40,'KEN','KENYA',sysdate);
INSERT INTO XREF_STATECODE VALUES (50,'NAI','NAIROBI',sysdate);
INSERT INTO XREF_STATECODE VALUES (60,'NOR','NORTH EASTERN',sysdate);
INSERT INTO XREF_STATECODE VALUES (70,'NYA','NYANZA',sysdate);
INSERT INTO XREF_STATECODE VALUES (80,'RIF','RIFT VALLEY',sysdate);
INSERT INTO XREF_STATECODE VALUES (90,'WES','WESTERN',sysdate);



INSERT INTO XREF_COUNTRY_CODE VALUES (10,'KE','Kenyan',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (20,'SC','Seychoiles',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (30,'SO','Somalian',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (40,'ZA','South African',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (50,'GS','British',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (60,'SD','Sudanese',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (70,'SS','South Sudanese',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (80,'UG','Ugandan',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (90,'US','American',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (100,'NE','Nigerian',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (110,'RW','Rwandan',sysdate);
INSERT INTO XREF_COUNTRY_CODE VALUES (120,'WS','Samoan',sysdate);

INSERT INTO XREF_OCCUPATION_CODE VALUES (10,'Acc','Accountant',sysdate);
INSERT INTO XREF_OCCUPATION_CODE VALUES (20,'ADV','Advocate',sysdate);
INSERT INTO XREF_OCCUPATION_CODE VALUES (30,'ARCH','Architect',sysdate);

INSERT INTO XREF_INDUSTRY_CODE VALUES (10,'1AA','Government',sysdate);
INSERT INTO XREF_INDUSTRY_CODE VALUES (20,'1BC','Public sector',sysdate);
INSERT INTO XREF_INDUSTRY_CODE VALUES (30,'1DA','Manufacturing',sysdate);


INSERT INTO XREF_SUBTYPE_CODE VALUES (10,'CA201','Personal Account',sysdate);
INSERT INTO XREF_SUBTYPE_CODE VALUES (20,'LA531','Mircoloan',sysdate);
INSERT INTO XREF_SUBTYPE_CODE VALUES (30,'SB100','Ordinary Account',sysdate);
INSERT INTO XREF_SUBTYPE_CODE VALUES (40,'SB777','Hapo Hapo Account',sysdate);
INSERT INTO XREF_SUBTYPE_CODE VALUES (50,'SB109','Mkeso Account',sysdate);

INSERT INTO XREF_CURRENCY_CODE VALUES (10,'KES','KES',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (20,'USD','USD',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (30,'EUR','EUR',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (40,'GBP','GBP',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (50,'JPY','JPY',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (60,'NGN','NGN',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (70,'TZS','TZS',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (80,'RWF','RWF',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (90,'UFX','UFX',sysdate);
INSERT INTO XREF_CURRENCY_CODE VALUES (100,'YEN','YEN',sysdate);

INSERT INTO XREF_NATIONALITY_CODE VALUES (10,'KE','Kenya',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (20,'SC','Seychelles',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (30,'SO','Somalia',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (40,'ZA','South Africa',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (50,'GS','British',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (60,'SD','Sudanese',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (70,'SS','South Sudanese',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (80,'UG','Uganda',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (90,'US','America',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (100,'NE','Nigeria',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (110,'RW','Rwanda',sysdate);
INSERT INTO XREF_NATIONALITY_CODE VALUES (120,'WS','Samoa',sysdate);

INSERT INTO XREF_DESPATCH_CODE VALUES (10,'A','Post and Email',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (20,'B','Special Delivery and Email',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (30,'C','Collect By Person',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (40,'D','Courier and Email',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (50,'E','Email Only',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (60,'N','No Dispatch',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (70,'P','post',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (80,'Q','Courier',sysdate);
INSERT INTO XREF_DESPATCH_CODE VALUES (90,'S','Special Delivery',sysdate);

INSERT INTO XREF_TITLE_CODE VALUES (10,'MESS','MESS',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (20,'MISS','MISS',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (30,'MR','MR',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (40,'MRS','MRS',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (50,'MS','MS',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (60,'DR','DOCTER',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (70,'REV','REVEREND',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (80,'PROF','PROFESSOR',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (90,'MINOR','MINOR',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (100,'MAJOR','MAJOR',sysdate);
INSERT INTO XREF_TITLE_CODE VALUES (110,'GEN','GENERAl',sysdate);