<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Payment/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:rcom="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Payment/V1/PaymentRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Payment/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Payment/V1/PaymentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT MAY 02 17:47:46 PDT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/rcom:MsgID"/>
      </com:MsgID>
      <com:Source>COR</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>PaymentES</com:Service>
      <xsl:if test="/ns0:ESBMsg/ns0:RqData">
        <tns:RqData actionCode="QueryBillPaymentByID">
          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment">
            <tns:Payment>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PaymentIdentifier">
                <com:PaymentIdentifier>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PaymentIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PaymentIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PaymentIdentifier/com:PaymentID">
                    <com:PaymentID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PaymentIdentifier/com:PaymentID"/>
                    </com:PaymentID>
                  </xsl:if>
                </com:PaymentIdentifier>
              </xsl:if>
              <tns:PaymentType>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/tns:PaymentType"/>
              </tns:PaymentType>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier">
                <com:BillIdentifier>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BankBIC">
                    <com:BankBIC>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BankBIC"/>
                    </com:BankBIC>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BranchID">
                    <com:BranchID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BranchID"/>
                    </com:BranchID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:AccountID">
                    <com:AccountID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:AccountID"/>
                    </com:AccountID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:IBAN">
                    <com:IBAN>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:IBAN"/>
                    </com:IBAN>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:AccountCurrency">
                    <com:AccountCurrency>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:AccountCurrency"/>
                    </com:AccountCurrency>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BillerID">
                    <com:BillerID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BillerID"/>
                    </com:BillerID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BillID">
                    <com:BillID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:BillIdentifier/com:BillID"/>
                    </com:BillID>
                  </xsl:if>
                </com:BillIdentifier>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:BillAmount">
                <com:BillAmount currencyCode="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:BillAmount/rcom:CurrencyCode}">
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:BillAmount/rcom:Value"/>
                </com:BillAmount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier">
                <com:CardIdentifier>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:BankBIC">
                    <com:BankBIC>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:BankBIC"/>
                    </com:BankBIC>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:BranchID">
                    <com:BranchID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:BranchID"/>
                    </com:BranchID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:AccountID">
                    <com:AccountID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:AccountID"/>
                    </com:AccountID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:IBAN">
                    <com:IBAN>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:IBAN"/>
                    </com:IBAN>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:AccountCurrency">
                    <com:AccountCurrency>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:AccountCurrency"/>
                    </com:AccountCurrency>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:CardID">
                    <com:CardID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:CardID"/>
                    </com:CardID>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:CardNumber">
                    <com:CardNumber>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:CardIdentifier/com:CardNumber"/>
                    </com:CardNumber>
                  </xsl:if>
                </com:CardIdentifier>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Amount">
                <com:Amount currencyCode="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Amount/rcom:CurrencyCode}">
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Amount/rcom:Value"/>
                </com:Amount>
              </xsl:if>
              <com:ValueDate>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:ValueDate"/>
              </com:ValueDate>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:TotalAmount">
                <com:TotalAmount currencyCode="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:TotalAmount/rcom:CurrencyCode}">
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:TotalAmount/rcom:Value"/>
                </com:TotalAmount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:ChargeAmount">
                <com:ChargeAmount currencyCode="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:ChargeAmount/rcom:CurrencyCode}">
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:ChargeAmount/rcom:Value"/>
                </com:ChargeAmount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName">
                <com:PersonName>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:FullName">
                    <com:FullName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:FullName"/>
                    </com:FullName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:FirstName">
                    <com:FirstName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:FirstName"/>
                    </com:FirstName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:MiddleName">
                    <com:MiddleName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:MiddleName"/>
                    </com:MiddleName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:LastName">
                    <com:LastName>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:LastName"/>
                    </com:LastName>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:Title">
                    <com:Title>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PersonName/com:Title"/>
                    </com:Title>
                  </xsl:if>
                </com:PersonName>
              </xsl:if>
              <com:Remarks>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:Remarks"/>
              </com:Remarks>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount">
                <com:PayFromAccount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayFromAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </com:PayFromAccount>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount">
                <com:PayeeAccount>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:PayeeAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </com:PayeeAccount>
              </xsl:if>
              <tns:PaymentStatus>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/tns:PaymentStatus"/>
              </tns:PaymentStatus>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Rate">
                <com:Rate unitCode="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Rate/rcom:CurrencyCode}"
                          baseValue="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Rate/rcom:BaseValue}"
                          baseUnitCode="{/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Rate/rcom:BaseCurrencyCode}">
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/rcom:Rate/rcom:Value"/>
                </com:Rate>
              </xsl:if>
              <xsl:if test="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:Remarks">
                <tns:TransactionRemarks>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/ns0:Payment/com:Remarks"/>
                </tns:TransactionRemarks>
              </xsl:if>
            </tns:Payment>
          </xsl:if>
        </tns:RqData>
      </xsl:if>
    </tns:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
