<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:trnseo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:cardeo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:rs="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Payment/V1"
                xmlns:rcom="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Payment/V1/PaymentRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Payment/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Card/V1/CardBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI JUN 05 14:33:35 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/rs:ESBMsg/rcom:MsgID"/>
      </com:MsgID>
      <com:Source>COR</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>PaymentES</com:Service>
      <tns:RqData>
        <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment">
          <eo:Payment>
            <com:PaymentIdentifier>
              <com:BankID>
                <xsl:value-of select="/rs:ESBMsg/rs:RqData/com:BankID"/>
              </com:BankID>
            </com:PaymentIdentifier>
            <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment/com:CardIdentifier">
              <com:CardIdentifier>
                <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment/com:CardIdentifier/com:CardNumber">
                  <com:CardNumber>
                    <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Payment/com:CardIdentifier/com:CardNumber"/>
                  </com:CardNumber>
                </xsl:if>
              </com:CardIdentifier>
            </xsl:if>
            <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment/rcom:Amount">
              <com:Amount currencyCode="{/rs:ESBMsg/rs:RqData/rs:Payment/rcom:Amount/rcom:CurrencyCode}">
                <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Payment/rcom:Amount/rcom:Value"/>
              </com:Amount>
            </xsl:if>
            <com:ValueDate>
              <xsl:value-of select="concat(substring(/rs:ESBMsg/rs:RqData/rs:Payment/rs:ValueDate,1,4),'-',substring(/rs:ESBMsg/rs:RqData/rs:Payment/rs:ValueDate,5,2),'-',substring(/rs:ESBMsg/rs:RqData/rs:Payment/rs:ValueDate,7,2))"/>
            </com:ValueDate>
            <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment/com:Remarks">
              <com:Remarks>
                <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Payment/com:Remarks"/>
              </com:Remarks>
            </xsl:if>
            <com:PayFromAccount>
              <com:AccountIdentifier>
                <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID">
                  <com:AccountID>
                    <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountID"/>
                  </com:AccountID>
                </xsl:if>
                <xsl:if test="/rs:ESBMsg/rs:RqData/rs:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency">
                  <com:AccountCurrency>
                    <xsl:value-of select="/rs:ESBMsg/rs:RqData/rs:Payment/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency"/>
                  </com:AccountCurrency>
                </xsl:if>
              </com:AccountIdentifier>
            </com:PayFromAccount>
          </eo:Payment>
        </xsl:if>
      </tns:RqData>
    </tns:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
