<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:v1="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Payment/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 v1 oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:ns3="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:v12="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:trnseo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:cardeo="http://xmlns.equitybank.co.ke/ESB/EO/Instruments/Card/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:v13="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:v11="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1"
                xmlns:ns4="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Card/V1/CardBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Card/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Payment/V1/PaymentRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Payment/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE JUN 16 17:21:34 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="BankID"/>
  <xsl:template match="/">
    <v1:ESBMsg>
      <v11:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/v12:MsgID"/>
      </v11:MsgID>
      <v1:RsData>
        <v12:BankID>
          <xsl:value-of select="$BankID"/>
        </v12:BankID>
        <v1:Payment>
          <v1:CardPayment>
            <v1:CardPaymentID>
              <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/v13:Payment/v12:PaymentIdentifier/v12:PaymentID"/>
            </v1:CardPaymentID>
          </v1:CardPayment>
        </v1:Payment>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/v12:Status">
          <v12:Status>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/v12:Status/v12:Code">
              <v12:Code>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/v12:Status/v12:Code"/>
              </v12:Code>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/v12:Status/v12:Type">
              <v12:Type>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/v12:Status/v12:Type"/>
              </v12:Type>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/v12:Status/v12:Text">
              <v12:Text>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/v12:Status/v12:Text"/>
              </v12:Text>
            </xsl:if>
          </v12:Status>
        </xsl:if>
      </v1:RsData>
    </v1:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
