<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Notification/V1"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1">
  <xsl:output method="html" indent="yes" version="4.0"/>
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Account/V1/AccountBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"/>
        <oracle-xsl-mapper:param name="accountOpeningDO"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Account/V1/AccountBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"/>
        <oracle-xsl-mapper:param name="accountOpeningRespDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/EnterpriseObjects/Misc/Notification/V1/NotificationEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Notification/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAY 18 10:19:57 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="accountOpeningRespDO"/>
  <xsl:template match="/">
    <xsl:variable name="msg"/>
    <tns:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgID"/>
      </com:MsgID>
      <com:Source>
        <xsl:value-of select="/ns0:ESBMsg/com:Source"/>
      </com:Source>
      <com:MsgType>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgType"/>
      </com:MsgType>
      <com:Service>
        <xsl:value-of select="/ns0:ESBMsg/com:Service"/>
      </com:Service>
      <tns:RqData actionCode="SendEmail">
        <tns:Notification>
          <tns:FromEmailAddress>customercare@equitybank.co.ke</tns:FromEmailAddress>
          <tns:ToEmailAddress>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RqData/custeo:Customer/com:Email/com:EmailAddress"/>
          </tns:ToEmailAddress>
          <tns:Subject>Welcome to Equity Bank</tns:Subject>
          <tns:Body>
            <xsl:value-of select='concat ("&lt;p>Dear Member,&lt;/p> &lt;p>&lt;b>RE: Welcome to Equity Bank&lt;/b>&lt;/p>&lt;p>We thank you for choosing Equity Bank to be your financial partner by opening your account in the name of ", /ns0:ESBMsg/ns0:RqData/custeo:Customer/com:Person/com:PersonName/com:FullName, " on ", xp20:current-date ( ), ". &lt;/p>&lt;p>We appreciate this opportunity that you have given us to serve you.&lt;/p>&lt;p>At Equity Bank, we are continuously innovating products and services to meet our customers needs. Our promise and commitment is to deliver high quality customer focussed services. We invite you to experience some of our services that have been designed to give you convenience and ease of access using modern technology: &lt;/p>&lt;p>•	&lt;b>Eazzy 247:&lt;/b> This is banking using your phone, you can transfer funds, pay your bills; buy airtime among many other services. &lt;br>•	&lt;b>Internet Banking:&lt;/b> Access your account and do banking from the comfort of your home, office or anywhere in the world.&lt;br>•	&lt;b>Cash Back Service: &lt;/b> With your Equity ATM / VISA card you can pay for your goods and bills at no extra cost. In addition, at selected stores, you can withdraw cash from your account as you pay for your goods and services.  Just look out for shops that accept Equity Bank Cards.&lt;br>•	&lt;b>Statements via email:&lt;/b> All you need to do is fill a statement request form, indicate email address you want your statements to be sent to and frequency.&lt;/p> &lt;p>To know more about Equity Bank innovative, unique and exciting services, visit our website www.equitybank.co.ke. You will also find information on ATM and Branch locations, to help you identify the most convenient to you.&lt;/p>&lt;p>At Equity Bank, we welcome your suggestions and feedback to help us improve our services to you. You can write to us through the suggestion boxes in our branches, customercare@equitybank.co.ke; info@equitybank.co.ke or on the postal address indicated below. You can also call us on the Contact Centre numbers indicated below.&lt;/p>&lt;p>At Equity Bank we appreciate you and are honoured to be your financial partner. We look forward to serving you.&lt;/p>&lt;p>I take this opportunity to wish you good health, prosperity as we walk this journey together.&lt;br>Yours faithfully,&lt;/p>&lt;p>Customer Care Manager, &lt;br>&lt;b>Equity Bank Limited,&lt;/b>&lt;br>P. O. Box 75104 - 00200,&lt;br>&lt;b>NAIROBI.&lt;/b>&lt;/p>&lt;p>&lt;b>Equity Contact Centre:&lt;/b> 020 2744 000 / 0711 025 000 / 0734 108 000&lt;/p>" )'/>
          </tns:Body>
        </tns:Notification>
      </tns:RqData>
    </tns:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
