<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ro bo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:biomeo="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:bo="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"
                xmlns:accteo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Account/V1/AccountRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="CreateLoanAccountRequestRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Account/V1/AccountBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 29 14:51:14 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <bo:ESBMsg>
      <xsl:choose>
        <xsl:when test="/ro:CreateLoanAccountRequestRM/ro:MsgID">
          <com:MsgID>
            <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:MsgID"/>
          </com:MsgID>
        </xsl:when>
        <xsl:otherwise>
          <com:MsgID>
            <xsl:value-of select="UUIDUserFunction:uuid ( )"/>
          </com:MsgID>
        </xsl:otherwise>
      </xsl:choose>
      <com:Source>MDE</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>AccountES</com:Service>
      <bo:RqData actionCode="CreateLoanAccount">
        <biomeo:Biometric>
          <com:BiometricIdentifier>
            <com:BiometricID/>
          </com:BiometricIdentifier>
          <com:BiometricUserIdentifier>
            <com:BiometricUserID>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:AgentId"/>
            </com:BiometricUserID>
            <com:BiometricUserPin>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:AgentPin"/>
            </com:BiometricUserPin>
          </com:BiometricUserIdentifier>
          <biomeo:BiometricImage>
            <com:FingerPrints>
              <com:ImageL1>
                <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:AgentImage"/>
              </com:ImageL1>
            </com:FingerPrints>
          </biomeo:BiometricImage>
          <com:CustomerIdentifier>
            <com:CustomerID>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:AgentId"/>
            </com:CustomerID>
          </com:CustomerIdentifier>
        </biomeo:Biometric>
        <custeo:Customer>
          <com:CustomerIdentifier>
            <com:CustomerID>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:CustomerID"/>
            </com:CustomerID>
          </com:CustomerIdentifier>
          <com:Person>
            <com:MaritalStatus>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:MaritalStatus"/>
            </com:MaritalStatus>
            <com:Employment>
              <com:CompanyName>
                <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:CompanyName"/>
              </com:CompanyName>
              <com:EmploymentStatus>
                <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:EmployementStatus"/>
              </com:EmploymentStatus>
              <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:TimeInEmploymentMM">
                <com:TimeInEmploymentMM>
                  <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:TimeInEmploymentMM"/>
                </com:TimeInEmploymentMM>
              </xsl:if>
              <com:Phone>
                <com:CompleteNumber>
                  <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:EmployerPhone"/>
                </com:CompleteNumber>
              </com:Phone>
            </com:Employment>
            <com:IdentityDocument>
              <com:IdentityDocumentID>
                <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:DocumentId"/>
              </com:IdentityDocumentID>
              <com:IdentityDocumentSerialNumber>
                <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:DocumentIdReference"/>
              </com:IdentityDocumentSerialNumber>
            </com:IdentityDocument>
          </com:Person>
          <com:Phone>
            <com:CompleteNumber>
              <xsl:value-of select='concat(substring-before (/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:PhoneNumber, "-" ),substring-after (/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:PhoneNumber, "-" ))'/>
            </com:CompleteNumber>
            <com:CountryCode>
              <xsl:value-of select='substring-before (/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:PhoneNumber, "-" )'/>
            </com:CountryCode>
            <com:AreaCode/>
            <com:LocalNumber>
              <xsl:value-of select='substring-after (/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:PhoneNumber, "-" )'/>
            </com:LocalNumber>
            <com:PreferredIndicator>true</com:PreferredIndicator>
          </com:Phone>
          <custeo:PhonePin>
            <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:PhonePin"/>
          </custeo:PhonePin>
          <com:TermsAndCondition>
            <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:Document">
              <com:AgreementDocument mimeCode="application/pdf"
                                     fileName='{concat (/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:DocumentId, ".pdf" )}'
                                     characterSetCode="binary">
                <xsl:value-of select="string (/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:Document)"/>
              </com:AgreementDocument>
            </xsl:if>
          </com:TermsAndCondition>
        </custeo:Customer>
        <accteo:Account>
          <accteo:AccountType>
            <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:LoanType"/>
          </accteo:AccountType>
          <accteo:LoanProducts>
            <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:LoanProducts"/>
          </accteo:LoanProducts>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:LoanAmount">
            <accteo:LoanAmount>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:LoanAmount"/>
            </accteo:LoanAmount>
          </xsl:if>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:LoanPeriod">
            <accteo:LoanPeriod>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:LoanPeriod"/>
            </accteo:LoanPeriod>
          </xsl:if>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:RepaymentStartDate">
            <accteo:RepaymentStartDate>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:RepaymentStartDate"/>
            </accteo:RepaymentStartDate>
          </xsl:if>
          <accteo:ResidentialStatus>
            <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:ResidentialStatus"/>
          </accteo:ResidentialStatus>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:TimeAtAdressMM">
            <accteo:TimeAtAdressYY>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:TimeAtAdressMM"/>
            </accteo:TimeAtAdressYY>
          </xsl:if>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:TimeAtAdressMM">
            <accteo:TimeAtAdressMM>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:CustomerInfo/ro:TimeAtAdressMM"/>
            </accteo:TimeAtAdressMM>
          </xsl:if>
          <xsl:for-each select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:GoodsCategoryInfo">
            <com:GoodsCategory>
              <xsl:if test="ro:Good_Category">
                <com:Good_Category>
                  <xsl:value-of select="ro:Good_Category"/>
                </com:Good_Category>
              </xsl:if>
              <xsl:if test="ro:Good">
                <com:Good>
                  <xsl:value-of select="ro:Good"/>
                </com:Good>
              </xsl:if>
              <xsl:if test="ro:Good_Amount">
                <com:Good_Amount>
                  <xsl:value-of select="ro:Good_Amount"/>
                </com:Good_Amount>
              </xsl:if>
            </com:GoodsCategory>
          </xsl:for-each>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:MerchantRef">
            <accteo:MerchantReferenceNumber>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:MerchantRef"/>
            </accteo:MerchantReferenceNumber>
          </xsl:if>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:MerchantID">
            <accteo:MerchantID>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:MerchantID"/>
            </accteo:MerchantID>
          </xsl:if>
          <xsl:if test="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:ClientContribution">
            <accteo:ClientContribution>
              <xsl:value-of select="/ro:CreateLoanAccountRequestRM/ro:InStoreLoanInfo/ro:ClientContribution"/>
            </accteo:ClientContribution>
          </xsl:if>
        </accteo:Account>
      </bo:RqData>
    </bo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
