<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tns="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Account/V1/AccountRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="LoanQueryResponseRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 21 19:17:03 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:LoanQueryResponseRM>
    <com:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgID"/>
      </com:MsgID>
      <tns:CIFCode>
        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
      </tns:CIFCode>
      <tns:LoanDetails>
        <tns:LoanProducts>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LoanProducts"/>
        </tns:LoanProducts>
        <tns:LoanAmount>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LoanAmount"/>
        </tns:LoanAmount>
        <tns:ResponseCode>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:ResponseCode"/>
        </tns:ResponseCode>
        <tns:EffectiveInterestRate>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:EffectiveInterestRate"/>
        </tns:EffectiveInterestRate>
        <tns:Fees>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:Fees"/>
        </tns:Fees>
        <tns:MinimumLoanTerm>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MinimumLoanTerm"/>
        </tns:MinimumLoanTerm>
        <tns:MaximumLoanTerm>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaximumLoanTerm"/>
        </tns:MaximumLoanTerm>
        <tns:MaxCreditLimitAmnt>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaxCreditLimitAmnt"/>
        </tns:MaxCreditLimitAmnt>
        <tns:MinCreditLimitAmnt>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MinCreditLimitAmnt"/>
        </tns:MinCreditLimitAmnt>
        <tns:AffordableMonthlyRepayment>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaxPLInstallment"/>
        </tns:AffordableMonthlyRepayment>
        <tns:MaximumAffordableLoanAmount>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaximumAffordableLoanAmount"/>
        </tns:MaximumAffordableLoanAmount>
        <tns:MinimumLoanAmount>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MinimumLoanAmount"/>
        </tns:MinimumLoanAmount>
        <tns:EazzyLoanLimit>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:EazzyLoanLimit"/>
        </tns:EazzyLoanLimit>
        <tns:MaxPLLimitAmnt>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaxPLLimitAmnt"/>
        </tns:MaxPLLimitAmnt>
        <tns:MaxCCLimitAmnt>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaxCCLimitAmnt"/>
        </tns:MaxCCLimitAmnt>
      </tns:LoanDetails>
      <tns:Status>
        <tns:Status>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/com:Status/com:Type"/>
        </tns:Status>
        <tns:Code>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/com:Status/com:Code"/>
        </tns:Code>
        <tns:Description>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/com:Status/com:Text"/>
        </tns:Description>
      </tns:Status>
    </tns:LoanQueryResponseRM>
  </xsl:template>
</xsl:stylesheet>
