<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.equitybank.co.ke/RM/MobileDevice/Account/V1"
                xmlns:tns="http://xmlns.equitybank.co.ke/BM/RetailBanking/Account/V1"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:biomeo="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"
                xmlns:bo="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1" xmlns:uuid="java:java.util.UUID"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"
                xmlns:ns3="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Account/V1/AccountRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="AccountOpeningRequestRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Account/V1/AccountBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAR 12 20:31:53 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <bo:ESBMsg>
      <xsl:choose>
        <xsl:when test="/ro:AccountOpeningRequestRM/ro:MsgID">
          <com:MsgID>
            <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:MsgID"/>
          </com:MsgID>
        </xsl:when>
        <xsl:otherwise>
          <com:MsgID>
            <xsl:value-of select="substring(UUIDUserFunction:uuid ( ),0,33)"/>
          </com:MsgID>
        </xsl:otherwise>
      </xsl:choose>
      <com:Source>MDE</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>AccountES</com:Service>
      <bo:RqData>
        <biomeo:Biometric>
          <com:BiometricIdentifier>
            <com:BiometricID/>
          </com:BiometricIdentifier>
          <com:BiometricUserIdentifier>
            <com:BiometricUserID>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:AgentBioDetails/ro:AgentPinDetails/ro:UserID"/>
            </com:BiometricUserID>
            <com:BiometricUserPin>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:AgentBioDetails/ro:AgentPinDetails/ro:UserPin"/>
            </com:BiometricUserPin>
          </com:BiometricUserIdentifier>
          <biomeo:BiometricImage>
            <com:FingerPrints>
              <com:ImageL1 mimeCode="PNG">
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:AgentBioDetails/ro:Image"/>
              </com:ImageL1>
            </com:FingerPrints>
          </biomeo:BiometricImage>
          <com:CustomerIdentifier>
            <com:CustomerID>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:AgentBioDetails/ro:AgentPinDetails/ro:UserID"/>
            </com:CustomerID>
          </com:CustomerIdentifier>
        </biomeo:Biometric>
        <custeo:Customer>
          <com:Person>
            <com:PersonName>
              <com:FullName>
                <xsl:value-of select='concat (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Firstname, " ", /ro:AccountOpeningRequestRM/ro:PersonInfo/ro:SecondName, " ", /ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Familyname )'/>
              </com:FullName>
              <com:FirstName>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Firstname"/>
              </com:FirstName>
              <com:MiddleName>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:SecondName"/>
              </com:MiddleName>
              <com:LastName>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Familyname"/>
              </com:LastName>
              <com:Title>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Title"/>
              </com:Title>
            </com:PersonName>
            <com:BirthDate>
              <xsl:value-of select='substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:DOB, "T" )'/>
            </com:BirthDate>
            <com:GenderCode>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Gender"/>
            </com:GenderCode>
            <com:Language>USA (English)</com:Language>
            <com:Nationality>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Nationality"/>
            </com:Nationality>
            <com:MaritalStatus>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:MaritalStatus"/>
            </com:MaritalStatus>
            <com:Occupation>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:Occupation"/>
            </com:Occupation>
            <com:Employment>
              <com:CompanyName>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:CompanyName"/>
              </com:CompanyName>
              <com:Income>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:Income"/>
              </com:Income>
              <com:Occupation>
                <xsl:value-of select="ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:Occupation"/>
              </com:Occupation>
              <com:Address>
                <com:LineOne>
                  <xsl:value-of select='concat ("P.O. Box ", /ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:CompanyAddress/ro:PostalNumber )'/>
                </com:LineOne>
                <com:StateName>
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:CompanyAddress/ro:State"/>
                </com:StateName>
                <com:CountryName>
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:CompanyAddress/ro:Country"/>
                </com:CountryName>
                <com:PostalCode>
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:Employment/ro:CompanyAddress/ro:PostalCode"/>
                </com:PostalCode>
                <com:PreferredIndicator>true</com:PreferredIndicator>
              </com:Address>
              <!--com:Phone>
              <com:PhoneType>WORKTELEX</com:PhoneType>              
            <com:CompleteNumber>
              <xsl:value-of select='concat(substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" ),substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" ))'/>
            </com:CompleteNumber>
                <com:CountryCode>
                  <xsl:value-of select='substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" )'/>
                </com:CountryCode>
                <com:LocalNumber>
                  <xsl:value-of select='substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" )'/>
                </com:LocalNumber>
                <com:PreferredIndicator>false</com:PreferredIndicator>
              </com:Phone>              
          <com:Phone>          
              <com:PhoneType>CELLPH</com:PhoneType>
            <com:CompleteNumber>
              <xsl:value-of select='concat(substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" ),substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" ))'/>
            </com:CompleteNumber>
            <com:CountryCode>
              <xsl:value-of select='substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" )'/>
            </com:CountryCode>
            <com:LocalNumber>
              <xsl:value-of select='substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" )'/>
            </com:LocalNumber>
            <com:PreferredIndicator>true</com:PreferredIndicator>
          </com:Phone>
          <com:Email>
          <com:EmailType>COMMEML</com:EmailType>
            <com:EmailAddress>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PersonalMail"/>
            </com:EmailAddress>
            <com:PreferredIndicator>true</com:PreferredIndicator>
          </com:Email>
              <com:Email>
          <com:EmailType>WORKEML</com:EmailType>
                <com:EmailAddress>
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkEmail"/>
                </com:EmailAddress>
            <com:PreferredIndicator>false</com:PreferredIndicator>
              </com:Email-->
            </com:Employment>
            <com:FaceImage>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:FacePhoto"/>
            </com:FaceImage>
            <com:FingerPrints>
              <com:ImageL1 mimeCode="PNG">
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageL1"/>
              </com:ImageL1>
              <com:ImageL2 mimeCode="PNG">
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageL2"/>
              </com:ImageL2>
              <com:ImageR1 mimeCode="PNG">
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageR1"/>
              </com:ImageR1>
              <com:ImageR2 mimeCode="PNG">
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageR2"/>
              </com:ImageR2>
            </com:FingerPrints>
            <com:IdentityDocument>
              <com:IdentityDocumentID>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:IdDcouments/ro:DocumentId"/>
              </com:IdentityDocumentID>
              <com:IdentityDocumentSerialNumber>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:IdDcouments/ro:DocumentIdReference"/>
              </com:IdentityDocumentSerialNumber>
              <com:IdentityDocumentType>DOC03</com:IdentityDocumentType>
              <com:IssueDate>
                <xsl:value-of select='substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:IdDcouments/ro:IssueDate, "T" )'/>
              </com:IssueDate>
              <com:IssuingCountry>KE</com:IssuingCountry>
              <com:IssuingLocation>223</com:IssuingLocation>
              <com:IssuingAuthority/>
              <com:DocImage1>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:IdDcouments/ro:IDFrontImage"/>
              </com:DocImage1>
              <com:DocImage2>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:IdDcouments/ro:IDBackImage"/>
              </com:DocImage2>
            </com:IdentityDocument>
            <com:SignatureImage>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:SigFile/ro:FileContent"/>
            </com:SignatureImage>
          </com:Person>
          <com:Address>
            <com:AddressType>Mailing</com:AddressType>
            <com:LineOne>
              <xsl:value-of select='concat ("P.O. BOX ", /ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PostalAddress/ro:PostalNumber )'/>
            </com:LineOne>
            <com:CityName>223</com:CityName>
            <com:StateName>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PostalAddress/ro:State"/>
            </com:StateName>
            <com:CountryName>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PostalAddress/ro:Country"/>
            </com:CountryName>
            <com:PostalCode>
              <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PostalAddress/ro:PostalCode"/>
            </com:PostalCode>
            <com:PreferredIndicator>true</com:PreferredIndicator>
          </com:Address>
          <xsl:if test="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone">
            <com:Phone>
              <com:PhoneType>WORKTELEX</com:PhoneType>
              <com:CompleteNumber>
                <xsl:value-of select='concat(substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" ),substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" ))'/>
              </com:CompleteNumber>
              <!--com:CountryCode>
                  <xsl:value-of select='substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" )'/>
                </com:CountryCode>
                <com:LocalNumber>
                  <xsl:value-of select='substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkPhone, "-" )'/>
                </com:LocalNumber-->
              <com:PreferredIndicator>false</com:PreferredIndicator>
            </com:Phone>
          </xsl:if>
          <xsl:if test="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone">
            <com:Phone>
              <com:PhoneType>CELLPH</com:PhoneType>
              <com:CompleteNumber>
                <xsl:value-of select='concat(substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" ),substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" ))'/>
              </com:CompleteNumber>
              <!--com:CountryCode>
              <xsl:value-of select='substring-before (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" )'/>
            </com:CountryCode>
            <com:LocalNumber>
              <xsl:value-of select='substring-after (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:MobilePhone, "-" )'/>
            </com:LocalNumber-->
              <com:PreferredIndicator>true</com:PreferredIndicator>
            </com:Phone>
          </xsl:if>
          <xsl:if test="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PersonalMail">
            <com:Email>
              <com:EmailType>COMMEML</com:EmailType>
              <com:EmailAddress>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:PersonalMail"/>
              </com:EmailAddress>
              <com:PreferredIndicator>true</com:PreferredIndicator>
            </com:Email>
          </xsl:if>
          <xsl:if test="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkEmail">
            <com:Email>
              <com:EmailType>WORKEML</com:EmailType>
              <com:EmailAddress>
                <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:ContactInfo/ro:WorkEmail"/>
              </com:EmailAddress>
              <com:PreferredIndicator>false</com:PreferredIndicator>
            </com:Email>
          </xsl:if>
          <com:TermsAndCondition>
            <com:AgreementDocument mimeCode="application/pdf"
                                   fileName='{concat (/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:IdDcouments/ro:DocumentId, ".pdf" )}'
                                   characterSetCode="binary">
              <xsl:value-of select="string (/ro:AccountOpeningRequestRM/ro:Contract/ro:Document )"/>
            </com:AgreementDocument>
          </com:TermsAndCondition>
          <custeo:CustomerStatus>
            <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:AccountRefID"/>
          </custeo:CustomerStatus>
          <biomeo:Biometric>
            <com:BiometricIdentifier>
              <com:BiometricID/>
            </com:BiometricIdentifier>
            <biomeo:BiometricImage>
              <com:FingerPrints>
                <com:ImageL4 mimeCode="PNG">
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageL2"/>
                </com:ImageL4>
                <com:ImageL5 mimeCode="PNG">
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageL1"/>
                </com:ImageL5>
                <com:ImageR4 mimeCode="PNG">
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageR2"/>
                </com:ImageR4>
                <com:ImageR5 mimeCode="PNG">
                  <xsl:value-of select="/ro:AccountOpeningRequestRM/ro:PersonInfo/ro:BioMetricInfo/ro:ImageR1"/>
                </com:ImageR5>
              </com:FingerPrints>
            </biomeo:BiometricImage>
          </biomeo:Biometric>
        </custeo:Customer>
        <xsl:for-each select="/ro:AccountOpeningRequestRM/ro:AccountInfo">
          <eo:Account>
            <com:AccountIdentifier>
              <com:AccountCurrency>
                <xsl:value-of select="ro:CurrencyType"/>
              </com:AccountCurrency>
              <com:AccountType/>
            </com:AccountIdentifier>
            <xsl:choose>
              <xsl:when test="starts-with(ro:SchemeCode/text(),'SB')">
                <eo:AccountType>SBA</eo:AccountType>
              </xsl:when>
              <xsl:otherwise>
                <eo:AccountType>CAA</eo:AccountType>
              </xsl:otherwise>
            </xsl:choose>
            <eo:AccountSubType>
              <xsl:value-of select="ro:SchemeCode"/>
            </eo:AccountSubType>
            <eo:AccountStmtCode>S</eo:AccountStmtCode>
            <eo:StatementFrequency>
              <eo:CalenderType>
                <xsl:value-of select="ro:CalenderType"/>
              </eo:CalenderType>
              <eo:StmtDuration>
                <xsl:value-of select="ro:StmtType"/>
              </eo:StmtDuration>
              <eo:StartDay>
                <xsl:value-of select="ro:StartDt"/>
              </eo:StartDay>
              <eo:WeekDay>
                <xsl:value-of select="ro:WeekDay"/>
              </eo:WeekDay>
              <eo:WeekNum>
                <xsl:value-of select="ro:WeekNum"/>
              </eo:WeekNum>
              <eo:HolidaytStatus>
                <xsl:value-of select="ro:HolidayStatus"/>
              </eo:HolidaytStatus>
            </eo:StatementFrequency>
            <eo:AccountDespatchCode>
              <xsl:value-of select="ro:DespatchCode"/>
            </eo:AccountDespatchCode>
            <xsl:if test="ro:InstallmentAmount">
              <eo:JijengeAccount>
                <eo:InstallmentAmount>
                  <xsl:value-of select="ro:InstallmentAmount"/>
                </eo:InstallmentAmount>
                <eo:InstallmentPeriod>
                  <xsl:value-of select="ro:InstallmentPeriod"/>
                </eo:InstallmentPeriod>
              </eo:JijengeAccount>
            </xsl:if>
          </eo:Account>
        </xsl:for-each>
      </bo:RqData>
    </bo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>