<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ro oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:accteo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:biomeo="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/BusinessServices/RetailBanking/Account/V1/AccountBO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/BO/RetailBanking/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/MobileDevice/Account/V1/AccountRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="CreateLoanAccountResponseRM"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RO/MobileDevice/Account/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT MAY 30 11:53:33 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ro:CreateLoanAccountResponseRM>
    <com:MsgID>
        <xsl:value-of select="/ns0:ESBMsg/com:MsgID"/>
      </com:MsgID>
      <ro:CustomerID>
        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
      </ro:CustomerID>
      <ro:InStoreLoanResponse>
        <ro:LoanProduct>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/accteo:LoanProducts"/>
        </ro:LoanProduct>
        <ro:LoanRespCode>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/accteo:ResponseCode"/>
        </ro:LoanRespCode>
        <ro:TransactApplicationNumber>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/com:TransactionReferenceNumber"/>
        </ro:TransactApplicationNumber>
        <ro:LoanDecision>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/accteo:LoanDecision"/>
        </ro:LoanDecision>
        <ro:LoanAccountCreationStatus>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/accteo:AccountCreateStatus"/>
        </ro:LoanAccountCreationStatus>
        <ro:NewAccountOpened>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/accteo:NewAccOpened"/>
        </ro:NewAccountOpened>
        <ro:PolicyRules>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/accteo:Account/accteo:PolicyRules"/>
        </ro:PolicyRules>
      </ro:InStoreLoanResponse>
      <ro:Status>
        <ro:Status>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/com:Status/com:Type"/>
        </ro:Status>
        <ro:Code>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/com:Status/com:Code"/>
        </ro:Code>
        <ro:Description>
          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/com:Status/com:Text"/>
        </ro:Description>
      </ro:Status>
    </ro:CreateLoanAccountResponseRM>
  </xsl:template>
</xsl:stylesheet>
