<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:rs="urn:control.services.tiplus2.misys.com"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1"
                xmlns:msg="urn:messages.service.ti.apps.tiplus2.misys.com"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Employee/V1"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Notification/V1"
                xmlns:ns2="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Misys/AppMetadata/V1/Control.xsd"/>
        <oracle-xsl-mapper:rootElement name="ServiceResponse" namespace="urn:control.services.tiplus2.misys.com"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAY 11 15:43:57 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <rs:ServiceResponse>
      <rs:ResponseHeader>
        <rs:Service>Account</rs:Service>
        <rs:Operation>AccountSearch</rs:Operation>
        <xsl:choose>
          <xsl:when test='/eo:ESBMsg/eo:RsData/com:Status/com:Type = "SUCCESS"'>
            <rs:Status>SUCCEEDED</rs:Status>
          </xsl:when>
          <xsl:when test='/eo:ESBMsg/eo:RsData/com:Status/com:Type = "FAILURE"'>
            <rs:Status>FAILED</rs:Status>
          </xsl:when>
          <xsl:otherwise>
            <rs:Status>UNAVAILABLE</rs:Status>
          </xsl:otherwise>
        </xsl:choose>
        <rs:Details>
          <xsl:choose>
            <xsl:when test='/eo:ESBMsg/eo:RsData/com:Status/com:Type = "FAILURE"'>
              <rs:Error>ESB-100</rs:Error>
            </xsl:when>
          </xsl:choose>
          <rs:Info>
            <xsl:value-of select="/eo:ESBMsg/eo:RsData/com:Status/com:Text"/>
          </rs:Info>
        </rs:Details>
        <rs:CorrelationId>2102</rs:CorrelationId>
      </rs:ResponseHeader>
      <msg:AccountSearchResponse>
        <msg:AccountSearchResults>
          <msg:AccountSearchResult>
            <msg:BranchNumber>
              <xsl:choose>
                <xsl:when test="string-length(/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:BranchID)&lt; 4">
                  <xsl:value-of select="concat('0',/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:BranchID)"/>
                </xsl:when>
                <xsl:otherwise>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:BranchID"/>
                </xsl:otherwise>
              </xsl:choose>
            </msg:BranchNumber>
            <msg:CustomerNumber>
              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
            </msg:CustomerNumber>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Account/eo:AccountType">
              <msg:AccountType>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/eo:AccountType"/>
              </msg:AccountType>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:AccountCurrency">
              <msg:Currency>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:AccountCurrency"/>
              </msg:Currency>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:AccountID">
              <msg:BackOfficeAccount>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:AccountID"/>
              </msg:BackOfficeAccount>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:MiddleName">
              <msg:ShortName>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/custeo:Customer/com:Person/com:PersonName/com:MiddleName"/>
              </msg:ShortName>
            </xsl:if>
            <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:IBAN">
              <msg:IBAN>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Account/com:AccountIdentifier/com:IBAN"/>
              </msg:IBAN>
            </xsl:if>
          </msg:AccountSearchResult>
        </msg:AccountSearchResults>
      </msg:AccountSearchResponse>
    </rs:ServiceResponse>
  </xsl:template>
</xsl:stylesheet>