<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Notification/V1"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:app="http://www.csapi.org/schema/parlayx/sms/send/v2_2/local"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:parlayx_sms_send="http://www.csapi.org/wsdl/parlayx/sms/send/v2_2/interface"
                xmlns:parlayx_sms_xsd="http://www.csapi.org/schema/parlayx/sms/v2_2"
                xmlns:parlayx_common_faults="http://www.csapi.org/wsdl/parlayx/common/v2_0/faults"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:parlayx_common_xsd="http://www.csapi.org/schema/parlayx/common/v2_1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Misc/Notification/V1/NotificationEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Misc/Notification/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Safaricom/AppMetadata/wsdls/SendSmsInterface.wsdl"/>
        <oracle-xsl-mapper:rootElement name="sendSms"
                                       namespace="http://www.csapi.org/schema/parlayx/sms/send/v2_2/local"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAY 13 16:42:26 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <app:sendSms>
      <app:addresses>
        <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Notification/eo:ToMobileNumber"/>
      </app:addresses>
      <app:senderName>
        <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Notification/eo:FromMobileNumber"/>
      </app:senderName>
      <app:message>
        <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Notification/eo:Body"/>
      </app:message>
      <app:receiptRequest>
        <interfaceName>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Notification/eo:NotificationType"/>
        </interfaceName>
        <correlator>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Notification/com:NotificationIdentifier/com:NotificationID"/>
        </correlator>
      </app:receiptRequest>
    </app:sendSms>
  </xsl:template>
</xsl:stylesheet>
