<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:psc="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo psc xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:es="http://xmlns.equitybank.co.ke/ESB/ES/Transactions/Bill/V1"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/ChaiBillESWrapper.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/EqpgwPS.wsdl"/>
        <oracle-xsl-mapper:rootElement name="ChaiBillRequestPSM"
                                       namespace="http://xmlns.equitybank.co.ke/ProviderComponents/PSC/Transactions/Bill/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAY 06 12:54:45 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <psc:ChaiBillRequestPSM>
      <psc:DataArea>
        <psc:SourceSystem>
          <xsl:value-of select="/eo:ESBMsg/com:Source"/>
        </psc:SourceSystem>
        <psc:UserID>
          <xsl:value-of select="concat(/eo:ESBMsg/eo:RqData/eo:Bill/com:UserID,'@',xp20:current-dateTime ( ))"/>
        </psc:UserID>
        <psc:PaymentRef>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:PaymentRef"/>
        </psc:PaymentRef>
        <psc:Amount>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:Amount"/>
        </psc:Amount>
        <psc:Description>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:ShortDescription"/>
        </psc:Description>
        <psc:CustomerName>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:PersonName/com:FullName"/>
        </psc:CustomerName>
        <psc:CurrencyCode>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:ExchangeCurrency"/>
        </psc:CurrencyCode>
        <psc:Mobile>
          <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:MobileWallet/com:MobileNumber"/>
        </psc:Mobile>
      </psc:DataArea>
    </psc:ChaiBillRequestPSM>
  </xsl:template>
</xsl:stylesheet>
