<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Transfer/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo ro oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:rcom="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Transfer/V1/TransferEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Polaris/Transfer/V1/TransferRO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/RS/Polaris/Transfer/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [TUE MAY 19 13:58:05 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <ro:ESBMsg>
      <rcom:MsgID>
        <xsl:value-of select="/eo:ESBMsg/com:MsgID"/>
      </rcom:MsgID>
      <xsl:if test="/eo:ESBMsg/eo:RsData">
        <ro:RsData>
          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer">
            <ro:Transfer>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:TransferIdentifier">
                <com:TransferIdentifier>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:TransferIdentifier/com:BankID">
                    <com:BankID>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:TransferIdentifier/com:BankID"/>
                    </com:BankID>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:TransferIdentifier/com:TransferID">
                    <com:TransferID>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:TransferIdentifier/com:TransferID"/>
                    </com:TransferID>
                  </xsl:if>
                </com:TransferIdentifier>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferType">
                <eo:TransferType>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferType"/>
                </eo:TransferType>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:PurposeCode">
                <eo:PurposeCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:PurposeCode"/>
                </eo:PurposeCode>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:ChargeEventID">
                <eo:ChargeEventID>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:ChargeEventID"/>
                </eo:ChargeEventID>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:ChargeOption">
                <eo:ChargeOption>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:ChargeOption"/>
                </eo:ChargeOption>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:WaiveChargesIndicator">
                <eo:WaiveChargesIndicator>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:WaiveChargesIndicator"/>
                </eo:WaiveChargesIndicator>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferOrderType">
                <eo:TransferOrderType>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferOrderType"/>
                </eo:TransferOrderType>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Amount">
                <rcom:Amount>
                  <rcom:Value>
                    <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Amount"/>
                  </rcom:Value>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Amount/@currencyCode">
                    <rcom:CurrencyCode>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Amount/@currencyCode"/>
                    </rcom:CurrencyCode>
                  </xsl:if>
                </rcom:Amount>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:InstructedAmount">
                <ro:InstructedAmount>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:InstructedAmount/@currencyCode">
                    <rcom:CurrencyCode>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:InstructedAmount/@currencyCode"/>
                    </rcom:CurrencyCode>
                  </xsl:if>
                </ro:InstructedAmount>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:ChargeAmount">
                <rcom:ChargeAmount>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:ChargeAmount/@currencyCode">
                    <rcom:CurrencyCode>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:ChargeAmount/@currencyCode"/>
                    </rcom:CurrencyCode>
                  </xsl:if>
                </rcom:ChargeAmount>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:ValueDate">
                <com:ValueDate>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:ValueDate"/>
                </com:ValueDate>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:DebitValueDate">
                <eo:DebitValueDate>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:DebitValueDate"/>
                </eo:DebitValueDate>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:DebitExecutionDate">
                <eo:DebitExecutionDate>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:DebitExecutionDate"/>
                </eo:DebitExecutionDate>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:CreditValueDate">
                <eo:CreditValueDate>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:CreditValueDate"/>
                </eo:CreditValueDate>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:CreditExecutionDate">
                <eo:CreditExecutionDate>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:CreditExecutionDate"/>
                </eo:CreditExecutionDate>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Rate">
                <rcom:Rate>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Rate/@baseValue">
                    <rcom:Value>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Rate/@baseValue"/>
                    </rcom:Value>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Rate/@baseValue">
                    <rcom:BaseValue>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Rate/@baseValue"/>
                    </rcom:BaseValue>
                  </xsl:if>
                </rcom:Rate>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Remarks">
                <com:Remarks>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:Remarks"/>
                </com:Remarks>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferReferenceNumber">
                <eo:TransferReferenceNumber>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferReferenceNumber"/>
                </eo:TransferReferenceNumber>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount">
                <com:PayFromAccount>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountType">
                        <com:AccountType>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountType"/>
                        </com:AccountType>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountSubType">
                        <com:AccountSubType>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:AccountIdentifier/com:AccountSubType"/>
                        </com:AccountSubType>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:ShortName">
                            <com:ShortName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:ShortName"/>
                            </com:ShortName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </com:PayFromAccount>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount">
                <com:PayeeAccount>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountType">
                        <com:AccountType>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountType"/>
                        </com:AccountType>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountSubType">
                        <com:AccountSubType>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:AccountIdentifier/com:AccountSubType"/>
                        </com:AccountSubType>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:ShortName">
                            <com:ShortName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:ShortName"/>
                            </com:ShortName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </com:PayeeAccount>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:CountryCode">
                <com:CountryCode>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:CountryCode"/>
                </com:CountryCode>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryIndicator">
                <eo:IntermediaryIndicator>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryIndicator"/>
                </eo:IntermediaryIndicator>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount">
                <eo:IntermediaryAccount>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier">
                    <com:AccountIdentifier>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:BankID">
                        <com:BankID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:BankID"/>
                        </com:BankID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:BankBIC">
                        <com:BankBIC>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:BankBIC"/>
                        </com:BankBIC>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:BranchID">
                        <com:BranchID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:BranchID"/>
                        </com:BranchID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountID">
                        <com:AccountID>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountID"/>
                        </com:AccountID>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:IBAN">
                        <com:IBAN>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:IBAN"/>
                        </com:IBAN>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountCurrency">
                        <com:AccountCurrency>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountCurrency"/>
                        </com:AccountCurrency>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountType">
                        <com:AccountType>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountType"/>
                        </com:AccountType>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountSubType">
                        <com:AccountSubType>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:AccountIdentifier/com:AccountSubType"/>
                        </com:AccountSubType>
                      </xsl:if>
                    </com:AccountIdentifier>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference">
                    <com:PartyReference>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:OrganizationName">
                        <com:OrganizationName>
                          <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:OrganizationName"/>
                        </com:OrganizationName>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName">
                        <com:PersonName>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:FullName">
                            <com:FullName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:FullName"/>
                            </com:FullName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:FirstName">
                            <com:FirstName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:FirstName"/>
                            </com:FirstName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:MiddleName">
                            <com:MiddleName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:MiddleName"/>
                            </com:MiddleName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:LastName">
                            <com:LastName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:LastName"/>
                            </com:LastName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:ShortName">
                            <com:ShortName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:ShortName"/>
                            </com:ShortName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:Title">
                            <com:Title>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:PersonName/com:Title"/>
                            </com:Title>
                          </xsl:if>
                        </com:PersonName>
                      </xsl:if>
                      <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address">
                        <com:Address>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:AddressType">
                            <com:AddressType>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:AddressType"/>
                            </com:AddressType>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineOne">
                            <com:LineOne>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineOne"/>
                            </com:LineOne>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineTwo">
                            <com:LineTwo>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineTwo"/>
                            </com:LineTwo>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineThree">
                            <com:LineThree>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineThree"/>
                            </com:LineThree>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineFour">
                            <com:LineFour>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:LineFour"/>
                            </com:LineFour>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:CityName">
                            <com:CityName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:CityName"/>
                            </com:CityName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:StateName">
                            <com:StateName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:StateName"/>
                            </com:StateName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:CountyName">
                            <com:CountyName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:CountyName"/>
                            </com:CountyName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:CountryName">
                            <com:CountryName>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:CountryName"/>
                            </com:CountryName>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:PostalCode">
                            <com:PostalCode>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:PostalCode"/>
                            </com:PostalCode>
                          </xsl:if>
                          <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:PreferredIndicator">
                            <com:PreferredIndicator>
                              <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:IntermediaryAccount/com:PartyReference/com:Address/com:PreferredIndicator"/>
                            </com:PreferredIndicator>
                          </xsl:if>
                        </com:Address>
                      </xsl:if>
                    </com:PartyReference>
                  </xsl:if>
                </eo:IntermediaryAccount>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:MobileWalletVendor">
                <com:MobileWalletVendor>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:MobileWalletVendor"/>
                </com:MobileWalletVendor>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromMobileWallet">
                <com:PayFromMobileWallet>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromMobileWallet/com:MobileNumber">
                    <com:MobileNumber>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromMobileWallet/com:MobileNumber"/>
                    </com:MobileNumber>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromMobileWallet/com:MobileUser">
                    <com:MobileUser>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayFromMobileWallet/com:MobileUser"/>
                    </com:MobileUser>
                  </xsl:if>
                </com:PayFromMobileWallet>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeMobileWallet">
                <com:PayeeMobileWallet>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeMobileWallet/com:MobileNumber">
                    <com:MobileNumber>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeMobileWallet/com:MobileNumber"/>
                    </com:MobileNumber>
                  </xsl:if>
                  <xsl:if test="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeMobileWallet/com:MobileUser">
                    <com:MobileUser>
                      <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/com:PayeeMobileWallet/com:MobileUser"/>
                    </com:MobileUser>
                  </xsl:if>
                </com:PayeeMobileWallet>
              </xsl:if>
              <eo:TransferStatus>
                <xsl:value-of select="/eo:ESBMsg/eo:RsData/eo:Transfer/eo:TransferStatus"/>
              </eo:TransferStatus>
            </ro:Transfer>
          </xsl:if>
          <xsl:if test="/eo:ESBMsg/eo:RsData/com:Status">
            <com:Status>
              <xsl:if test="/eo:ESBMsg/eo:RsData/com:Status/com:Code">
                <com:Code>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/com:Status/com:Code"/>
                </com:Code>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/com:Status/com:Type">
                <com:Type>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/com:Status/com:Type"/>
                </com:Type>
              </xsl:if>
              <xsl:if test="/eo:ESBMsg/eo:RsData/com:Status/com:Text">
                <com:Text>
                  <xsl:value-of select="/eo:ESBMsg/eo:RsData/com:Status/com:Text"/>
                </com:Text>
              </xsl:if>
            </com:Status>
          </xsl:if>
        </ro:RsData>
      </xsl:if>
    </ro:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
