<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Way4/AppMetadata/xsds/UFXMsg.xsd"/>
        <oracle-xsl-mapper:rootElement name="UFXMsg" namespace=""/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Payment/V1/PaymentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT MAY 02 09:52:22 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/UFXMsg/MsgId"/>
      </com:MsgID>
      <eo:RsData>
        <eo:Payment>
          <com:PaymentIdentifier>
            <com:PaymentID>
              <xsl:value-of select="/UFXMsg/MsgData/Doc/DocRefSet/Parm/Value"/>
            </com:PaymentID>
          </com:PaymentIdentifier>
        </eo:Payment>
        <com:Status>
          <xsl:choose>
            <xsl:when test="/UFXMsg/MsgData/Doc/Status/RespCode = '0'">
              <com:Code>ESB-00</com:Code>
              <com:Type>Success</com:Type>
              <com:Text>Card payment processed successfully</com:Text>
            </xsl:when>
            <xsl:when test="/UFXMsg/MsgData/Doc/Status/RespCode = '96'">
              <com:Code>ESB-1252401</com:Code>
              <com:Type>Failure</com:Type>
              <com:Text>
                <xsl:value-of select="/response/eazzycashres/status"/>
              </com:Text>
            </xsl:when>
            <xsl:when test="/UFXMsg/MsgData/Doc/Status/RespCode = '1200'">
              <com:Code>ESB-1252402</com:Code>
              <com:Type>Failure</com:Type>
              <com:Text>
                <xsl:value-of select="/response/eazzycashres/status"/>
              </com:Text>
            </xsl:when>
            <xsl:when test="/UFXMsg/MsgData/Doc/Status/RespCode = '14'">
              <com:Code>ESB-1252403</com:Code>
              <com:Type>Failure</com:Type>
              <com:Text>
                <xsl:value-of select="/response/eazzycashres/status"/>
              </com:Text>
            </xsl:when>
            <xsl:when test="/UFXMsg/MsgData/Doc/Status/RespCode = '115'">
              <com:Code>ESB-1252404</com:Code>
              <com:Type>Failure</com:Type>
              <com:Text>
                <xsl:value-of select="/response/eazzycashres/status"/>
              </com:Text>
            </xsl:when>
            <xsl:when test="/UFXMsg/MsgData/Doc/Status/RespCode = '30'">
              <com:Code>ESB-1252405</com:Code>
              <com:Type>Failure</com:Type>
              <com:Text>
                <xsl:value-of select="/response/eazzycashres/status"/>
              </com:Text>
            </xsl:when>
          </xsl:choose>
        </com:Status>
      </eo:RsData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>
