<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Payment/V1/PaymentEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Payment/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Way4/AppMetadata/xsds/UFXMsg.xsd"/>
        <oracle-xsl-mapper:rootElement name="UFXMsg" namespace=""/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SAT MAY 02 09:51:36 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <UFXMsg direction="Rq" msg_type="Doc" scheme="WAY4Doc" version="2.0">
      <MsgId>
        <xsl:value-of select="/eo:ESBMsg/com:MsgID"/>
      </MsgId>
      <Source app="WebPortal"/>
      <MsgData>
        <Doc>
          <TransType>
            <TransCode>
              <MsgCode>PAYCARD</MsgCode>
            </TransCode>
          </TransType>
          <DocRefSet>
            <Parm>
              <ParmCode>SRN</ParmCode>
              <Value>
                <xsl:value-of select="substring-before(UUIDUserFunction:uuid(),'-')"/>
              </Value>
            </Parm>
          </DocRefSet>
          <LocalDt>
            <xsl:value-of select="string(concat(/eo:ESBMsg/eo:RqData/eo:Payment/com:ValueDate,' 00:00:00'))"/>
          </LocalDt>
          <Description>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:Remarks"/>
          </Description>
          <Requestor>
            <ContractNumber>
              <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:CardIdentifier/com:CardNumber"/>
            </ContractNumber>
          </Requestor>
          <Source>
            <ContractNumber>068-TELLER</ContractNumber>
            <MemberId>0068</MemberId>
          </Source>
          <Transaction>
            <Currency>
              <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:Amount/@currencyCode"/>
            </Currency>
            <Amount>
              <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Payment/com:Amount"/>
            </Amount>
            <Extra>
              <Type>AddInfo</Type>
              <Details>DOC_MODE=SMS;ONLINE_CREDIT_PENDING=Y;</Details>
            </Extra>
          </Transaction>
        </Doc>
      </MsgData>
    </UFXMsg>
  </xsl:template>
</xsl:stylesheet>