<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:app="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd eo app oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:nxsd="http://xmlns.oracle.com/pcbpel/nxsd">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Transfer/V1/TransferEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../Adapter/ftp/PRS_FTP_Adapter.xsd"/>
        <oracle-xsl-mapper:rootElement name="RTGSInwardFileInput"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/PS/Polaris/Adapter/ftp"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [THU MAY 14 15:40:36 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <app:RTGSInwardFileInput>
      <xsl:for-each select="/eo:ESBMsg/eo:RqData/eo:Transfer">
        <app:DataLine>
          <app:LineIdentifier>D</app:LineIdentifier>
          <app:UnitID>
            <xsl:value-of select="com:TransferIdentifier/com:BankID"/>
          </app:UnitID>
          <app:drAcct>
            <xsl:value-of select="com:PayFromAccount/com:AccountIdentifier/com:AccountID"/>
          </app:drAcct>
          <app:tranAmt>
            <xsl:value-of select="com:Amount"/>
          </app:tranAmt>
          <app:BankCode>
            <xsl:value-of select="com:PayFromAccount/com:AccountIdentifier/com:BankID"/>
          </app:BankCode>
          <app:benCustAcctId>
            <xsl:value-of select="com:PayeeAccount/com:AccountIdentifier/com:AccountID"/>
          </app:benCustAcctId>
          <app:benCustName>
            <xsl:value-of select="com:PayeeAccount/com:PartyReference/com:PersonName/com:FullName"/>
          </app:benCustName>
          <app:benCustAddr1>
            <xsl:value-of select="com:PayeeAccount/com:PartyReference/com:Address/com:LineOne"/>
          </app:benCustAddr1>
          <app:benCustAddr2>
            <xsl:value-of select="com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo"/>
          </app:benCustAddr2>
          <app:benCustAddr2>
            <xsl:value-of select="com:PayeeAccount/com:PartyReference/com:Address/com:LineTwo"/>
          </app:benCustAddr2>
          <app:benCustAddr3>
            <xsl:value-of select="com:PayeeAccount/com:PartyReference/com:Address/com:LineThree"/>
          </app:benCustAddr3>
          <app:ordInstName/>
          <app:ordInstAddr1/>
          <app:ordInstAddr2/>
          <app:ordInstAddr3/>
          <app:pymntDetLine1/>
          <app:pymntDetLine2/>
          <app:pymntDetLine3/>
          <app:pymntDetLine4/>
          <app:sendRecvInfo1>
            <xsl:value-of select="eo:sendRecvInfo1"/>
          </app:sendRecvInfo1>
          <app:sendRecvInfo2/>
          <app:sendRecvInfo3/>
          <app:sendRecvInfo4/>
          <app:sendRecvInfo5/>
          <app:sendRecvInfo6/>
          <app:utrreferencenumber/>
        </app:DataLine>
      </xsl:for-each>
    </app:RTGSInwardFileInput>
  </xsl:template>
</xsl:stylesheet>
