<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ro eo xp20 oraxsl mhdr oraext dvm xref socket DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:ro="http://xmlns.equitybank.co.ke/ESB/RS/Chai/BillRO/V1"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1">
    <oracle-xsl-mapper:schema>
        <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
        <oracle-xsl-mapper:mapSources>
            <oracle-xsl-mapper:source type="XSD">
                <oracle-xsl-mapper:schema location="../../../Schemas/BillRO.xsd"/>
                <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/RS/Chai/BillRO/V1"/>
            </oracle-xsl-mapper:source>
        </oracle-xsl-mapper:mapSources>
        <oracle-xsl-mapper:mapTargets>
            <oracle-xsl-mapper:target type="XSD">
                <oracle-xsl-mapper:schema location="../../../Schemas/XMLSchema_-777266802.xsd"/>
                <oracle-xsl-mapper:rootElement name="ESBMsg" namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"/>
            </oracle-xsl-mapper:target>
        </oracle-xsl-mapper:mapTargets>
        <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [MON MAY 11 16:38:17 EAT 2015].-->
    </oracle-xsl-mapper:schema>
    <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
    <xsl:template match="/">
        <eo:ESBMsg>
            <com:Source>
                <xsl:value-of select="DVMFunctions:lookupValue ('ChaiReq/DVM/SourceAccount','SourceSystem',string(/ro:ESBMsg/ro:source),'BillerCode','')"/>
            </com:Source>
            <eo:RqData actionCode="CHSCreateBill">
                <eo:Bill>
                    <com:UserID>
                        <xsl:value-of select="/ro:ESBMsg/ro:user"/>
                    </com:UserID>
                    <com:PaymentRef>
                        <xsl:value-of select="/ro:ESBMsg/ro:ref"/>
                    </com:PaymentRef>
                    <com:Amount>
                        <xsl:value-of select="/ro:ESBMsg/ro:amount"/>
                    </com:Amount>
                    <com:ShortDescription>Bill Desc</com:ShortDescription>
                    <com:PersonName>
                        <com:FullName>
                            <xsl:value-of select="DVMFunctions:lookupValue ('ChaiReq/DVM/PayerAccount','UserID',string(/ro:ESBMsg/ro:user),'Name','')"/>
                        </com:FullName>
                    </com:PersonName>
                    <com:ExchangeCurrency>
                        <xsl:value-of select="DVMFunctions:lookupValue ('ChaiReq/DVM/PayerAccount','UserID',string(/ro:ESBMsg/ro:user),'Currency','')"/>
                    </com:ExchangeCurrency>
                    <com:MobileWallet>
                        <com:MobileNumber>
                            <xsl:value-of select="DVMFunctions:lookupValue ('ChaiReq/DVM/PayerAccount','UserID',string(/ro:ESBMsg/ro:user),'Mobile','')"/>
                        </com:MobileNumber>
                    </com:MobileWallet>
                </eo:Bill>
            </eo:RqData>
        </eo:ESBMsg>
    </xsl:template>
</xsl:stylesheet>