<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0" xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:app="http://ws.equitybank/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl ns0 tns oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns1="http://schemas.xmlsoap.org/soap/http">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Bill/V1/BillEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Bill/V1"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/ProviderServices/Safaricom/AppMetadata/wsdls/SafDealerService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="authRequest" namespace="http://ws.equitybank/"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI MAY 29 17:58:41 IST 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <app:authRequest>
      <dealer>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:Amount">
          <amount>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:Amount"/>
          </amount>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:BranchName">
          <branchName>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:BranchName"/>
          </branchName>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:BillIdentifier/com:AccountID">
          <dealerAccountNumber>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:BillIdentifier/com:AccountID"/>
          </dealerAccountNumber>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:DealerCode">
          <dealerCode>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:DealerCode"/>
          </dealerCode>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:DealerName">
          <dealerName>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:DealerName"/>
          </dealerName>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:PayMethod">
          <payMethod>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:PayMethod"/>
          </payMethod>
        </xsl:if>
        <xsl:if test="/eo:ESBMsg/eo:RqData/eo:Bill/com:BillIdentifier/com:BillID">
          <payRef>
            <xsl:value-of select="/eo:ESBMsg/eo:RqData/eo:Bill/com:BillIdentifier/com:BillID"/>
          </payRef>
        </xsl:if>
      </dealer>
    </app:authRequest>
  </xsl:template>
</xsl:stylesheet>
