<xsl:stylesheet version="1.0"
                exclude-result-prefixes="xsd xsi oracle-xsl-mapper xsl rs eo oraxsl DVMFunctions BasicCredentialsUserFunction UUIDUserFunction IsUserInRoleFunction IsUserInGroupFunction XrefFunctions"
                xmlns:eo="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:DVMFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.dvm.DVMFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:rs="urn:control.services.tiplus2.misys.com"
                xmlns:BasicCredentialsUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.BasicCredentialsUserFunction"
                xmlns:UUIDUserFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.UUIDUserFunction"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:IsUserInRoleFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInRoleFunction"
                xmlns:IsUserInGroupFunction="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.stages.functions.IsUserInGroupFunction"
                xmlns:XrefFunctions="http://www.oracle.com/XSL/Transform/java/com.bea.wli.sb.functions.xref.XrefFunctions"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:msg="urn:messages.service.ti.apps.tiplus2.misys.com"
                xmlns:fileo="http://xmlns.equitybank.co.ke/ESB/EO/Misc/File/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/RequesterServices/Misys/AppMetadata/V1/Control.xsd"/>
        <oracle-xsl-mapper:rootElement name="ServiceRequest" namespace="urn:control.services.tiplus2.misys.com"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../../../../ESBMetadata/ComponentLibrary/EnterpriseObjects/Transactions/Transfer/V1/TransferEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Transactions/Transfer/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [SUN MAY 17 18:03:07 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <eo:ESBMsg>
      <com:MsgID>
        <xsl:value-of select="/rs:ServiceRequest/msg:BatchRequest/rs:ServiceRequest/msg:Posting/msg:TransactionId"/>
      </com:MsgID>
      <com:Source>COR</com:Source>
      <com:MsgType>Requester</com:MsgType>
      <com:Service>TransferES</com:Service>
      <eo:RqData actionCode="AccountEntryPosting">
        <eo:Transfer>
          <xsl:for-each select="/rs:ServiceRequest/msg:BatchRequest/rs:ServiceRequest">
            <com:Transaction>
              <com:TransactionID>
                <xsl:value-of select="msg:Posting/msg:TransactionId"/>
              </com:TransactionID>
              <com:AccountIdentifier>
                <com:BankID>54</com:BankID>
                <com:AccountID>
                  <xsl:value-of select="msg:Posting/msg:AccountNumber"/>
                </com:AccountID>
                <com:AccountCurrency>
                  <xsl:value-of select="msg:Posting/msg:PostingCcy"/>
                </com:AccountCurrency>
              </com:AccountIdentifier>
              <com:TransactionType>
                <xsl:value-of select="msg:Posting/msg:DebitCreditFlag"/>
              </com:TransactionType>
              <com:TransactionReferenceNumber>
                <xsl:value-of select="msg:Posting/msg:MasterReference"/>
              </com:TransactionReferenceNumber>
              <com:TransactionDescription>
                <xsl:value-of select="msg:Posting/msg:EventReference"/>
              </com:TransactionDescription>
              <com:TransactionAmount currencyCode="{msg:Posting/msg:PostingCcy}">
                <xsl:value-of select="msg:Posting/msg:PostingAmount"/>
              </com:TransactionAmount>
              <com:Remarks>
                <xsl:value-of select="msg:Posting/msg:PostingNarrative1"/>
              </com:Remarks>
              <com:ValueDate>
                <xsl:value-of select="msg:Posting/msg:ValueDate"/>
              </com:ValueDate>
              <com:TicketNumber>
                <xsl:value-of select="msg:Posting/msg:PostingNarrative2"/>
              </com:TicketNumber>
            </com:Transaction>
          </xsl:for-each>
        </eo:Transfer>
      </eo:RqData>
    </eo:ESBMsg>
  </xsl:template>
</xsl:stylesheet>