<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:tns="http://xmlns.equitybank.co.ke/BS/Party/Customer/Rules/V1"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:ns1="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 ns1 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:com="http://xmlns.equitybank.co.ke/ESB/EO/Common/V1"
                xmlns:bio="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/Biometric/V1"
                xmlns:custeo="http://xmlns.equitybank.co.ke/ESB/EO/Parties/Customer/V1">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/EnterpriseObjects/Accounts/Account/V1/AccountEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Accounts/Account/V1"/>
        <oracle-xsl-mapper:param name="queryAccountDO"/>
      </oracle-xsl-mapper:source>
      <oracle-xsl-mapper:source type="XSD">
        <oracle-xsl-mapper:schema location="oramds:/apps/ESBMetadata/ComponentLibrary/EnterpriseObjects/Resilience/NationalIdentity/V1/NationalIdentityEO.xsd"/>
        <oracle-xsl-mapper:rootElement name="ESBMsg"
                                       namespace="http://xmlns.equitybank.co.ke/ESB/EO/Resilience/NationalIdentity/V1"/>
        <oracle-xsl-mapper:param name="queryNationalIdentityDO"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="XSD">
        <oracle-xsl-mapper:schema location="../Schemas/AccountOpenRules.xsd"/>
        <oracle-xsl-mapper:rootElement name="AccountOpenRulesRequest"
                                       namespace="http://xmlns.equitybank.co.ke/BS/Party/Customer/Rules/V1"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [WED MAY 13 23:52:24 EAT 2015].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:param name="queryNationalIdentityDO"/>
  <xsl:template match="/">
    <tns:AccountOpenRulesRequest>
      <tns:BirthDate>
        <xsl:value-of select="$queryNationalIdentityDO/ns1:ESBMsg/ns1:RsData/ns1:NationalIdentity/com:Person/com:BirthDate"/>
      </tns:BirthDate>
      <xsl:choose>
        <xsl:when test='$queryNationalIdentityDO/ns1:ESBMsg/ns1:RsData/ns1:NationalIdentity/com:Person/com:DeathDate != ""'>
          <tns:IsDeath>Y</tns:IsDeath>
        </xsl:when>
        <xsl:otherwise>
          <tns:IsDeath>N</tns:IsDeath>
        </xsl:otherwise>
      </xsl:choose>
      <tns:NationalID>
        <xsl:value-of select="$queryNationalIdentityDO/ns1:ESBMsg/ns1:RsData/ns1:NationalIdentity/com:NationalIdentityIdentifier/com:NationalIdentityID"/>
      </tns:NationalID>
      <tns:CustomerID>
        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
      </tns:CustomerID>
      <tns:Account>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric">
          <bio:Biometric>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricIdentifier">
              <com:BiometricIdentifier>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricIdentifier/com:BiometricID">
                  <com:BiometricID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricIdentifier/com:BiometricID"/>
                  </com:BiometricID>
                </xsl:if>
              </com:BiometricIdentifier>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricUserIdentifier">
              <com:BiometricUserIdentifier>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricUserIdentifier/com:BiometricUserID">
                  <com:BiometricUserID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricUserIdentifier/com:BiometricUserID"/>
                  </com:BiometricUserID>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricUserIdentifier/com:BiometricUserPin">
                  <com:BiometricUserPin>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:BiometricUserIdentifier/com:BiometricUserPin"/>
                  </com:BiometricUserPin>
                </xsl:if>
              </com:BiometricUserIdentifier>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage">
              <bio:BiometricImage>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints">
                  <com:FingerPrints>
                    <com:ImageL1>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL1"/>
                    </com:ImageL1>
                    <com:ImageL2>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL2"/>
                    </com:ImageL2>
                    <com:ImageL3>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL3"/>
                    </com:ImageL3>
                    <com:ImageL4>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL4"/>
                    </com:ImageL4>
                    <com:ImageL5>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageL5"/>
                    </com:ImageL5>
                    <com:ImageR1>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR1"/>
                    </com:ImageR1>
                    <com:ImageR2>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR2"/>
                    </com:ImageR2>
                    <com:ImageR3>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR3"/>
                    </com:ImageR3>
                    <com:ImageR4>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR4"/>
                    </com:ImageR4>
                    <com:ImageR5>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricImage/com:FingerPrints/com:ImageR5"/>
                    </com:ImageR5>
                  </com:FingerPrints>
                </xsl:if>
              </bio:BiometricImage>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier">
              <com:CustomerIdentifier>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier/com:BankID">
                  <com:BankID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier/com:BankID"/>
                  </com:BankID>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier/com:BankBIC">
                  <com:BankBIC>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier/com:BankBIC"/>
                  </com:BankBIC>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier/com:BranchID">
                  <com:BranchID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/com:CustomerIdentifier/com:BranchID"/>
                  </com:BranchID>
                </xsl:if>
              </com:CustomerIdentifier>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricType">
              <bio:BiometricType>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricType"/>
              </bio:BiometricType>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricStatus">
              <bio:BiometricStatus>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/bio:Biometric/bio:BiometricStatus"/>
              </bio:BiometricStatus>
            </xsl:if>
          </bio:Biometric>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier">
          <com:AccountIdentifier>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:BankID">
              <com:BankID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:BankID"/>
              </com:BankID>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:BankBIC">
              <com:BankBIC>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:BankBIC"/>
              </com:BankBIC>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:BranchID">
              <com:BranchID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:BranchID"/>
              </com:BranchID>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountID">
              <com:AccountID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountID"/>
              </com:AccountID>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:IBAN">
              <com:IBAN>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:IBAN"/>
              </com:IBAN>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountCurrency">
              <com:AccountCurrency>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountCurrency"/>
              </com:AccountCurrency>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountType">
              <com:AccountType>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountType"/>
              </com:AccountType>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountSubType">
              <com:AccountSubType>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:AccountIdentifier/com:AccountSubType"/>
              </com:AccountSubType>
            </xsl:if>
          </com:AccountIdentifier>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountType">
          <ns0:AccountType>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountType"/>
          </ns0:AccountType>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountSubType">
          <ns0:AccountSubType>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountSubType"/>
          </ns0:AccountSubType>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountOpenDate">
          <ns0:AccountOpenDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountOpenDate"/>
          </ns0:AccountOpenDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountOwnership">
          <ns0:AccountOwnership>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountOwnership"/>
          </ns0:AccountOwnership>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:ModeOfOperation">
          <ns0:ModeOfOperation>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:ModeOfOperation"/>
          </ns0:ModeOfOperation>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer">
          <custeo:Customer>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier">
              <com:CustomerIdentifier>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:BankID">
                  <com:BankID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:BankID"/>
                  </com:BankID>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID">
                  <com:CustomerID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:CustomerID"/>
                  </com:CustomerID>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:BranchID">
                  <com:BranchID>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:CustomerIdentifier/com:BranchID"/>
                  </com:BranchID>
                </xsl:if>
              </com:CustomerIdentifier>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerType">
              <custeo:CustomerType>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerType"/>
              </custeo:CustomerType>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person">
              <com:Person>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName">
                  <com:PersonName>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:FullName">
                      <com:FullName>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:FullName"/>
                      </com:FullName>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:FirstName">
                      <com:FirstName>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:FirstName"/>
                      </com:FirstName>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:MiddleName">
                      <com:MiddleName>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:MiddleName"/>
                      </com:MiddleName>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:LastName">
                      <com:LastName>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:LastName"/>
                      </com:LastName>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:ShortName">
                      <com:ShortName>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:ShortName"/>
                      </com:ShortName>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:Title">
                      <com:Title>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:PersonName/com:Title"/>
                      </com:Title>
                    </xsl:if>
                  </com:PersonName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:BirthDate">
                  <com:BirthDate>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:BirthDate"/>
                  </com:BirthDate>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:DeathDate">
                  <com:DeathDate>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:DeathDate"/>
                  </com:DeathDate>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:BirthCountry">
                  <com:BirthCountry>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:BirthCountry"/>
                  </com:BirthCountry>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:BirthCityName">
                  <com:BirthCityName>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:BirthCityName"/>
                  </com:BirthCityName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:GenderCode">
                  <com:GenderCode>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:GenderCode"/>
                  </com:GenderCode>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Language">
                  <com:Language>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Language"/>
                  </com:Language>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:NativeLanguage">
                  <com:NativeLanguage>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:NativeLanguage"/>
                  </com:NativeLanguage>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Nationality">
                  <com:Nationality>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Nationality"/>
                  </com:Nationality>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:MaritalStatus">
                  <com:MaritalStatus>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:MaritalStatus"/>
                  </com:MaritalStatus>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:MinorIndicator">
                  <com:MinorIndicator>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:MinorIndicator"/>
                  </com:MinorIndicator>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:NREIndicator">
                  <com:NREIndicator>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:NREIndicator"/>
                  </com:NREIndicator>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Occupation">
                  <com:Occupation>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Occupation"/>
                  </com:Occupation>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment">
                  <com:Employment>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:CompanyID">
                      <com:CompanyID>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:CompanyID"/>
                      </com:CompanyID>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:CompanyName">
                      <com:CompanyName>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:CompanyName"/>
                      </com:CompanyName>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Income">
                      <com:Income>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Income"/>
                      </com:Income>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Occupation">
                      <com:Occupation>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Occupation"/>
                      </com:Occupation>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address">
                      <com:Address>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:AddressType">
                          <com:AddressType>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:AddressType"/>
                          </com:AddressType>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineOne">
                          <com:LineOne>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineOne"/>
                          </com:LineOne>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineTwo">
                          <com:LineTwo>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineTwo"/>
                          </com:LineTwo>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineThree">
                          <com:LineThree>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineThree"/>
                          </com:LineThree>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineFour">
                          <com:LineFour>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:LineFour"/>
                          </com:LineFour>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:CityName">
                          <com:CityName>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:CityName"/>
                          </com:CityName>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:StateName">
                          <com:StateName>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:StateName"/>
                          </com:StateName>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:CountyName">
                          <com:CountyName>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:CountyName"/>
                          </com:CountyName>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:CountryName">
                          <com:CountryName>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:CountryName"/>
                          </com:CountryName>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:PostalCode">
                          <com:PostalCode>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:PostalCode"/>
                          </com:PostalCode>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:PreferredIndicator">
                          <com:PreferredIndicator>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Address/com:PreferredIndicator"/>
                          </com:PreferredIndicator>
                        </xsl:if>
                      </com:Address>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone">
                      <com:Phone>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:PhoneType">
                          <com:PhoneType>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:PhoneType"/>
                          </com:PhoneType>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:CompleteNumber">
                          <com:CompleteNumber>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:CompleteNumber"/>
                          </com:CompleteNumber>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:CountryCode">
                          <com:CountryCode>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:CountryCode"/>
                          </com:CountryCode>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:AreaCode">
                          <com:AreaCode>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:AreaCode"/>
                          </com:AreaCode>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:LocalNumber">
                          <com:LocalNumber>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:LocalNumber"/>
                          </com:LocalNumber>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:ExtensionNumber">
                          <com:ExtensionNumber>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:ExtensionNumber"/>
                          </com:ExtensionNumber>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:PreferredIndicator">
                          <com:PreferredIndicator>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Phone/com:PreferredIndicator"/>
                          </com:PreferredIndicator>
                        </xsl:if>
                      </com:Phone>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email">
                      <com:Email>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email/com:EmailType">
                          <com:EmailType>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email/com:EmailType"/>
                          </com:EmailType>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email/com:EmailAddress">
                          <com:EmailAddress>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email/com:EmailAddress"/>
                          </com:EmailAddress>
                        </xsl:if>
                        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email/com:PreferredIndicator">
                          <com:PreferredIndicator>
                            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:Employment/com:Email/com:PreferredIndicator"/>
                          </com:PreferredIndicator>
                        </xsl:if>
                      </com:Email>
                    </xsl:if>
                  </com:Employment>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FaceImage">
                  <com:FaceImage>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FaceImage"/>
                  </com:FaceImage>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints">
                  <com:FingerPrints>
                    <com:ImageL1>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL1"/>
                    </com:ImageL1>
                    <com:ImageL2>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL2"/>
                    </com:ImageL2>
                    <com:ImageL3>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL3"/>
                    </com:ImageL3>
                    <com:ImageL4>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL4"/>
                    </com:ImageL4>
                    <com:ImageL5>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageL5"/>
                    </com:ImageL5>
                    <com:ImageR1>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR1"/>
                    </com:ImageR1>
                    <com:ImageR2>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR2"/>
                    </com:ImageR2>
                    <com:ImageR3>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR3"/>
                    </com:ImageR3>
                    <com:ImageR4>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR4"/>
                    </com:ImageR4>
                    <com:ImageR5>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5/@mimeCode">
                        <xsl:attribute name="mimeCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5/@mimeCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5/@characterSetCode">
                        <xsl:attribute name="characterSetCode">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5/@characterSetCode"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5/@fileName">
                        <xsl:attribute name="fileName">
                          <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5/@fileName"/>
                        </xsl:attribute>
                      </xsl:if>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:FingerPrints/com:ImageR5"/>
                    </com:ImageR5>
                  </com:FingerPrints>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument">
                  <com:IdentityDocument>
                    <com:IdentityDocumentID>
                      <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IdentityDocumentID"/>
                    </com:IdentityDocumentID>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IdentityDocumentSerialNumber">
                      <com:IdentityDocumentSerialNumber>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IdentityDocumentSerialNumber"/>
                      </com:IdentityDocumentSerialNumber>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IdentityDocumentType">
                      <com:IdentityDocumentType>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IdentityDocumentType"/>
                      </com:IdentityDocumentType>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssueDate">
                      <com:IssueDate>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssueDate"/>
                      </com:IssueDate>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:ExpirationDate">
                      <com:ExpirationDate>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:ExpirationDate"/>
                      </com:ExpirationDate>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssuingCountry">
                      <com:IssuingCountry>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssuingCountry"/>
                      </com:IssuingCountry>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssuingLocation">
                      <com:IssuingLocation>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssuingLocation"/>
                      </com:IssuingLocation>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssuingAuthority">
                      <com:IssuingAuthority>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:IssuingAuthority"/>
                      </com:IssuingAuthority>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:DocImage1">
                      <com:DocImage1>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:DocImage1"/>
                      </com:DocImage1>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:DocImage2">
                      <com:DocImage2>
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:IdentityDocument/com:DocImage2"/>
                      </com:DocImage2>
                    </xsl:if>
                  </com:IdentityDocument>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:SignatureImage">
                  <com:SignatureImage>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Person/com:SignatureImage"/>
                  </com:SignatureImage>
                </xsl:if>
              </com:Person>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company">
              <com:Company>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company/com:CompanyName">
                  <com:CompanyName>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company/com:CompanyName"/>
                  </com:CompanyName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company/com:IncorporationDate">
                  <com:IncorporationDate>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company/com:IncorporationDate"/>
                  </com:IncorporationDate>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company/com:RegistrationCode">
                  <com:RegistrationCode>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Company/com:RegistrationCode"/>
                  </com:RegistrationCode>
                </xsl:if>
              </com:Company>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address">
              <com:Address>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:AddressType">
                  <com:AddressType>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:AddressType"/>
                  </com:AddressType>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineOne">
                  <com:LineOne>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineOne"/>
                  </com:LineOne>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineTwo">
                  <com:LineTwo>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineTwo"/>
                  </com:LineTwo>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineThree">
                  <com:LineThree>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineThree"/>
                  </com:LineThree>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineFour">
                  <com:LineFour>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:LineFour"/>
                  </com:LineFour>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:CityName">
                  <com:CityName>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:CityName"/>
                  </com:CityName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:StateName">
                  <com:StateName>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:StateName"/>
                  </com:StateName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:CountyName">
                  <com:CountyName>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:CountyName"/>
                  </com:CountyName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:CountryName">
                  <com:CountryName>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:CountryName"/>
                  </com:CountryName>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:PostalCode">
                  <com:PostalCode>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:PostalCode"/>
                  </com:PostalCode>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:PreferredIndicator">
                  <com:PreferredIndicator>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Address/com:PreferredIndicator"/>
                  </com:PreferredIndicator>
                </xsl:if>
              </com:Address>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone">
              <com:Phone>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:PhoneType">
                  <com:PhoneType>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:PhoneType"/>
                  </com:PhoneType>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:CompleteNumber">
                  <com:CompleteNumber>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:CompleteNumber"/>
                  </com:CompleteNumber>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:CountryCode">
                  <com:CountryCode>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:CountryCode"/>
                  </com:CountryCode>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:AreaCode">
                  <com:AreaCode>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:AreaCode"/>
                  </com:AreaCode>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:LocalNumber">
                  <com:LocalNumber>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:LocalNumber"/>
                  </com:LocalNumber>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:ExtensionNumber">
                  <com:ExtensionNumber>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:ExtensionNumber"/>
                  </com:ExtensionNumber>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:PreferredIndicator">
                  <com:PreferredIndicator>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Phone/com:PreferredIndicator"/>
                  </com:PreferredIndicator>
                </xsl:if>
              </com:Phone>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email">
              <com:Email>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email/com:EmailType">
                  <com:EmailType>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email/com:EmailType"/>
                  </com:EmailType>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email/com:EmailAddress">
                  <com:EmailAddress>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email/com:EmailAddress"/>
                  </com:EmailAddress>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email/com:PreferredIndicator">
                  <com:PreferredIndicator>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:Email/com:PreferredIndicator"/>
                  </com:PreferredIndicator>
                </xsl:if>
              </com:Email>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:RelationshipManagerName">
              <com:RelationshipManagerName>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:RelationshipManagerName"/>
              </com:RelationshipManagerName>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:RelationshipManagerEmailID">
              <com:RelationshipManagerEmailID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:RelationshipManagerEmailID"/>
              </com:RelationshipManagerEmailID>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerTaxCode">
              <custeo:CustomerTaxCode>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerTaxCode"/>
              </custeo:CustomerTaxCode>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerTaxID">
              <custeo:CustomerTaxID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerTaxID"/>
              </custeo:CustomerTaxID>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:PostingBranchID">
              <custeo:PostingBranchID>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:PostingBranchID"/>
              </custeo:PostingBranchID>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:HostSystem">
              <custeo:HostSystem>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:HostSystem"/>
              </custeo:HostSystem>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument">
              <com:PrimaryIdentityDocument>
                <com:IdentityDocumentID>
                  <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IdentityDocumentID"/>
                </com:IdentityDocumentID>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IdentityDocumentSerialNumber">
                  <com:IdentityDocumentSerialNumber>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IdentityDocumentSerialNumber"/>
                  </com:IdentityDocumentSerialNumber>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IdentityDocumentType">
                  <com:IdentityDocumentType>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IdentityDocumentType"/>
                  </com:IdentityDocumentType>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssueDate">
                  <com:IssueDate>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssueDate"/>
                  </com:IssueDate>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:ExpirationDate">
                  <com:ExpirationDate>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:ExpirationDate"/>
                  </com:ExpirationDate>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssuingCountry">
                  <com:IssuingCountry>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssuingCountry"/>
                  </com:IssuingCountry>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssuingLocation">
                  <com:IssuingLocation>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssuingLocation"/>
                  </com:IssuingLocation>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssuingAuthority">
                  <com:IssuingAuthority>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:IssuingAuthority"/>
                  </com:IssuingAuthority>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:DocImage1">
                  <com:DocImage1>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:DocImage1"/>
                  </com:DocImage1>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:DocImage2">
                  <com:DocImage2>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:PrimaryIdentityDocument/com:DocImage2"/>
                  </com:DocImage2>
                </xsl:if>
              </com:PrimaryIdentityDocument>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:StartDate">
              <com:StartDate>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:StartDate"/>
              </com:StartDate>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition">
              <com:TermsAndCondition>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementText">
                  <com:AgreementText>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementText"/>
                  </com:AgreementText>
                </xsl:if>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument">
                  <com:AgreementDocument>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument/@mimeCode">
                      <xsl:attribute name="mimeCode">
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument/@mimeCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument/@characterSetCode">
                      <xsl:attribute name="characterSetCode">
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument/@characterSetCode"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument/@fileName">
                      <xsl:attribute name="fileName">
                        <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument/@fileName"/>
                      </xsl:attribute>
                    </xsl:if>
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/com:TermsAndCondition/com:AgreementDocument"/>
                  </com:AgreementDocument>
                </xsl:if>
              </com:TermsAndCondition>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerStatus">
              <custeo:CustomerStatus>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/custeo:Customer/custeo:CustomerStatus"/>
              </custeo:CustomerStatus>
            </xsl:if>
          </custeo:Customer>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance">
          <com:Balance>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance/com:BalanceType">
              <com:BalanceType>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance/com:BalanceType"/>
              </com:BalanceType>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance/com:BalanceAmount">
              <com:BalanceAmount>
                <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance/com:BalanceAmount/@currencyCode">
                  <xsl:attribute name="currencyCode">
                    <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance/com:BalanceAmount/@currencyCode"/>
                  </xsl:attribute>
                </xsl:if>
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Balance/com:BalanceAmount"/>
              </com:BalanceAmount>
            </xsl:if>
          </com:Balance>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NoCreditStatus">
          <ns0:NoCreditStatus>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NoCreditStatus"/>
          </ns0:NoCreditStatus>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NoDebitStatus">
          <ns0:NoDebitStatus>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NoDebitStatus"/>
          </ns0:NoDebitStatus>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:DelinquencyStatus">
          <ns0:DelinquencyStatus>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:DelinquencyStatus"/>
          </ns0:DelinquencyStatus>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:RelationshipManagerName">
          <com:RelationshipManagerName>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:RelationshipManagerName"/>
          </com:RelationshipManagerName>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:RelationshipManagerEmailID">
          <com:RelationshipManagerEmailID>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:RelationshipManagerEmailID"/>
          </com:RelationshipManagerEmailID>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Amount">
          <com:Amount>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Amount/@currencyCode">
              <xsl:attribute name="currencyCode">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Amount/@currencyCode"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Amount"/>
          </com:Amount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:MobileWalletVendor">
          <com:MobileWalletVendor>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:MobileWalletVendor"/>
          </com:MobileWalletVendor>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:TransactionReferenceNumber">
          <com:TransactionReferenceNumber>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:TransactionReferenceNumber"/>
          </com:TransactionReferenceNumber>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:UserID">
          <ns0:UserID>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:UserID"/>
          </ns0:UserID>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:SolID">
          <com:SolID>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:SolID"/>
          </com:SolID>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaturityDate">
          <ns0:MaturityDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:MaturityDate"/>
          </ns0:MaturityDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate">
          <ns0:CurrentInterestRate>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate/@unitCode">
              <xsl:attribute name="unitCode">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate/@unitCode"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate/@baseValue">
              <xsl:attribute name="baseValue">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate/@baseValue"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate/@baseUnitCode">
              <xsl:attribute name="baseUnitCode">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate/@baseUnitCode"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:CurrentInterestRate"/>
          </ns0:CurrentInterestRate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate">
          <ns0:InterestRate>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate/@unitCode">
              <xsl:attribute name="unitCode">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate/@unitCode"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate/@baseValue">
              <xsl:attribute name="baseValue">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate/@baseValue"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate/@baseUnitCode">
              <xsl:attribute name="baseUnitCode">
                <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate/@baseUnitCode"/>
              </xsl:attribute>
            </xsl:if>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRate"/>
          </ns0:InterestRate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:TenorValue">
          <ns0:TenorValue>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:TenorValue"/>
          </ns0:TenorValue>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Remarks">
          <com:Remarks>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:Remarks"/>
          </com:Remarks>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestToDate">
          <ns0:InterestToDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestToDate"/>
          </ns0:InterestToDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestAccrued">
          <ns0:InterestAccrued>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestAccrued"/>
          </ns0:InterestAccrued>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:SettlementCurrency">
          <ns0:SettlementCurrency>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:SettlementCurrency"/>
          </ns0:SettlementCurrency>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LoanType">
          <ns0:LoanType>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LoanType"/>
          </ns0:LoanType>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:FundingAccount">
          <ns0:FundingAccount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:FundingAccount"/>
          </ns0:FundingAccount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:PaymentFrequency">
          <ns0:PaymentFrequency>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:PaymentFrequency"/>
          </ns0:PaymentFrequency>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:Original_Amount">
          <ns0:Original_Amount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:Original_Amount"/>
          </ns0:Original_Amount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:OutStanding_Amount">
          <ns0:OutStanding_Amount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:OutStanding_Amount"/>
          </ns0:OutStanding_Amount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:PastDueAmount">
          <ns0:PastDueAmount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:PastDueAmount"/>
          </ns0:PastDueAmount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LastPaymentAmount">
          <ns0:LastPaymentAmount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LastPaymentAmount"/>
          </ns0:LastPaymentAmount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LastPaymentReceivedDate">
          <ns0:LastPaymentReceivedDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:LastPaymentReceivedDate"/>
          </ns0:LastPaymentReceivedDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:TotalNumberofInstallments">
          <ns0:TotalNumberofInstallments>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:TotalNumberofInstallments"/>
          </ns0:TotalNumberofInstallments>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InstallmentsPaid">
          <ns0:InstallmentsPaid>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InstallmentsPaid"/>
          </ns0:InstallmentsPaid>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NextPaymentDate">
          <ns0:NextPaymentDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NextPaymentDate"/>
          </ns0:NextPaymentDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:DisbursementAccount">
          <ns0:DisbursementAccount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:DisbursementAccount"/>
          </ns0:DisbursementAccount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRepaymentAccount">
          <ns0:InterestRepaymentAccount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:InterestRepaymentAccount"/>
          </ns0:InterestRepaymentAccount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:Tenure">
          <ns0:Tenure>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:Tenure"/>
          </ns0:Tenure>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:ApprovedLimit">
          <ns0:ApprovedLimit>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:ApprovedLimit"/>
          </ns0:ApprovedLimit>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NextPrincipalDueDate">
          <ns0:NextPrincipalDueDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NextPrincipalDueDate"/>
          </ns0:NextPrincipalDueDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NextInterestDueDate">
          <ns0:NextInterestDueDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NextInterestDueDate"/>
          </ns0:NextInterestDueDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NoofDelayed_Payments">
          <ns0:NoofDelayed_Payments>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:NoofDelayed_Payments"/>
          </ns0:NoofDelayed_Payments>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:DisbursedAmount">
          <ns0:DisbursedAmount>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:DisbursedAmount"/>
          </ns0:DisbursedAmount>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountClosureFlag">
          <ns0:AccountClosureFlag>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountClosureFlag"/>
          </ns0:AccountClosureFlag>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:StartDate">
          <com:StartDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:StartDate"/>
          </com:StartDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:EndDate">
          <com:EndDate>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/com:EndDate"/>
          </com:EndDate>
        </xsl:if>
        <xsl:if test="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountStatus">
          <ns0:AccountStatus>
            <xsl:value-of select="/ns0:ESBMsg/ns0:RsData/ns0:Account/ns0:AccountStatus"/>
          </ns0:AccountStatus>
        </xsl:if>
      </tns:Account>
    </tns:AccountOpenRulesRequest>
  </xsl:template>
</xsl:stylesheet>
